### ISSUE TITLE
Chặn script QC trên bongtron.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#106]
**Rules đề xuất:**

```
bongtron.tv###adsModal
bongtron.tv##.show.fade.modal-backdrop
bongtron.tv##.mb-60.group-banner
bongtron.tv##.BannerFixedRight.BannerFixed
bongtron.tv##.BannerFixedLeft.BannerFixed
bongtron.tv##.BannerStickyRight
bongtron.tv##.BannerStickyLeft
bongtron.tv##.btn_cuoc
```

_P/S: Các script kiểu như dòng thứ 4, 5, 6, 7 còn xuất hiện nhiều trên các xem bóng đá khác, nên chăng tạo rule chung cho nhóm element này?_

**Comment by vhpcdpgl** [comment]
Các trang tương tự: `ghiban.tv, anhem.tv`...

**Comment by hoang-rio** [comment]
Mấy trang bóng đá này có đặc điểm là chết rất nhanh nên biết trang nào xử lý trang đó thôi bạn
