### ISSUE TITLE
imovies.vn

### ISSUE THREAD

**Issue by trinhcover** [abpvn/abpvn#11]
quảng cáo ở bên phải 1 link phim bất kì

http://imovies.vn/phim-le/arrival-su-menh-ngoai-giao/im3134.html

**Comment by abpvn** [comment]
Chào bạn. Mình đã nhận được thông tin. Mình sẽ kiểm tra khi có máy tính

**Comment by abpvn** [comment]
Đã fix ở commit https://github.com/abpvn/abpvn/commit/999ee4bd5fed8ef0013fd115c116d2f08cd93f4e Bạn update bộ lọc là ok nhé!
