### ISSUE TITLE
Bổ sung cho #112 (tructiep.xemchua.tv)

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#113]
_Bổ sung cho #112_

**Rule đề xuất:**

 `tructiep.xemchua.tv###myModal`

**Comment by hoang-rio** [comment]
lần sau nếu muốn udpate thì bạn comment ở issue cũ mà open lại issue nhé

**Comment by vhpcdpgl** [comment]
Mình reopen (app github trên android) ko được nên mới dùng cách này

**Comment by hoang-rio** [comment]
Mình vừa thử reopen trên Android vẫn được 😖

**Comment by vhpcdpgl** [comment]
> Mình vừa thử reopen trên Android vẫn được

Chắc là bạn được Github phân quyền cao hơn hay sao đó, mình cũng không rõ.
Trên PC mình dùng web browser thì không thấy chỗ nào ghi là "reopen", còn trên app Github cài trên Android thì có thấy nút "reopen" nhưng bấm vào không có tác dụng.
_(Trước đây bạn có đề cập vụ reopen với mình trên một issue cũ, lúc ấy mình cũng đã thử tìm nhưng không có)_
