### ISSUE TITLE
Chặn QC trên bongda365.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#116]
**Rules đề xuất:**

```
||upsieutoc.com^*.gif$domain=bongda365.tv
bongda365.tv##[class^="float-"]
##a.btn.mlt-btn-watch:nth-of-type(4)
##[href^="http://www.sbbanner.com/"]
##[href^="https://r88.vn/"]
##[href^="https://zbet.vn/"]
```

_Ngoài ra, trên trang này còn bung popup của qc.789.fun, nhưng nếu chặn href kiểu `#a[href^="https://qc.789.fun/"]` thì mất nội dung.
Ví dụ script popup:_

```
<div class="banners"> <a rel="nofollow" href="https://qc.789.fun/?utm_source=bongda365.tv&utm_medium=TopBanner_570x80_7&utm_campaign=CPD&utm_content=Home&utm_term=LII_CPD_B&a=LII_CPD_B" target="_blank" title="789 Clubgame bài đổi thưởng trên máy tính"> <img class="lazy" src="/themes/new/img/..png" data-src="https://www.upsieutoc.com/images/2020/05/25/570x80-789.gif" alt="789 Club đánh bài online đổi thưởng lấy tiền tiêu tết"> </a> </div>
```

**Comment by vhpcdpgl** [comment]
**Rule đề xuất:**

`bongda365.tv$$a[rel="nofollow"]`

**Comment by vhpcdpgl** [comment]
**Bổ sung rules để chặn hết các QC trên trang này và các trang tương tự:**

```
##[href^="https://388bet.top"]
##[href^="https://cacuoc247.com"]
##[href^="https://datcuoc247.com"]
##[href^="https://debet.com"]
##[href^="https://dp5755.wbet99.net"]
##[href^="https://five88.net"]
##[href^="https://keotot.net"]
##[href^="https://lp.zo.club"]
##[href^="https://m.five88.net"]
##[href^="https://m.lucky88.win"]
##[href^="https://mibet.win"]
##[href^="https://qc.789.fun"]
##[href^="https://qc.top88.club"]
##[href^="https://r88.vn"]
##[href^="https://tai.go88.club"]
##[href^="https://zbet.win"]
```

**Comment by hoang-rio** [comment]
> **Bổ sung rules để chặn hết các QC trên trang này và các trang tương tự:**
> 
> ```
> ##[href^="https://388bet.top"]
> ##[href^="https://cacuoc247.com"]
> ##[href^="https://datcuoc247.com"]
> ##[href^="https://debet.com"]
> ##[href^="https://dp5755.wbet99.net"]
> ##[href^="https://five88.net"]
> ##[href^="https://keotot.net"]
> ##[href^="https://lp.zo.club"]
> ##[href^="https://m.five88.net"]
> ##[href^="https://m.lucky88.win"]
> ##[href^="https://mibet.win"]
> ##[href^="https://qc.789.fun"]
> ##[href^="https://qc.top88.club"]
> ##[href^="https://tai.go88.club"]
> ##[href^="https://zbet.win"]
> ```

Những rule này mình không thêm được do là rule chung sẽ ảnh hưởng rất nhiều đến tốc độ của ABP. Và không có quá nhiều trang sử dụng
