### ISSUE TITLE
Chặn QC trên topphimhd.com/topphimmoi.net

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#119]
**Rules đề xuất:**
```
topphimhd.com,topphimmoi.net##.gnarty-offads
topphimhd.com,topphimmoi.net###float_content_right
topphimhd.com,topphimmoi.net###float_content_left
topphimhd.com,topphimmoi.net###hide_ballon_right
topphimhd.com,topphimmoi.net###hide_ballon_left
topphimhd.com,topphimmoi.net###hide_float_right
topphimhd.com,topphimmoi.net###hide_float_left
topphimhd.com,topphimmoi.net###ballon_content_right
topphimhd.com,topphimmoi.net###ballon_content_left
topphimhd.com,topphimmoi.net###closePC
topphimhd.com,topphimmoi.net###fixed_bottom
```

**Comment by hoang-rio** [comment]
Những rule này k kèm tên miền mình sẽ không cho vào bộ lọc nhé

**Comment by vhpcdpgl** [comment]
> Những rule này k kèm tên miền mình sẽ không cho vào bộ lọc nhé

Mình sẽ bổ sung sau bạn nhé!

**Comment by vhpcdpgl** [comment]
> Những rule này k kèm tên miền mình sẽ không cho vào bộ lọc nhé

Mình đã edit lại bạn ạ.

**Comment by vhpcdpgl** [comment]
Mình bổ sung thêm rule chặn popup `bit.ly`:

`topphimhd.com,topphimmoi.net##clearfix`

Mở một phim bất kỳ, trong khoảng 5 đến 10 giây đầu tiên trang bị mờ đi. Nếu click bất kỳ chỗ nào cũng bị bung popup dạng `bit.ly`
