### ISSUE TITLE
Ứng dụng Báo mới Android

### ISSUE THREAD

**Issue by PhamVanDac** [abpvn/abpvn#12]
Có thể chặn được quảng cáo trong ứng dụng Báo mới Android được không ạ?

**Comment by abpvn** [comment]
Không bạn ạ. ABPVN chưa hỗ trợ chặn quảng cáo trong ứng dụng

**Comment by PhamVanDac** [comment]
Mình dùng Aduard Android thấy mấy ứng dụng khác chặn được mà Báo mới thì không.

**Comment by abpvn** [comment]
Cái này bạn liên hệ adguard nhé. Mình không rõ cái này. Hơn nữa ABPVN cũng k hỗ trợ chính thức adguard

**Comment by PhamVanDac** [comment]
Ok, Cảm ơn bạn nhé.

**Comment by abpvn** [comment]
Mình đã dùng thử cả 2 app báo mới mình tìm được. Cài adaway là hết quảng cáo. Nhân tiện bạn close issue giúp mình luôn nhé
