### ISSUE TITLE
Chặn banner QC trên baonga.com

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#126]
**Rules đề xuất:**

```
baonga.com##div.monkey-qc
baonga.com##.monkey-gioithieu-daisu
baonga.com##.monkey-content-duoicanbiet
baonga.com##.monkey-banner-benphai-detail
||baonga.com/*quang_cao$image
||baonga.com/image*.gif
```

**Comment by stephenhawk8054** [comment]
New placeholder on top of page.

URL: `https://baonga.com/`

![image](https://user-images.githubusercontent.com/66517106/142748819-a940e7e0-0644-4f46-aba4-3503a6ed31e2.png)

Firefox 94.0.1, ublock 1.38.6 default + ABPVN

Proposed filter:

`baonga.com##.monkey-section-tinnoibat`
