### ISSUE TITLE
Bổ sung: Chặn QC trên player của banthang.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#129]
**Rules đề xuất:**

```
banthang.tv##.show-ads-banner
banthang.tv##.close-ads-player
banthang.tv##.close-ads

```

_P/S: Có vẻ các element này giống nhau ở nhiều trang xem bóng đá._

**Comment by hoang-rio** [comment]
> **Rules đề xuất:**
> 
> ```
> banthang.tv##.show-ads-banner
> banthang.tv##.close-ads-player
> banthang.tv##.close-ads
> ```
> 
> _P/S: Có vẻ các element này giống nhau ở nhiều trang xem bóng đá._

Mình sẽ dùng rule chung cho trường hợp này

**Comment by stephenhawk8054** [comment]
`banthang.tv`'s new domain is `banthang.co`. There are ads inside the page now. Click on video player triggers a popup.

URL: `https://banthang.co/truc-tiep-bong-da/leicester-city-chelsea-lm3517163.html`

![image](https://user-images.githubusercontent.com/66517106/142725660-33a70ada-649b-453e-b410-b12aa670ba98.png)

Firefox 94.0.1, ublock 1.38.6 default + ABPVN

Proposed filters:

```
/ad-banner/*$image,domain=banthang.co
/banner/*$image,domain=banthang.co
||cdn.firebase.com/js/client/*$script,domain=banthang.co
banthang.co##a[href^="/ads/"]
banthang.co##.top-bet-list
```

**Comment by hoang-rio** [comment]
I will check banthang.co by myself. Thanks for you report @stephenhawk8054
