### ISSUE TITLE
[Add] Truyentranh8.com

### ISSUE THREAD

**Issue by Ch3X4nh** [abpvn/abpvn#13]
Trang này có quảng cáo ở ngoài lẫn ở trang đọc truyện*cụ thể là gần cuối của truyện*
Mong ad thêm bộ lọc vào.

**Comment by abpvn** [comment]
Mình sẽ cập nhật. Cảm ơn bạn đã báo lỗi

**Comment by abpvn** [comment]
Mình đã update ở commit https://github.com/abpvn/abpvn/commit/2ed04c83f92ed4b71329fbac2d4418c517d3f7a8 rồi bạn nhé! Bạn update bộ lọc là ok
