### ISSUE TITLE
Đề xuất khắc phục lỗi player không load được phim trên m.vkool.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#130]
Hiện tại, `phim.vkool.tv` khi xem trên mobile thì chuyển thành `m.vkool.tv` và gặp lỗi không load được phim trên player;
Lỗi này đã được loại trừ khi xem trên PC vì ABPVN đã có rule chứa quy tắc loại trừ.
Do vậy mình đề xuất fix như sau:
**Rule hiện có:**

`.tv/*ads$script,domain=~phim.vkool.tv`

**Rule đề xuất fix:**

`.tv/*ads$script,domain=~vkool.tv`

**Comment by vhpcdpgl** [comment]
Mình đã thử thêm rule này vào thì player load được phim:
@@||vkool.tv/js/adsvk_v3.js

**Comment by hoang-rio** [comment]
Mình cập nhật rồi nhé
