### ISSUE TITLE
Chặn banner QC trên vietbao.com

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#131]
**Rules đề xuất:**

```
vietbao.com/*adv_counter
vietbao.com###nwwg_5609
vietbao.com###div-gpt-ad-1593398914201-0
vietbao.com##div[id^="adspot"]
```

**Comment by hoang-rio** [comment]
Rule
>vietbao.com###div-gpt-ad-1593398914201-0
thì EasyList đã xử lý ẩn bởi rule chung rồi nên mình không thêm. Còn các rule khác đã cập nhật rồi nhé
