### ISSUE TITLE
Chặn QC trên livestreambongda.tv/thuckhuya.net

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#136]
**Rules đề xuất:**

```
##.adTop
##.adBot
##.show.fade.modal-backdrop
###overlay
||livestreambongda.tv/*.gif
||thuckhuya.net/*.gif$image
||thuckhuya.net/*.mp4$media
```

**Note:**

- 4 rule đầu tiên dạng rule chung vì mình thấy các element này là phổ biến trên các trang tương tự
- Rule cuối chặn video QC dạng TVC phát vào các giây đầu tiên trên Player của trang

**Comment by hoang-rio** [comment]
2 Rule này
```
##.show.fade.modal-backdrop
###overlay
```
nguy hiểm và có thể chặn nhầm nên mình bỏ nhé
