### ISSUE TITLE
Không xem được video trên vtvgiaitri.vn

### ISSUE THREAD

**Issue by S-a-l-a-d** [abpvn/abpvn#141]
```
@@||vtvgiaitri.vn$generichide
```
Mình đã phải thêm rule này.

**Comment by hoang-rio** [comment]
Cái này có trong bộ lọc lâu rồi mà bạn. Bạn kiểm tra lại xem có bị lỗi cập nhật bộ lọc không?
https://github.com/abpvn/abpvn/blob/master/filter/src/abpvn_whitelist_elemhide.txt#L57
