### ISSUE TITLE
Chặn element QC trên vnews.gov.vn [TRUYỀN HÌNH THÔNG TẤN]

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#162]
__Rules đề xuất:__

```
vnews.gov.vn##.adshead
vnews.gov.vn##.popup-bg
vnews.gov.vn##.showpop
vnews.gov.vn##div[class^="adscode"]
```
![vnews](https://user-images.githubusercontent.com/59459998/92305180-f4e1ad00-efae-11ea-96b9-5542bdd9a84c.png)

**Comment by stephenhawk8054** [comment]
There's an ad banner at the top of the page now.

URL: `https://vnews.gov.vn/video/trung-quoc-dung-dau-cac-nuoc-xuat-khau-vaccine-covid-19-20123.htm`

![image](https://user-images.githubusercontent.com/66517106/143680548-b95d2a1b-7073-44cc-b197-8fcf319a82ab.png)

Firefox 94.0.2, ublock 1.39.0 default + ABPVN

Proposed filter:

`vnews.gov.vn##.banner-bottom-menu`
