### ISSUE TITLE
Chặn banner trên baoxaydung.com.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#165]
**_Rule đề xuất:_**

`baoxaydung.com.vn##.banner`

![image](https://user-images.githubusercontent.com/59459998/92455279-af5df380-f1eb-11ea-99c0-9dad4dc48904.png)

**Comment by vhpcdpgl** [comment]
P/S: có lẽ nên đặt rule chung là `.vn##.banner` thì sẽ bao quát hơn, nếu vướng website nào thì ta loại trừ sau.
Mình vẫn chưa biết xài PR trên github nên tạm thời vẫn dùng cách này, bác Hoàng thông cảm cho nhé.

**Comment by hoang-rio** [comment]
> P/S: có lẽ nên đặt rule chung là `.vn##.banner` thì sẽ bao quát hơn, nếu vướng website nào thì ta loại trừ sau.
> Mình vẫn chưa biết xài PR trên github nên tạm thời vẫn dùng cách này, bác Hoàng thông cảm cho nhé.

Để tạo PR thì bác phải fork project về account cá nhân trước đã
