### ISSUE TITLE
lỗi chặn quảng cáo làm màn hình đen

### ISSUE THREAD

**Issue by yagano1** [abpvn/abpvn#17]
Mình đang sài bộ lọc ABPVN List+EasyList nếu như bật chăn quảng cáo thì đôi khi xem phim nó sẽ ko load quảng cáo nhưng sẽ bị dính 1 cái màn hình đen che lại phim không xem dc chỉ có tiếng.

**Comment by abpvn** [comment]
Bạn vui lòng cung cấp cụ thể địa chỉ website để ABPVN kiểm tra nhé!

**Comment by yagano1** [comment]
vung.tv

**Comment by abpvn** [comment]
Mình đã fix ở commit 1d02f05 nhưng cần phải đợi đến chu kỳ cập nhật của ABPVN LIst+EasyList thì mới được cập nhật. Bạn có thể sử dụng bộ lọc EasyList riêng lẻ và ABPVN get từ trang chủ https://abpvn.com để được cập nhật nhanh hơn

**Comment by yagano1** [comment]
mình chuyển sang sài bộ lọc riêng thì thấy nó sót ra 1 cái quảng cáo nhó bên dưới khi đang ở trong xem phim http://prntscr.com/hp2u2i

**Comment by abpvn** [comment]
Dùng riêng nghĩa là bạn sử dụng 2 bộ lọc là EasyList và bộ lọc ABPVN List get từ trang chủ https://abpvn.com. Chứ không phải chỉ sử dụng ABPVN List.
![filter](https://user-images.githubusercontent.com/11514638/34108464-bd3cc748-e432-11e7-9b73-53584c34325b.PNG)
