### ISSUE TITLE
Đóng góp

### ISSUE THREAD

**Issue by qthinh4996** [abpvn/abpvn#18]
||egnatius-ear.com^  mình thấy ở trang https://vidoza.net/8h0p111k6mtm.html
Bộ lọc coin thì mình thấy https://github.com/hoshsadiq/adblock-nocoin-list là khá ổn đấy.

**Comment by abpvn** [comment]
Bạn có thể dùng thêm bộ lọc coin nếu cần thiết. Còn các đóng góp bạn cứ fork project rồi tạo pull request mình sẽ review và và accept nếu hợp lý

**Comment by qthinh4996** [comment]
||adnetwork.adasiaholdings.com^$third-party
mình thấy ở guu.vn
