### ISSUE TITLE
www.ucweb.com (false alarm)

### ISSUE THREAD

**Issue by 3xploiton3** [abpvn/abpvn#186]
![image](https://user-images.githubusercontent.com/19517680/96572868-9458c600-12f7-11eb-9550-bd971c9da867.png)

regular website

**Comment by hoang-rio** [comment]
I don't know where you got this alarm but in **ABPVN List** no rule with domain ucweb.com found. It mean **ABVPN List** is not block this domain

**Comment by 3xploiton3** [comment]
im using nextdns

**Comment by hoang-rio** [comment]
Please contact your service for help. ABPVN List is not contains this rule
