### ISSUE TITLE
Weblinhtinh.xyz

### ISSUE THREAD

**Issue by DiAnTTA** [abpvn/abpvn#193]
**Rule đề xuất:**
`||s1.animeweb.xyz/media/qcdd7$image`

`||weblinhtinh.xyz/wp-content/themes/halimmovies/adswebsite/jquery.popup.js$script `

**Link:** [https://weblinhtinh.xyz](https://weblinhtinh.xyz/) 
![Screenshot_20201128-010758~2](https://user-images.githubusercontent.com/74956696/100475659-4618bd00-3116-11eb-8e8b-538fbb991b94.png)

**Comment by qthinh4996** [comment]
Rule đề xuất:
||weblinhtinh.xyz/*/adswebsite
weblinhtinh.xyz##.btm_banner
