### ISSUE TITLE
m.truyentranh86.com

### ISSUE THREAD

**Issue by DiAnTTA** [abpvn/abpvn#194]
Quảng cáo dạng **Gif** và **Youtube**:
![IMG_20201201_005725](https://user-images.githubusercontent.com/74956696/100646691-ed912c00-3370-11eb-8c6d-65d265f6eba8.jpg)
**Link ví dụ:**
[http://m.truyentranh86.com/BTOOOM-chap-85](http://m.truyentranh86.com/BTOOOM-chap-85)

**Comment by hoang-rio** [comment]
Mình update ở 7ed6b99f rồi nhé
