### ISSUE TITLE
Chặn các script popup từ các tên miền ngẫu nhiên ở trang nettruyen.com

### ISSUE THREAD

**Issue by bigdargon** [abpvn/abpvn#197]
Link ví dụ: http://www.nettruyen.com/truyen-tranh/josou-shounen-anthology-comic/chap-6/221293

Đoạn script phát hiện

```
https://kz2oq0xm6ie7gn5dkswlpv6mfgci8yoe3xlqp12gjotp5fdjxs5ckztb8rzn.codes/tzq5w0oxm2fj8vkah6clmqji9oyt7ckawmbwjt8dg5jsaqjtjut8wikdzloyjev7fqxb6ckixmbr5pw6cjrz.js
```

Khi script được load sẽ kéo theo script mới với tên ngẫu nhiên khác nữa

```
http://kz2oq0xm6ie7gn5dkswlpv6mfgci8yoe3xlqp12gjotp5fdjxs5ckztb8rzn.codes/aq2g6fx0qp8ni4px0xton3cwry7ie1xm/n3tzm5pwmzx6uckiwhks2p7xjew5kf2oxj5akwrjazo/b8zo5k0lwx6kr5wizk2o.js
```

Mã nguồn của trang

```
<!--googleoff: all-->
<script type="text/javascript" src="//kz2oq0xm6ie7gn5dkswlpv6mfgci8yoe3xlqp12gjotp5fdjxs5ckztb8rzn.codes/tzq5w0oxm2fj8vkah6clmqji9oyt7ckawmbwjt8dg5jsaqjtjut8wikdzloyjev7fqxb6ckixmbr5pw6cjrz.js"></script><script type="text/javascript">document.write(ghz.yz6vqp2w0xg7qivt6qxhwm("PHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiIHNyYz0iLy9rejJvcTB4bTZpZTdnbjVka3N3bHB2Nm1mZ2NpOHlvZTN4bHFwMTJnam90cDVmZGp4czVja3p0Yjhyem4uY29kZXMvYXEyZzZmeDBxcDhuaTRweDB4dG9uM2N3cnk3aWUxeG0vbjN0em01cHdteng2dWNraXdoa3MycDd4amV3NWtmMm94ajVha3dyamF6by9iOHpvNWswbHd4NmtyNXdpemsyby5qcyI+PC9zY3JpcHQ+"));</script>
<!--googleon: all-->
```

Khi script được load sẽ kéo theo hàng loạt các tên miền chứa popup xuất hiện, bao gồm cả các tên miền đã có EasyList chặn và chưa có

```
azoaltou.com
ruwertur.com
jomtingi.net
denetsuk.com
heeteefu.com <- chưa có
```

![Screenshot (89)](https://user-images.githubusercontent.com/10969626/101583303-d6f07200-3a0d-11eb-9be5-0086a0b7feba.png)

Rule đề xuất

```
*.codes/*.js$script,domain=www.nettruyen.com
```

**Comment by stephenhawk8054** [comment]
There are ads in new domain `nettruyengo.com`

URL: `https://www.nettruyengo.com/truyen-tranh/asper-girl/chap-1/550366`

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/66517106/145324975-2e4bd9d0-3902-4210-869d-30307f7fd4f7.png)

![image](https://user-images.githubusercontent.com/66517106/145325008-930e73c2-e42a-4ce2-834e-ab4aee1a0168.png)

</details>

Firefox 95.0, ublock 1.39.2 default + ABPVN

Proposed fitlers:

```
||s.nettruyengo.com/*/banner/$image,domain=nettruyengo.com
nettruyengo.com##.container.mrb5
nettruyengo.com##.container > .mrb5
```

**Comment by hoang-rio** [comment]
@stephenhawk8054 Done via commit 1df470e
