### ISSUE TITLE
https://kissanime.ac/

### ISSUE THREAD

**Issue by yagano1** [abpvn/abpvn#21]
ko dùng dc

**Comment by hoang-rio** [comment]
Bạn có thể mô tả rõ hơn về vấn đề của bạn được không. Mình có thể hỗ trợ bạn thêm vào bộ lọc cá nhân. Do đây là trang web không phải tiếng việt nên mình không hỗ trợ thêm vào ABPVN được

**Comment by hoang-rio** [comment]
Để xem được phim trên trang này bạn có thể thêm bộ lọc sau vào bộ lọc cá nhân
```
@@||static.animecdn.stream/themes/vast/videojs.ima.js$domain=kissanime.ac
@@||static.animecdn.stream/themes/vast/videojs.ads.min.js$domain=kissanime.ac
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=kissanime.ac
@@||static.animecdn.stream/js/ads.js$domain=kissanime.ac
```
