### ISSUE TITLE
Lỗi trang CGV

### ISSUE THREAD

**Issue by zonprox** [abpvn/abpvn#219]
https://www.cgv.vn/ bị lỗi không chọn được ghế khi bật ABP.

**Comment by hoang-rio** [comment]
Trang này yêu cầu đăng nhập mới vào được chức năng như bạn nói nên nếu bạn có kiến thức về ABP bạn có thể xem ABP chặn gì gây lỗi rồi đề xuất quy tắc cho ABPVN nhé

**Comment by hoang-rio** [comment]
Mà trang này cơ bản là không có quảng cáo của bên khác nên mình nghĩ bạn tắt luôn ABP cũng được mà.
