### ISSUE TITLE
NetTruyenTop, NhatTruyenTranh

### ISSUE THREAD

**Issue by DiAnTTA** [abpvn/abpvn#222]
[NetTruyenTop.com](http://www.nettruyentop.com/truyen-tranh/19-days/chap-2/176050) & [NhatTruyenTranh.com](http://nhattruyentranh.com/truyen-tranh/19-days/chap-2/176050) 
- Rule đề xuất:
```
nettruyentop.com,nhattruyentranh.com##div.container > div.mrb5.mrt5
```
<details><summary>Screenshot:</summary>

| Trước khi ẩn | Sau khi ẩn |
|--------------|------------|
| ![IMG_20210522_124524](https://user-images.githubusercontent.com/74956696/119216084-ae5fbe80-bafb-11eb-91f9-35eeaf455fd7.jpg) | ![IMG_20210522_113850](https://user-images.githubusercontent.com/74956696/119215466-08f71b80-baf8-11eb-9e61-37f86ebcad25.jpg)

</details>

**Comment by DiAnTTA** [comment]
@hoang-rio 
Fix/Update rule:
~`nettruyentop.com,nhattruyentranh.com##div.container > div.mrb5.mrt5`~
```
nettruyentop.com,nhattruyentranh.com##div.container > div.text-center.mrt5.mrb5
```
Lý do: Rule không hiệu quả
| ![IMG_20210522_155441](https://user-images.githubusercontent.com/74956696/119221120-fee51500-bb17-11eb-9890-6b83d74c7166.jpg) | ![IMG_20210522_151844](https://user-images.githubusercontent.com/74956696/119220981-4ae38a00-bb17-11eb-88c8-d112b0e828c2.jpg) |
|--------------|------------|

**Comment by DiAnTTA** [comment]
2 rule bị dính chung 1 dòng rồi @hoang-rio 
![IMG_20210522_165858](https://user-images.githubusercontent.com/74956696/119222587-533fc300-bb1f-11eb-90e7-8beee768530d.jpg)

**Comment by hoang-rio** [comment]
Ok để mình xem lại

**Comment by DiAnTTA** [comment]
@hoang-rio 
Mình update bộ lọc ABPVN vẫn không có hiệu quả, nhưng dùng *"Bộ lọc của tôi"* thì lại được.😅

https://photos.app.goo.gl/pZCkRASwZTmRe7Ar5

**Comment by hoang-rio** [comment]
Mình sửa ngon rồi nhé. Tưởng rule của thím ngon cứ thế add vào. Ai ngờ chưa ngon

**Comment by DiAnTTA** [comment]
@hoang-rio Tại mình muốn giữ lại 2 nút ◀ ▶ này😁
![IMG_20210522_185858](https://user-images.githubusercontent.com/74956696/119225746-eb45a880-bb2f-11eb-8111-c6b9eefac407.jpg)

**Comment by hoang-rio** [comment]
Nhưng cơ bản nó còn k chạy mà thím

**Comment by DiAnTTA** [comment]
@hoang-rio Sao mình dùng [bộ lọc tùy chỉnh này]( https://raw.githubusercontent.com/DiAnTTA/dian/main/test.txt) trên 2 trình duyệt khác nhau lại có hiệu lực nhỉ?
| Firefox | [Vivaldi]( https://play.google.com/store/apps/details?id=com.vivaldi.browser) |
|--------------|------------|
| ![IMG_20210522_193943](https://user-images.githubusercontent.com/74956696/119227045-4aa6b700-bb36-11eb-9df3-1873874a440c.jpg) | ![IMG_20210522_193831](https://user-images.githubusercontent.com/74956696/119227081-79bd2880-bb36-11eb-89f1-7311c960b1c9.jpg)

**Comment by hoang-rio** [comment]
Cái này mình k rõ lắm thím ạ

**Comment by hoang-rio** [comment]
Mình vừa sửa lại dùng rule
```
nettruyentop.com##div.container > div.mrb5.mrt5.text-center
```
Thấy ok mà

**Comment by DiAnTTA** [comment]
@hoang-rio 
<details><summary>OK rồi 😂</summary>

![IMG_20210522_201348](https://user-images.githubusercontent.com/74956696/119227887-657b2a80-bb3a-11eb-9656-92621a17ecca.jpg)
