### ISSUE TITLE
hentaivn.tv

### ISSUE THREAD

**Issue by DiAnTTA** [abpvn/abpvn#225]
### ~Hentaivn.net~ [Hentaivn.tv](https://hentaivn.tv/) 

<details><summary>Screenshots</summary>

![Screenshot_2021-05-24-22-16-27-553_org mozilla firefox_beta](https://user-images.githubusercontent.com/74956696/119372886-06581a00-bce2-11eb-8044-788312d93dc2.jpg) | ![Screenshot_2021-05-24-22-18-16-806_org mozilla firefox_beta](https://user-images.githubusercontent.com/74956696/119376638-5df88480-bce6-11eb-8799-5c94d81cdbb5.jpg)
|--------------|------------|
</details>

- [ ] Đề xuất **thêm** 2 rules mới:
``` javascript
||static.htvncdn.net/qx/qx_catfish.php$subdocument
hentaivn.tv##.a_d_s_115
```
- [ ] Đề xuất **xóa** 3 rules cũ:
```javascript
||hentaivn.net/js/abp.js
||hentaivn.net/qc/
hentaivn.net###page_ads_right
```

**Comment by hoang-rio** [comment]
Sao bạn k thử contribute bằng cách fork project rồi tạo pull request nhỉ?
Combo mình đang dùng trên Android để sửa ABPVN bao gồm: 
# termux: để cài git và chạy file sh
# Xplorer để edit filter
# Firefox + Ublock Origin để tạo rule filter
