### ISSUE TITLE
[Coc Coc] Ads Frames & white space are displaying in some sites

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#240]
iOS
1) nhattruyen.com: Ads Frames
![image](https://user-images.githubusercontent.com/85873327/122345444-12966680-cf72-11eb-8752-b65adc3f45be.png)

2) metruyenchu.com: Ads Frames
![image](https://user-images.githubusercontent.com/85873327/122345647-470a2280-cf72-11eb-8c67-9452202df41a.png)

3) hitomi.la: White space
![image](https://user-images.githubusercontent.com/85873327/122347961-d3b5e000-cf74-11eb-9dfa-0fa953d0b6e4.png)

Android
anime47.com: White space
![image](https://user-images.githubusercontent.com/85873327/122352355-42953800-cf79-11eb-80ee-d70ccabed250.png)

**Comment by hangtt1** [comment]
Android:
anime47.com: White Space
![IMG_0861](https://user-images.githubusercontent.com/85873327/122353714-83418100-cf7a-11eb-8069-eb3477dd7b57.PNG)

**Comment by hoang-rio** [comment]
> nhattruyen.com
> metruyenchu.com
> anime47.com
Checking
> hitomi.la
Not Vietnamese website. You should report in EL repository
