### ISSUE TITLE
[Coc Coc] Still show Ads in Youtube layout

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#243]
1. Actual:
- Go to: https://www.youtube.com/watch?v=PxJG1RzM8dA
- Still see Ads in Youtube layout
![image](https://user-images.githubusercontent.com/85873327/123613740-e4483f00-d82d-11eb-9039-698d926abdd3.png)

2. Expected: No Ads in Youtube Layout

**Comment by hoang-rio** [comment]
I can not reprodue it. Here is my view
![Screenshot_20210628-170413.png](https://user-images.githubusercontent.com/11514638/123619469-67b85f00-d833-11eb-9319-d9fafca53082.png)

**Comment by hangtt1** [comment]
It still happens from my side. Can you re-try with other recommended video? @hoang-rio 
Below is another screenshot (different url: https://www.youtube.com/watch?v=ZJy2L8xED1U)
![image](https://user-images.githubusercontent.com/85873327/123622581-94ba4100-d836-11eb-9395-8a1dd5424ac4.png)

**Comment by hoang-rio** [comment]
I will try again later because currently i checked on new YT link I see no ads like you seen

**Comment by hoang-rio** [comment]
@hangtt1 The rule hide ads bellow video play exist in EL: https://github.com/easylist/easylist/blob/9df57c3e8eabf7f5b99ff84950077d62b66038c7/easylist/easylist_specific_hide.txt#L2614 Coc Coc can not hide it, it's Coc Coc issue

**Comment by hoang-rio** [comment]
@hangtt1 Because it's not Filter list's issue so I close this issue. You should report this issue to Coc Coc Adsblocker Engine team
