### ISSUE TITLE
[Coc Coc] White Space in zingnews.vn when turning on Ads Block

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#244]
1) Actual:
- Go to zingnews.vn/nuoc-di-sai-lam-cua-elon-musk-va-tesla-post1230390.html

![image](https://user-images.githubusercontent.com/85873327/123616625-a993d600-d830-11eb-8904-132d3146dfe3.png)

- See that there is still white space when turning on Ads block (This bug may happen sometimes in this link. I don't see the issue in my second attempt)

2) Expected: No white space any more when turning on Ads block

**Comment by hoang-rio** [comment]
Checked on CocCoc Mobile in Android and no whitespace found. This whitespace already hidden by `zingnews.vn##.banner` rule in ABPVN List

**Comment by hangtt1** [comment]
@hoang-rio Hi Hoang, I checked this url 2 times today. First time, see the issue as I reported. In my second time (3 hours later), I don't see it anymore. I have no idea of the root cause for this and not sure if user can get the same situation or not because as I see it does't always happen

**Comment by hoang-rio** [comment]
@hangtt1 OK. I will try to add element hide rule use id selector. I don't know how Coc Coc block ads but if with same rule but sometime not happen I think it's Coc Coc issue not Filter List's issue.
