### ISSUE TITLE
[Coc Coc] Pop-under ads in porn sites

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#245]
Dear Team,

In our recent research on "Understand the behaviour of users churned after 3 days usage", 30-40% users visiting porn sites are bothered by annoying pop-under ads (which directs to a new window or push the loaded advertisement back behind the browser). The report shows that Coc Coc users bothered by pop-under ads contributed to number of churned users . It's supposed that ads blocker mechanism is working on pop-up ads only and there is still an issue with pop-under ads. Please help to further investigate.

Please help refer to examples of pop-under ads in some porn sites that I've tested via https://drive.google.com/drive/folders/1YMX4iKMWxcVDxAORR7pXShiUtzzkRwcg?usp=sharing

**Comment by hoang-rio** [comment]
@hangtt1 in video i saw 2 porn sites. Do you have list of site have same pop under ads issue? If you provide a list i will check all of it and try to block pop under ads in that site if posible
Popup under ads not only problem of Coc Coc. ABP also can't block inline pop under ads except rule in https://github.com/abp-filters/abp-filters-anti-cv. Is Coc Coc use this list or support snippet filter rule?

**Comment by hoang-rio** [comment]
I checked two site in video but i see no popunder ads. Exits banner ads now blocked in ABPVN List.
@hangtt1 Did you know which filter list use in Coc Coc Mobile in difference language? May be in English Coc Coc is not use ABPVN List as adblock filter list

**Comment by hoang-rio** [comment]
@hangtt1 Anything new about list porn sites?

**Comment by hangtt1** [comment]
Hi @hoang-rio,
1. Do you have list of site have same pop under ads issue?
> Reply: I just tested randomly some porn sites and see the issue here
2. Is Coc Coc use this list or support snippet filter rule?
> Reply: We dont use https://github.com/abp-filters/abp-filters-anti-cv
3.Did you know which filter list use in Coc Coc Mobile in difference language?
> Reply: We default use Vietnamese language ABPVN

**Comment by hoang-rio** [comment]
@hangtt1 
> 3.Did you know which filter list use in Coc Coc Mobile in difference language?
What about EasyList or any other English filter list?
ABPVN only support Vietnamese website or Vietnamese source (Vietnamese domain or webmaster is Vietnamese) and will never add exist rule in EasyList. If Coc Coc only use ABPVN List without any English filter list. Much of ads still exist

**Comment by hoang-rio** [comment]
@hangtt1 Please comment when have something new to reopen
