### ISSUE TITLE
Chặn banner QC trên trang suckhoedoisong\<dot>vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#246]
**Rule đề xuất:**
`suckhoedoisong.vn##.close_ads_all`

Vị trí banner: Cột phải

Hình:

![ảnh](https://user-images.githubusercontent.com/59459998/125266885-796c2d00-e330-11eb-999b-6c7e5b6e0782.png)

**Comment by hoang-rio** [comment]
Mình kiểm tra thì không thấy quảng cáo như ảnh bạn chụp là sao nhỉ?

**Comment by vhpcdpgl** [comment]
> Mình kiểm tra thì không thấy quảng cáo như ảnh bạn chụp là sao nhỉ?

![ảnh](https://user-images.githubusercontent.com/59459998/125376286-e1fced80-e3b4-11eb-95e0-9cf975608cc4.png)

**Comment by vhpcdpgl** [comment]
Mình dùng uBlock origin trên firefox, đã bật bộ lọc ABPVN nhưng vẫn dính QC banner này
