### ISSUE TITLE
[Coc Coc] ABP still leaves blank space

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#251]
Actual: ABP still leaves blank space

Example page: 24h.com

https://drive.google.com/file/d/1lVuQO8Wnu1qMUGHpG6mcwfchmdfBggb3/view

Expected: No blank space any more in all pages

**Comment by hoang-rio** [comment]
No use full information => reject

**Comment by hangtt1** [comment]
Hi Hoang, 
Sorry for the late reply. Please help check the image attached.

This happens in 24h.com

![image](https://user-images.githubusercontent.com/85873327/131516726-49fbf6c6-05c6-405e-b10d-7dfc9eb09594.png)

**Comment by hoang-rio** [comment]
No blank space in CocCoc Android and another brower with Adblocker extention and ABPVN List. It's mean it's bug from CocCoc iOS when process elemhide rule.
![Screenshot_20210831-215355.png](https://user-images.githubusercontent.com/11514638/131525862-09b66bd1-a082-477f-9e08-7ba53f760ec4.png)

**Comment by hoang-rio** [comment]
No blank space in ios too. But sometime ads flashing with a moment before hide. It's not filter issue. ![image](https://user-images.githubusercontent.com/11514638/131527317-df26703f-a486-4222-bbca-375f75c6f136.jpeg)
