### ISSUE TITLE
[Coc Coc] ABP changes the position of the site

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#252]
Actual: ABP changes the position of the site, users cannot read the whole title if they do not scroll up (video at 2.50)

https://drive.google.com/file/d/1Wl0HvGebSwWz75UMCwnz2Wrk25K7EScw/view?usp=sharing

Expected: Not change the position of site

**Comment by hoang-rio** [comment]
No use full information. ABPVN will reject all issue with video only

**Comment by hangtt1** [comment]
Dear Hoang,

Sorry for the late reply, please help refer to attached image.

This issue happens in dantri.com.vn.

Image 1: When Adblock has been turned on in Coc Coc app
Image 2: When Adblock hasn't been turned on

We can see that users cannot read the whole title if they do not scroll up (Image 1). I believe, somehow the position of the site has been affected by Ads banner here. For more info, please help see video at 2.50

![image](https://user-images.githubusercontent.com/85873327/131517271-b9af17b5-f57a-4ef1-8abf-3d91eb3aa438.png)

**Comment by hoang-rio** [comment]
It work normally. You should to know when element hidden by adblocker elmement bellow only fill hidden space with height of hidden space.![image](https://user-images.githubusercontent.com/11514638/131528773-950c537a-649e-4c6b-8393-b5d54f8a9cd0.png)

**Comment by hangtt1** [comment]
Noted. Thanks!
