### ISSUE TITLE
[Coc Coc] ABP blocks articles of news site

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#253]
Actual: ABP also blocks articles of the news site

https://drive.google.com/file/d/1Wl0HvGebSwWz75UMCwnz2Wrk25K7EScw/view

Expected: Not block article of news site

**Comment by hoang-rio** [comment]
No usefull information. ABPVN will reject all issue with video only

**Comment by hangtt1** [comment]
Hi Hoang,
Sorry for the late reply.
This issue happens in https://dantri.com.vn/

Attached here is the screenshot when we tested:
![image](https://user-images.githubusercontent.com/85873327/131518814-58e4ab22-80f7-48f2-bdc1-ef8e9e9b428e.png)

Image 1: Adblock turns on
Image 2: Adblock turns off

We can see that in Image 1, an article has been dismissed (title: "Nga bắt nhà khoa học nghi tuồn công nghệ siêu vượt âm cho nước ngoài"), compared to Image 2

See more at 0.55s in video https://drive.google.com/file/d/1Wl0HvGebSwWz75UMCwnz2Wrk25K7EScw/view?usp=sharing

Hope this is clear enough.
Many thanks!

**Comment by hoang-rio** [comment]
Fixed

**Comment by hangtt1** [comment]
Hi Hoàng, 

It's pity that I still got the issue in my device now.

![image](https://user-images.githubusercontent.com/85873327/132485785-382e90c0-5f47-4bcc-a71b-0be5153f6dac.png)

Image 1: ABP has been disabled
Image 2: ABP has been enabled

Domain: https://dantri.com.vn/

Environment: Coc Coc 98.0.278

Please help check.

**Comment by hoang-rio** [comment]
I sure that it not issue of ABPVN. The rule hide this item is removed when i close this issue. If CocCoc still hide this element it may be ABPVN List in CocCoc is outdate. CocCoc has no debug option so i only can check in another browser

**Comment by hangtt1** [comment]
Dear Team,

I would like to reopen this ticket to report on the related remaining issue.

To resolve the above issue (News has been blocked in dantri.com), Coc Coc Team disabled the rule **dantri.com.vn##div[id^="xds** which we found is the root cause of blocked news. However, this removed rule has been recently re-added to the file from ABP side. Hence, news are still blocked.

Please help recheck if dantri.com.vn##div[id^="xds is used to block any blocking ads rule from side or not. It is suggested that in case it has been used to block Ads, please help consider to user another rule. In case it has not been used to block Ads, could please help consider to remove it from the file because it is blocking news in dantri.com.

Many thanks,
Hang Tran

**Comment by hoang-rio** [comment]
> Dear Team,
> 
> I would like to reopen this ticket to report on the related remaining issue.
> 
> To resolve the above issue (News has been blocked in dantri.com), Coc Coc Team disabled the rule _**dantri.com.vn##div[id^="xds**_ which we found is the root cause of blocked news. However, this removed rule has been recently re-added to the file from ABP side. Hence, news are still blocked.
> 
> Please help recheck if **_dantri.com.vn##div[id^="xds_** is used to block any blocking ads rule from side or not. It is suggested that in case it has been used to block Ads, please help consider to user another rule. In case it has not been used to block Ads, could please help consider to remove it from the file because it is blocking news in dantri.com.
> 
> I would like to attach some screenshots as below for your reference: ![image](https://user-images.githubusercontent.com/85873327/143803803-15655091-307e-4eb9-a54b-b6d5c42ad91e.png) ![image](https://user-images.githubusercontent.com/85873327/143803831-727afa89-7980-4850-9cef-7009b565398c.png)
> 
> Many thanks, Hang Tran

It updated in 5ac9d151

**Comment by hangtt1** [comment]
Thanks Hoang,

We are checking and let you know then.

BR,
