### ISSUE TITLE
[Coc Coc] ABP Blocks images of articles

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#254]
Actual: ABP Blocks images of articles
https://drive.google.com/file/d/1duBkHbQVlW4NjlT9JzAwfnHL9g6mUnbx/view?usp=sharing

Expected: not block image

**Comment by hoang-rio** [comment]
No use full information. ABPVN will reject all issue with video only

**Comment by hangtt1** [comment]
Hi Hoang,

So sorry for the late reply.
This happens in zingnews.vn

Image 1: Turn on ABP
Image 2: Turn off ABP

![image](https://user-images.githubusercontent.com/85873327/131519992-70018bc1-897f-41c6-a3f9-051a5c70a7b2.png)

We can see that in Image 1, when ABP has been turned on, an image of article has been removed.

BR,

**Comment by hoang-rio** [comment]
Fixed
