### ISSUE TITLE
[Coc Coc] ABP Blocks notifications of sites

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#255]
Actual: ABP Blocks notifications of sites
https://drive.google.com/file/d/1o0BMpixcITi871VQjTNSHKpCbw6u0tx9/view?usp=sharing

Expected: No block notifications

**Comment by hoang-rio** [comment]
No use full information => reject

**Comment by hoang-rio** [comment]
Close because currently website has not notifcation to check

**Comment by hangtt1** [comment]
Hi Hoang,

Hope that my image below will provide more info for your further checking.

This happens in metruyenchu.com

Image 1: Turn on ABP
Image 2: Turn off ABP
We can see that the notification in Image 2 has been removed, compared to Image 1 when ABP has been turned on.

![image](https://user-images.githubusercontent.com/85873327/131520618-78b14cb6-7fe6-4011-b037-0a53b9a76758.png)

See more Video at 0.15s for further insight.

Many thanks!

**Comment by hoang-rio** [comment]
This site currently hide this notification or it not display on my device so i can not reproduce. I trying turn off ABP and use default browser without Adblock. Please check with current status of this website and tell me know if this issue still appear.![image](https://user-images.githubusercontent.com/11514638/131532440-648821ad-b9c9-4043-806a-157fe6e994a1.png)
