### ISSUE TITLE
[Coc Coc] ABP blocks access to movie

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#256]
Actual: ABP blocks access to movie so it can not play but has no notification to warn users

https://drive.google.com/file/d/1rKiKXTmxqfEsQkCmJbTGNJrdgBOkDNoS/view?usp=sharing

Expected: Not block access to movie

**Comment by hoang-rio** [comment]
@hangtt1 Please provide useful information. If not this issue with be reject

**Comment by hangtt1** [comment]
Hi Hoang, 
So sorry for the late reply.

This happens in motphim.net

Image 1: Turn off ABP
Image 2: Turn on ABP

![image](https://user-images.githubusercontent.com/85873327/131521858-0648a10c-c234-45d8-8b0e-f4c0721725d1.png)

Image 2 shows that when ABP has been turned on, the video cannot be played. We expect that ABP will not affect the video play.

For more info, please help see video at 0.51s (https://drive.google.com/file/d/1rKiKXTmxqfEsQkCmJbTGNJrdgBOkDNoS/view?usp=sharing).

Hope that this info is clear enough. :-)

Many thanks!

**Comment by hoang-rio** [comment]
Domain motphims.net is currently not accessible. I also check another domain of this site motphjm.net and movie can play normally. Can you provide full u of this site? Most of movie website use multiple source for movie and random load iframe source for each visit so it may not ABP issue.

**Comment by hoang-rio** [comment]
I found another issue in motphjm.net in only CocCoc Android but CocCoc Android does not support remote debug so I have no way to find the issue because in another debug able device it can not reproduce. @hangtt1 Please confirm this issue before end of to day if not it will be close again.

**Comment by hangtt1** [comment]
Thanks @hoang-rio for the information. We will provide more info if we see it happen regularly.
