### ISSUE TITLE
Exist ads on website: https://vnexpress.net/

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#260]
* Steps:
1. Go to https://vnexpress.net/
2. Click on https://vnexpress.net/nong-san-mien-tay-trong-vong-xoay-dich-benh-4350358.html to read news
3. Pop up an ads which cover the whole page

**Website url**
Direct website url contains ads: https://vnexpress.net/nong-san-mien-tay-trong-vong-xoay-dich-benh-4350358.html

**Screenshot**
<details>
<summary>With ABPVN Enabled (Default enable ABP in Coc Coc)</summary>

![IMG_6392](https://user-images.githubusercontent.com/85873327/132157451-d1248f13-898a-44fc-8512-8ffc2ee756b5.PNG)
</details>

**Environment**
Coc Coc ver 98.0.278

**Comment by hoang-rio** [comment]
I tried many time but i can not reproduce. It may be random ads because i try with Adblock Disabled no popup shown

**Comment by hangtt1** [comment]
Hi Hoang,

Can you please  help re-try to re-download Coc Coc app (iOS) in Store and try with some random links in vnexpress?
I newly download and see the issue with most of the articles (vnexpress, kenh14, dantri, etc) with banner ads at the top of the page, middle of page)

Example: 

*Ads at top of the page:
![image](https://user-images.githubusercontent.com/85873327/132279543-0e4a2c0d-2848-4d9d-b1d8-875ecbd781d1.png)

Link: https://vnexpress.net/bui-tien-dung-duoc-dang-ky-cho-tran-australia-4352054.html

*Ads at the middle of the page:
![image](https://user-images.githubusercontent.com/85873327/132279645-8b968292-5892-4b08-8c29-1d961384a15a.png)


Besides, this time I also see kind of ads at the top of the page when the page is loading (See below, sometimes it's blank ads, sometimes it shows a clear ads at the position). Once the page completes its loading, the ads at the top disappears.
![image](https://user-images.githubusercontent.com/85873327/132280299-69b1a316-0eb0-4571-b91b-81ff236310c2.png)

**Comment by hoang-rio** [comment]
@hangtt1 Fiber Cable in Vietnamese has issue. It make filter list download failed so without complete filter list ads will be show. It not problem come from filter list
