### ISSUE TITLE
[Coc Coc iOS] Request to turn off Adblocker: javcl.com

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#264]
1) Steps & actual:
- Go to https://javcl.com 

- Open a random link (https://javcl.com/right-after-i-after-fucked-her-i-fucked-her-again-100-times-in-a-row-480-minutes-of-women-who-are-fucked-to-oblivion-and-can-never-cum-back/)

- Display a request to turn off Adblocker from the site
![image](https://user-images.githubusercontent.com/85873327/135374875-a27c0216-103b-4727-8e96-8ae956164932.png)

2) Expected: No request to turn off adblocker and user can directly play the video

Environment: Coc Coc 98.0.286 (iOS)

**Comment by hoang-rio** [comment]
This non Vietnamese website is not directly support by ABPVN but I've just created a PR on easylist repo. Please follow easylist/easylist#9273
