### ISSUE TITLE
anime47.com

### ISSUE THREAD

**Issue by Salin1810** [abpvn/abpvn#27]
Có quảng cáo mới ở vị trí này:

1.
![untitled](https://user-images.githubusercontent.com/31431375/49683163-c3466400-faf2-11e8-9b8a-7b5476ed08b3.png)
Link test: https://anime47.com/

2. 
![2](https://user-images.githubusercontent.com/31431375/49683245-ee7d8300-faf3-11e8-8b28-43f2885a6224.png)
Link test: https://anime47.com/phim/tensei-shitara-slime-datta-ken/m6791.html

3.
![3](https://user-images.githubusercontent.com/31431375/49683242-e9203880-faf3-11e8-9fc4-e20617c75710.png)
Link test: https://anime47.com/xem-phim-tensei-shitara-slime-datta-ken-ep-10/157760.html

**Comment by hoang-rio** [comment]
Đã fix ở commit 47eb26c
