### ISSUE TITLE
Exist ads on website: NetTruyenPro.com

### ISSUE THREAD

**Issue by DiAnTTA** [abpvn/abpvn#273]
**Ads description**
Blank ad placeholder

**Website url**
http://www.nettruyenpro.com/truyen-tranh/pham-nhan-tu-tien/chap-1/15238

<details>
<summary>Screenshot</summary>

![IMG_20211016_091248](https://user-images.githubusercontent.com/74956696/137569759-dd8c7744-a3e0-40cf-86da-8e23544044cf.jpg)
</details>

**Environment**
|Browser|browserVersion|Extention|extensionVersion|Subscription Filter|
|---|---|---|---|---|
|Firefox Beta for Android|[94.0.0-beta.3](https://github.com/mozilla-mobile/fenix/releases/tag/v94.0.0-beta.3)|uBlock Origin|1.38.4|uBlock's default mode + ABPVN List|

**Comment by hoang-rio** [comment]
Mình có kiểm tra và không thấy popup nào như ảnh bạn chụp

**Comment by DiAnTTA** [comment]
Sau khi nhấn nút 🕘 "Purge all caches" và "Update now" thì không còn vấn đề nữa.
