### ISSUE TITLE
Anti-adblock: [getlink.tienichmaytinh.net]

### ISSUE THREAD

**Issue by stephenhawk8054** [abpvn/abpvn#275]
**Ads description**
No captcha due to anti-adblock

**Step to reproduce**
1. Go to website: `https://getlink.tienichmaytinh.net/Exj4ah`

**Website url**
[https://getlink.tienichmaytinh.net/Exj4ah](https://getlink.tienichmaytinh.net/Exj4ah)

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

![image](https://user-images.githubusercontent.com/66517106/138208718-48c975a4-c86c-4b68-b3a3-5cfbec6199d5.png)

</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image](https://user-images.githubusercontent.com/66517106/138208783-3276242c-c61d-4b7b-a241-f28667909ac6.png)

</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Firefox|93|ublock origin|1.38.6|Default settings and filter lists + ABPVN|

Cause: 
`*$document,csp=script-src 'self' 'unsafe-inline',domain=nousdecor.com|fidlarmusic.com|kingsleynyc.com|thegoneapp.com|staaker.com|uebnews.online|nro.vn|linkcc.pro|khophimhd.net|appvn.com|tienichmaytinh.net|kiemlua.com`

**Comment by stephenhawk8054** [comment]
Not anti-adblock, but incorrect blocking with the same filter above.

URL: `https://linkcc.pro/mEjC`

<details>
<summary>With ABPVN Enabled</summary>

![image](https://user-images.githubusercontent.com/66517106/141057019-9a7cbefd-b629-4fc3-8e38-d796bc387659.png)

</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image](https://user-images.githubusercontent.com/66517106/141057054-a51ed001-fb9f-4759-bf3c-8e9343149131.png)

</details>

**Comment by hoang-rio** [comment]
Fixed on lastest commit
