### ISSUE TITLE
linkneverdie.com

### ISSUE THREAD

**Issue by Salin1810** [abpvn/abpvn#28]
Bạn có thể xóa 2 dòng 
linkneverdie.com###asdf (Line 577)
linkneverdie.com#?#a:-abp-has(#adsqc) (Line 578)
linkneverdie dựa vào 2 dòng ấy để phát hiện sử dụng adblock

**Comment by hoang-rio** [comment]
Mình vừa truy cập trang linknervedie.com vẫn có quy tắc kia và không thấy có phát hiện quảng cáo nào hiện ra hết. Vì vậy không cần xoá
