### ISSUE TITLE
[NSFW] Popup on website: [lxhentai.com]

### ISSUE THREAD

**Issue by stephenhawk8054** [abpvn/abpvn#283]
**Ads description**
A banner appears, and clicking on close triggers a popup

**Step to reproduce**
1. Go to website: `https://lxhentai.com/`
2. Click on close button of the white banner

**Website url**
`https://lxhentai.com/`

**Screenshot**

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|95|ublock origin|1.38.6|ublock default + ABPVN|

Proposed filter:

`lxhentai.com##+js(acis, document.cookie)`

**Comment by stephenhawk8054** [comment]
Another website with similar behavior: `https://phimgii.net/`

Proposed filter: `phimgii.net##+js(acis, jQuery, popurl)`

**Comment by stephenhawk8054** [comment]
Another site: `https://rphangs.net/threads/em-rau-nvvp.87087/` [NSFW]

Click on the image in the first post, a popup appears.

Proposed filter: `rphangs.net##+js(acis, document.querySelectorAll, popMagic)`

**Comment by stephenhawk8054** [comment]
Another site: `https://tapmoi.net/vua-banh-mi-tap-81/`

Click on any videos at the right side list, a quick popup appears.

Proposed filter: `tapmoi.net##+js(acis, navigator, SmartPopunder)`

**Comment by stephenhawk8054** [comment]
Another site: `https://zo3x.ml/` [NSFW]

Click on play button, a popup appears.

Old domain is `zo3x.com`

Proposed filter: `zo3x.*##+js(aopr, open)`

**Comment by hoang-rio** [comment]
Your suggested rule now added in to ABPVN List. Now i know `^script:has-text()` only work on Firefox so i will use `+js` rule in the future to compare with all browser
