### ISSUE TITLE
[NSFW] Exist ads on website: [phim18zz.com]

### ISSUE THREAD

**Issue by stephenhawk8054** [abpvn/abpvn#286]
**Ads description**
Ads. Old domain is `phim18z.net`

**Step to reproduce**
1. Go to website: `https://phim18zz.com/`

**Website url**
`https://phim18zz.com/`

**Screenshot**
<details>

[NSFW screenshot 1](https://i.ibb.co/WD7Gf4s/image.png)
[NSFW screenshot 2](https://i.ibb.co/n3nBGvp/image.png)

</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Firefox|94.0.1|ublock origin|1.38.6|ublock default + ABPVN|

Proposed filters:

```
/assets/themes/js/wonderfarm$script,domain=huphimtv.com|phim18z.net|phim18zz.com
/ads33.js$script,domain=phim18zz.com
||img.steamaz.co^*.gif$domain=xemphimvui.net|phim18z.net|huphimtv.com|phim18zz.com
phim18zz.com##.pcCatfish
```

**Comment by hoang-rio** [comment]
@stephenhawk8054  Is old domain phim18z.net redirect to new domain phim18zz.com?

**Comment by stephenhawk8054** [comment]
> 
> 
> @stephenhawk8054 Is old domain phim18z.net redirect to new domain phim18zz.com?

Yup, it redirects to `phim18zz.com` for me.

**Comment by hoang-rio** [comment]
> > @stephenhawk8054 Is old domain phim18z.net redirect to new domain phim18zz.com?
> 
> Yup, it redirects to `phim18zz.com` for me.

Ok. So i will replace old with new
