### ISSUE TITLE
fimfast.com

### ISSUE THREAD

**Issue by taisang1996** [abpvn/abpvn#29]
hiện tại chặn đươc trên pc, trên thiết bị di động thì không được bạn ah, 
giải pháp của mình , hy vọng có ích cho mọi người
`fimfast.com##[class*='banner']`

**Comment by hoang-rio** [comment]
Cảm ơn bạn. Những quy tắc như này thì mình hạn chế dùng mình đã cập nhật chặn mobile cho trang này ở 8e44d258 rồi bạn nhé!
