### ISSUE TITLE
Possible tracker on website: [genk.vn]?

### ISSUE THREAD

**Issue by stephenhawk8054** [abpvn/abpvn#295]
**Ads description**
There's a suspicious script link that might be a tracker?
`https://deqik.com/tag/corejs/ATMJGB0YKY21R.js`

**Step to reproduce**
1. Go to website: `https://gamek.vn/`

**Website url**
[https://gamek.vn/](https://gamek.vn/)

**Screenshot**

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Firefox|94.0.1|ublock origin|1.38.6|ublock default + ABPVN|

Proposed filter:

`||deqik.com^`

**Comment by hoang-rio** [comment]
ABPVN only support advertisement. For tracking please create issue on EasyPrivacy
