### ISSUE TITLE
Exist ads on website: [http://truyenqqtop.com/]

### ISSUE THREAD

**Issue by bigdargon** [abpvn/abpvn#299]
**Ads description**
https://github.com/bigdargon/hostsVN/issues/306

Quảng cáo ở trang đã bị chặn các banner, tuy nhiên vẫn còn một số phần tử vẫn còn chính giữa trang (ở trang chủ) và phía đầu trên/dưới cùng (ở các trang truyện)

**Step to reproduce**
1. Go to website http://truyenqqtop.com/

**Website url**
http://truyenqqtop.com/
http://truyenqqtop.com/truyen-tranh/to-tich-ky-quai-2-11630-chap-1.html

**Screenshot**
<Details>

![image](https://user-images.githubusercontent.com/10969626/142826525-b8a6412c-701a-494d-82bb-e5b303fe2da7.jpeg)
![image](https://user-images.githubusercontent.com/10969626/142826554-71bdaf9a-a306-4cf9-8537-fdf9d6890e79.jpeg)

</Details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Safari iOS|iOS 14.8|Adguard|4.2.2|EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Đã xong nhé thím @bigdargon bigdargon/hostVN#306
![Screenshot_20211122-195519.png](https://user-images.githubusercontent.com/11514638/142865609-1382aec6-3d71-48df-8a45-a4dc6db002a3.png)
