### ISSUE TITLE
tắt mở trang mới và hiển thị mã giảm giá

### ISSUE THREAD

**Issue by taisang1996** [abpvn/abpvn#30]
Bạn có thể thêm userscript này không ?
https://gist.github.com/taisang1996/25e74c258fdd56d835dbdaec86ea3a21

**Comment by hoang-rio** [comment]
Không. ABPVN script chỉ xử lý quảng cáo. Bạn có thể tạo script riêng và chia sẻ cho mọi người nếu muốn.
