### ISSUE TITLE
Exist 3rd-party ads/script domain on website: [truyenfull.vn]

### ISSUE THREAD

**Issue by stephenhawk8054** [abpvn/abpvn#305]
**Ads description**
Although the ads section is already hidden, the scripts and ads images resources are still loaded with the domain `iads.staticscdn.net`, which is also in blocked list of `hostsVN`. I think it's safe to block this domain as it's just used to deliver ads.

**Step to reproduce**
1. Go to website: `https://truyenfull.vn/`

**Website url**
[https://truyenfull.vn/](https://truyenfull.vn/)

**Screenshot**
<details>

![image](https://user-images.githubusercontent.com/66517106/143799601-58670d21-443d-4704-a90c-b018e3ea4062.png)

![image](https://user-images.githubusercontent.com/66517106/143799621-ba3351dd-1a64-4a11-b487-3146ea140079.png)

</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Firefox|94.0.2|ublock origin|1.39.0|ublock default + ABPVN|

Proposed filter:

`||iads.staticscdn.net^`

**Comment by hoang-rio** [comment]
@stephenhawk8054 I add this rule to ABPVN to block ads script. All image from this domain blocked by `.net/ads/` rule
![Screenshot 2021-11-29 at 10 04 22](https://user-images.githubusercontent.com/11514638/143802503-2d04f822-303a-4ebe-9f6d-7fe528371a31.png)
