### ISSUE TITLE
[NSFW][iOS Coc Coc] Pop-under ads in https://xnxx-sex-videos.com/

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#306]
Dear Team,

Recently, we see that the number of pop-under ads in https://xnxx-sex-videos.com/ has been significantly increasing.

It's found from our side (iOS) that there is a _blank target with userout()'s onclick that makes a popunder ads in html body. See below screenshot.
![image](https://user-images.githubusercontent.com/85873327/143805824-65137f57-5069-402b-a305-b7bffc1d0e7e.png)

Please help take a look and advise us how to handle this case. Please help forward to easylist repo if needed.

Note: While testing, it's quite hard to reproduce the case with pop-under ads. We only see the below case:
Step 1: Go to https://xnxx-sex-videos.com/
Step 2: Choose random a video to watch
Step 3: Direct to hdpornlife.com and open new tab
See more at 1:24 (Video recorder: https://drive.google.com/file/d/1xG-8v2aSx5yzy-S4fK25sicb-xJmSxNG/view)

Hope that this info is useful for your investigation.

Many thanks!
Hang Tran

**Comment by hoang-rio** [comment]
@hangtt1 This type of ads can not block with normal rule. So i created new pull request to **ABP Filters Anti CV** abp-filters/abp-filters-anti-cv#728

Please continue follow this PR
