### ISSUE TITLE
Excuse me?

### ISSUE THREAD

**Issue by tw-e** [abpvn/abpvn#31]
Hello,abpvn

Will there continue to block foreign advertising and servers?

**Comment by hoang-rio** [comment]
We are **ABPVN** We only support Vietnamese website and it is not supported by EasyList

**Comment by tw-e** [comment]
Sorry!
I did not say clearly, is Android and IOS the same?
https://abpvn.com/android/abpvn.txt

**Comment by hoang-rio** [comment]
> Sorry!
> I did not say clearly, is Android and IOS the same?
> https://abpvn.com/android/abpvn.txt

This host file is maintain in https://github.com/bigdargon/hostsVN
