### ISSUE TITLE
Exist ads on website: [xemphimxua.net]

### ISSUE THREAD

**Issue by stephenhawk8054** [abpvn/abpvn#315]
**Ads description**
Ads banners

**Step to reproduce**
1. Go to website: `https://xemphimxua.net/movies/nguoi-hong-kong-tren-dat-quang-chau/`

**Website url**
[https://xemphimxua.net/movies/nguoi-hong-kong-tren-dat-quang-chau/](https://xemphimxua.net/movies/nguoi-hong-kong-tren-dat-quang-chau/)

**Screenshot**
<details>

![image](https://user-images.githubusercontent.com/66517106/145678816-76cf0e73-0cd8-470a-ad15-1643c1ad7a51.png)

</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Firefox|95.0|ublock origin|1.39.2|default + ABPVN|

Proposed filter:

`.gif$image,third-party,domain=xemphimxua.net`

**Comment by stephenhawk8054** [comment]
I think there's still a gif banner at the right with this link, should it be blocked?

`https://suckhoelamdep.vn/wp-content/uploads/2021/11/banner-sacngockhang.gif`

**Comment by hoang-rio** [comment]
Done via d698cb36]
