### ISSUE TITLE
Exist ads on website: [daominhha.com]

### ISSUE THREAD

**Issue by stephenhawk8054** [abpvn/abpvn#331]
**Ads description**
Ads banner

**Step to reproduce**
1. Go to website: `https://daominhha.com/grand-theft-auto-san-andreas-viet-hoa/`

**Website url**
[https://daominhha.com/grand-theft-auto-san-andreas-viet-hoa/](https://daominhha.com/grand-theft-auto-san-andreas-viet-hoa/)

**Screenshot**
<details>

![image](https://user-images.githubusercontent.com/66517106/146485278-53311906-bbca-4579-97f7-0a0f5a2afdd4.png)

</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Firefox|95.0.1|ublock origin|1.39.2|EasyList + ABPVN List|

Proposed filter:

`||gameiwin.net/wp-content/uploads/*$image,domain=daominhha.com`

**Comment by hoang-rio** [comment]
@stephenhawk8054 why you don't follow [CONTRIBUTING.md](https://github.com/abpvn/abpvn/blob/master/CONTRIBUTING.md) and create Pull Request instead of Issue?
