### ISSUE TITLE
[Coc Coc]  Cannot remove blank space completely on 24h.com.vn

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#342]
Step:
1. Install app
2. Access 24h.com.vn site
3. Obsever

Actual: Still show blank space
![image](https://user-images.githubusercontent.com/85873327/147052265-aa51a8c2-e85b-4a10-8c83-0e27b93e51dc.png)

Expect: Doesn't show blank space

Environment
Version: Coc Coc BT 102.1.21120721
Device: Ipad 9.7/OS 14.3
--------------------
Note: We had tried to fix this issue in Coc Coc Side, however, there is still other “blank space” on the right after that (See below image)
<img width="1536" alt="Screen Shot 2021-12-09 at 09 56 09" src="https://user-images.githubusercontent.com/85873327/147052439-fda1161d-171e-4409-bf75-ff0986c95e11.png">

Please help consider this issue.

**Comment by hoang-rio** [comment]
@hangtt1 This space can not removed by any adblocker because of HTML structure of this site use table layout so noway to hide these blank space.
