### ISSUE TITLE
Exist ads on website: [tvphapluat.vn]

### ISSUE THREAD

**Issue by stephenhawk8054** [abpvn/abpvn#345]
**Ads description**
Ads banners, especially when scrolling down. Also the site tries to connect to `/banner/*.gif` hundreds to thousands times when it's blocked whenever scrolling up and down.

**Step to reproduce**
1. Go to website: `https://tvphapluat.vn/video/ban-can-su-dang-bo-gd-dt-nhiem-ky-2016-2021-co-mot-so-vi-pham-khuyet-diem-57938/`
2. Scroll up and down and wait for loading.

**Website url**
https://tvphapluat.vn/video/ban-can-su-dang-bo-gd-dt-nhiem-ky-2016-2021-co-mot-so-vi-pham-khuyet-diem-57938/

**Screenshot**
<details>

![1](https://user-images.githubusercontent.com/66517106/147375982-85241cc2-6ca3-4742-91fc-71126441081f.png)

</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Firefox|95.0.2|ublock origin|1.40.0|EasyList + ABPVN List|

I created issue instead of PR since there are 2 approaches we can use so it's up to you to choose:

1. Allow banner gif and just hides the elements:

```
@@/banner/*.gif$image,domain=tvphapluat.vn
tvphapluat.vn##.bannerqc
tvphapluat.vn##[class^="sticky-top"]
tvphapluat.vn##[href*="/default/template/"]
tvphapluat.vn##[href*="hungthinhcorp.com.vn"]
tvphapluat.vn##[href*="pbgdpl.longan.gov.vn"]
tvphapluat.vn##[href*="vietcombank.com.vn"]
```

2. Block all banners connections and abort the inline script of trying to reconnect when scrolling

```
||tvphapluat.vn/upload/banner/*$image
tvphapluat.vn##[class^="sticky-top"]
tvphapluat.vn##[href*="pbgdpl.longan.gov.vn"]
tvphapluat.vn##+js(acis, $, scroll)
```
(And similar filters for ABP or Adguard)

**Comment by hoang-rio** [comment]
First solution is accepted. Thanks @stephenhawk8054
