### ISSUE TITLE
Đề nghị chặn quảng cáo trên phimmoi.net

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#35]
Đây là domain load quảng cáo trên trang phimmoi.net, nếu có thể - đề nghị bạn cho bổ sung vào bộ lọc domain này. Cảm ơn bạn.
Domain:
`verycheap.cheap-ads.net`

**Comment by hoang-rio** [comment]
Fixed with commit 023227e3b66e67be606b2b7dbe9585847fd6670d
