### ISSUE TITLE
pops.vn anti-adblock

### ISSUE THREAD

**Issue by minhngoc25a** [abpvn/abpvn#352]
POPS has improved the anti-adblock technology on their site. Here's the anti-adblock wall that shows when the filter is on:

![image](https://user-images.githubusercontent.com/33834488/150541211-ec2076c1-d406-4a49-90bc-4ee4f31b050a.png)

And this is the sample link for you to test: 
https://pops.vn/video/one-piece-s20-tap-891-dai-mao-hiem-o-hai-vuc-wano-61e53f85a7484e005f41cf4e

I'm using uBlock Origin, the VN regional filter was updated to the latest version. If anyone can fix this, thank you very much!

**Comment by hoang-rio** [comment]
ABPVN currently support when it enable with only EasyList. I've just checked with EasyList and ABPVN List enabled and it working fine it mean problem from another filter you enabled so I can not support.
