### ISSUE TITLE
Chặn ảnh QC từ media.giphy.com trên các trang banthang.tv|vaoroi.tv|ibongda.live|tructiepbongda.vip|dabong.net|bongda365.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#36]
`||media.giphy.com^*.gif$domain=banthang.tv|vaoroi.tv|ibongda.live|tructiepbongda.vip|dabong.net|bongda365.tv
`

**Comment by hoang-rio** [comment]
Add in commit 9daf33f7f31a65f8d59e4afd5d4131309647d417
