### ISSUE TITLE
Trang baominh.tech phát hiện adblock

### ISSUE THREAD

**Issue by docaohung** [abpvn/abpvn#361]
Mình dùng adguard windows.
Mình vào trang baominh.tech thì nó phát hiện adblock.
Mình đưa link thôi nha. https://baominh.tech/
Hình ảnh mình report bên facebook rồi. Đỡ mất công tìm host share ảnh :(

**Comment by hoang-rio** [comment]
Done via 38794d5e463557e25161d44407a25a76cef2b060 and aea029193ade8ff45daa69d8c711c3ceb57f8ef5
