### ISSUE TITLE
Chặn QC cá độ

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#37]
* **banthang.tv**: có các link quảng cáo của 11bet.win, 8live.fun, letouvn.com, debet.com, cacuoc247.com, datcuoc247.com, five88.net, one88.vn, jbo039.com, sbbanner.com, mayclub.net, qc.vic.win, qc.x8.club, zbet.vn, ad.yo88.win, qc.nhatvip.net, fa88.win, 11bet.win;
* **live.90p.tv** có link quảng cáo của zbet.vn, 11bet.win, lucky88.win, 8live.fun, bong99.fun, one88.vn, fabet.vip, debet.com,
* **tructiepbongda.vip** có link quảng cáo của jbo039.com, 9club.asia, nagavip.club, debet.com, zbet.vn, zo.game, uwin71.com, one88.vn, qq8788viet.com, cacuoc247.com, ad.yo88.win, tai.go88.vin, qc.nhatvip.net, qc.x8.club, qc.vic.win, mayclub.net, cacuoc24.net, datcuoc247.com, 
* **dabong.net, bongda365.tv** có các link quảng cáo của zbet.vn, cacuoc247.com, datcuoc247.com, debet.com, jbo002.com, sbbanner.com,
* **ibongda.live** có link quảng cáo của sbbanner.com, gamefb88.com, zbet.vn, 
* **binhluan.tv** có link quảng cáo của fb88sports.com, lucky88.win, mibet.win, 388bet.top, thethaofb88.com, zbet.vn, five88.net, fabet.vip, oneday88.com, mybookie.ag
* **phim.vkool.tv** có link quảng cáo của 8live.fun, fa88.win, uwin71.com, qq8878.org, qq8788viet.com, twin188.co
* **bilutv.org** có link quảng cáo của twin188.co, vuaking.net, jbo039.com
** Riêng **ads.sporttv.today** đóng vai trò là host chứa code quảng cáo xuất hiện trên nhiều trang khác nhau như: thevangtv.com, thevang.tv, ngoac.net, ibongda.live,...

**Comment by hoang-rio** [comment]
Dù là quảng cáo cá độ thì bạn cũng phải đưa ra được bằng chứng phù hợp thì ABPVN mới có thể đưa vào bộ lọc nhé

**Comment by vhpcdpgl** [comment]
Mình sẽ bổ sung sau bạn nhé

**Comment by hoang-rio** [comment]
Ok bạn. Bạn bổ sung lý do nếu hợp lý thì mình sẽ thêm vào bộ lọc.

**Comment by vhpcdpgl** [comment]
Mình có diễn giải cụ thể hơn rồi, khi nào rảnh bạn coi giúp nhé.
Thanks!

**Comment by hoang-rio** [comment]
Như thế này quá khó vì không xác định được cái nào có rồi cái nào chưa có

**Comment by hoang-rio** [comment]
> Mình có diễn giải cụ thể hơn rồi, khi nào rảnh bạn coi giúp nhé.
> Thanks!

Mình đã lướt 1 lượt các trang web trên và chặn quảng cáo mình thấy bằng comit eb167c281baaeb47a57f7a093a484e8179560dbd còn tất cả domain kia thì mình không thể chặn cứng được

**Comment by hoang-rio** [comment]
@vhpcdpgl Bạn biết dùng github thì bạn fork project rồi tạo pull request sẽ tiện hơi nhiều việc tạo issue như thế này bạn nhé
