### ISSUE TITLE
Chặn quảng cáo Video trên các trang xem phim như: phimdi.com

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#38]
Rule: `/cvast.$script,xmlhttprequest`
URL: `https://phimdi.com/cvast.xml?pub=phimdi.com&origin=https://phimdi.com/movie/tap-8-troi-dep-em-se-den-ill-go-to-you-when-the-weather-is-nice-2020_b2qP3QSA.html&custom%5B%5D=+%2Fvast_assets%2Fvast.xml%3Fv%3D2%26ref%3Dphimdi.com`
P/S:
- Mình không rành github hoặc lập trình nên chắc không làm kiểu pull request được
- Rule ở trên là do mình tạo thủ công bằng addon của Adguard Adblocker cho web browser, sau đó copy sang đây.
- Ngoài phimdi.com, một số trang cũng xài cvast.xml như https://an.acxapi.net/cvast.xml?pub=phimonl.net
- Trong rule có sẵn của ABPVN có `/vast.$script,xmlhttprequest,domain=~ynet.co.il|~xemvtv.net`
và `/vast\d+\./$xmlhttprequest` , bạn có thể biên tập thêm cái cvast.xml nữa không?
Kiến thức mày mò rất có hạn, nếu có gì không đúng mong bạn bỏ qua cho ;)

**Comment by hoang-rio** [comment]
Đã thêm ở 7b58d9eb2d9725d0b20fc30ce38ec87145ccc0ec
