### ISSUE TITLE
[NSFW][Coc Coc] Exist ads on website: [javmost.xyz ] Pop-under ads

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#380]
**Ads description**
Tell about ads you see in website here.

**Step to reproduce**
1. Go to website javmost.xyz
2. Choose a video to watch 
iOS: [https://www.javmost.xyz/SIRO-4830/]()
Android: [https://www.javmost.xyz/PPV-2760777/]()

Actual: See a lot of pop-under ads 

Video Recorder: 
iOS: [https://drive.google.com/file/d/16NI8D-kILiME901j7arbTnvy9pmyGn4R/view?usp=sharing]() **(1:12)**
Android: https://drive.google.com/file/d/1_QKbzu6S_EZ9khJpGrzffR2ePate4kIE/view **(0:13)**

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
Coc Coc (Latest version in Store)

**Comment by hoang-rio** [comment]
It's non Vietnamese website so I reported it to EasyList author.
