### ISSUE TITLE
[softonic]

### ISSUE THREAD

**Issue by zeref-dragneel** [abpvn/abpvn#394]
Cái này có được gọi là quảng cáo không bạn
`softonic.vn##.modal-di__button-wrapper`

![ảnh](https://user-images.githubusercontent.com/95934994/165464953-6d5ea6d5-b038-4a3f-909b-9eb9e5e27dee.png)

**Comment by hoang-rio** [comment]
Cái này được coi là quảng cáo nhé bạn. Đúng ra thì việc hiển thị cái popup này đã là quảng cáo rồi

**Comment by zeref-dragneel** [comment]
> 

Bạn chặn cái popup này cho nó nhảy qua trang download luôn được không nhỉ? Một là bấm nút X, 2 là chọn Cảm ơn, vẫn tiếp tục... thì mới qua trang download được. Còn cái nút xanh lá là quảng cáo chèn vào ấy
