### ISSUE TITLE
lỗi scrip làm đơ fb khi xem video

### ISSUE THREAD

**Issue by jamboml** [abpvn/abpvn#4]
dùng cái scrip này khi xem video trên facebook sẽ bị đơ cả tab fb , tắt đi xem bt

**Comment by abpvn** [comment]
Bạn có thể mô tả rõ hơn về lỗi bạn gặp phải không? Cụ thể là bạn gặp phải lỗi khi sử dụng bộ lọc quảng cáo với tiện ích mở rộng nào và trình duyệt nào.

Vào 11-05-2017 19:10, jamboml <notifications@github.com> đã viết:

dùng cái scrip này khi xem video trên facebook sẽ bị đơ cả tab fb , tắt đi xem bt

**Comment by jamboml** [comment]
bị lỗi trên cốc cốc ad nhé, [image: Inline image 1]

2017-05-11 19:18 GMT+07:00 ABPVN <notifications@github.com>:

**Comment by abpvn** [comment]
Bạn có thể mô tả đẩy đủ các thông số như mình yêu cầu được không? Như vậy sẽ dễ hơn cho việc sửa lỗi

**Comment by jamboml** [comment]
lỗi là do cái script này
https://greasyfork.org/vi/scripts/9099-abpvn-adsblock/
cài nó rồi thì khi xem 1 clip trên facebook sẽ bị đơ ngay

**Comment by abpvn** [comment]
Hiện mình đang thử sủ dụng và không gặp vấn đề gì bạn nhé. Mình có khuyến cáo script chỉ sử dụng với *Violent Monkey* chứ không sử dụng được với *Tampermonkey* bạn nhé!

[Screenshot (5).png](https://s7.postimg.org/fmlgu4yu3/Screenshot_5.png)

**Comment by jamboml** [comment]
thank ad, chắc vậy rồi, mà ad k dùng tampermonkey ah, vậy cái scrip này nó
có tác dụng gì đặc biệt k ạ, k dùng nó thì có lo quảng cáo k ạ

2017-05-11 20:01 GMT+07:00 ABPVN <notifications@github.com>:

**Comment by abpvn** [comment]
Mình đã cập nhật lại readme rồi nhé! https://github.com/abpvn/abpvn/tree/master/script
Script giúp chặn một số quảng cáo popup không chặn được bằng bộ lọc. Ngoài ra còn bổ xung thêm một vài chức năng như bỏ qua thời gian chờ đợi ở một số trang download.
VD: fshare.vn mediafire.com
