### ISSUE TITLE
Exist ads on website: [https://dood.pm/d/ez4q34fief1w#download_now]

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#408]
**Ads description**
See pop-under ads

**Step to reproduce**
1. Go to website: https://dood.pm/d/ez4q34fief1w#download_now
2. Tap to play the video
3. Direct to pop-under ads (https://hugregregy.pro/b/3JVK0JP.3mpxvbbZmxVmJaZGDA0n0hMmTqQM2ZOrTDMS4BLPT_QUxINlDzYc5MM/zTkg&s=414,896,1.078125,446.34375,966,1&v=&m=)

**Website url**
Direct website url contains ads: https://hugregregy.pro/b/3JVK0JP.3mpxvbbZmxVmJaZGDA0n0hMmTqQM2ZOrTDMS4BLPT_QUxINlDzYc5MM/zTkg&s=414,896,1.078125,446.34375,966,1&v=&m=

**Screenshot**

https://user-images.githubusercontent.com/85873327/172121772-47add385-ce18-4604-9e1f-7c78922e2d58.mp4

Note: Our Developer tried to fix this issue, however, he had been blocked from this site
<img width="358" alt="Screen Shot 2022-05-31 at 14 19 47" src="https://user-images.githubusercontent.com/85873327/172122109-d8d03595-c047-484c-85c2-b2d5b26edd74.png">

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Ex: Firefox, Chrome|Ex: 91|Ex: Adblock Plus|Ex: 3.10|Ex: EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Reported to EasyList filter. Please continue follow at easylist/easylist#12226

**Comment by hoang-rio** [comment]
@hangtt1 For next issue please add prefix [NSFW] when report adult website. Another notice: Please follow issue template to wrap screenshot inside **details** tag
