### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by zeref-dragneel** [abpvn/abpvn#414]
Không phải quảng cáo đâu nhưng mình bị OCD mà dùng FF Mobile thì gặp lỗi trên trang này bạn giúp mình ẩn nó đi được không nhỉ?
![20220622202357](https://user-images.githubusercontent.com/95934994/175041011-532e85e5-af2d-4822-a59c-3528d97a04fe.png)

**Comment by hoang-rio** [comment]
@zeref-dragneel Nhình cái này thì mình cũng không biết bạn đang muốn ẩn cái gì đâu bạn. Mà bạn vẫn có thể tự ẩn bằng uBlock Origin được mà

**Comment by zeref-dragneel** [comment]
Ẩn cái nút tam giác to mờ mờ phía sau ấy bạn
