### ISSUE TITLE
Pull

### ISSUE THREAD

**Issue by zeref-dragneel** [abpvn/abpvn#420]
Làm sao để fetch upstream được nhỉ. Nó cứ bắt tạo pull chứ không fetch được. Mỗi lần chỉnh sửa là cứ phải xoá đi fork lại hoài. Có cách nào để update mà không cần phải fork lại không bạn?

**Comment by hoang-rio** [comment]
Nếu bạn dùng git command thì có thể add remote là  abpvn rồi fetch --all là được bạn nhé. Sau đấy thì bạn có thể reset hoặc checkout từ abpvn/master

**Comment by hoang-rio** [comment]
Mỗi lần tạo pull bạn nên tạo một nhánh mới k sử dụng nhánh master trên repo fork nữa là được nhé
