### ISSUE TITLE
Block incorrect on website: `https://vast.gov.vn/`

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#426]
**Incorrect block description**
**Rule hiện tại:**

`/vast.$script,domain=~japopav.tv|~nhaccuatui.com|~radiomitre.cienradios.com|~supjav.com|~ynet.co.il`

**Rule đề xuất:**

`/vast.$script,domain=~vast.gov.vn|japopav.tv|~nhaccuatui.com|~radiomitre.cienradios.com|~supjav.com|~ynet.co.il`

**Screenshot**

<details>

![ảnh](https://user-images.githubusercontent.com/59459998/177899851-750bb9be-fff6-4e74-81a8-d41a1e18745e.png)

</details>

**Comment by vhpcdpgl** [comment]
@hoang-rio [vast.js block](https://github.com/abpvn/abpvn/commit/8610e90f08010987de9e4eeb91731833e261e5b7#r78931192)

**Comment by hoang-rio** [comment]
@vhpcdpgl Done in 5dcbbba25d555f612bfc51bdb655ecfb4cc4bea3
