### ISSUE TITLE
Exist ads on website: [skyphimz.net]

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#428]
**Ads description**
Hiện nay đối với trang `ssphim.net` thì ABPVN đã có rule fix nút logo trên player QC trá hình cá độ, cụ thể rule là `play.vnupload.net##.jw-logo`
Tuy nhiên trang `skyphimz.net` cũng xuất hiện nút logo giống hệt, hiện tại mình tự fix bằng rule `##div[class^="jw-logo"]`
=> Đề xuất ad xem xét, gộp chung rule cho 2 trang trên (rất có thể còn nhiều trang khác nữa cũng QC cá độ kiểu này)
Thân mến!

**Comment by vhpcdpgl** [comment]
![ảnh](https://user-images.githubusercontent.com/59459998/177977935-210a77de-a0b0-493b-a72c-e42b85fdcfdd.png)

**Comment by vhpcdpgl** [comment]
![ảnh](https://user-images.githubusercontent.com/59459998/177978136-9c9497e5-fc97-45ee-badb-334e3c866eb0.png)

**Comment by vhpcdpgl** [comment]
Mình tìm thấy trên link `https://browser.coccoc.com/js/android_abp_custom_rules_premium.txt` một số rule tương tự để fix mấy cái logo 'cà chớn' này.

**Comment by zeref-dragneel** [comment]
Tuyệt quá bạn 🌺

**Comment by hoang-rio** [comment]
Cái jw-logo này là tính năng của jwplayer nếu chặn trên tất cả các trang thì vẫn có nguy cơ chặn nhầm nên mình sẽ chỉ chặn trên trang phát sinh quảng cáo trên logo player thôi
