### ISSUE TITLE
Exist ads on website: cakhia.org

### ISSUE THREAD

**Issue by nguyenthanhnam000** [abpvn/abpvn#429]
**Ads description**

**Step to reproduce**
1. Go to website
2. ...
3. ...

**Website url**
cakhia.org
cakhia-tv.onl

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

![Image name](imageUrl)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|103|AdGuard AdBlocker|4.0.181|Ex: EasyList + ABPVN List, EasyPrivacy|

**Comment by nguyenthanhnam000** [comment]
Quảng cáo trên trang này nữa
https://cakhia-tv.onl/

**Comment by hoang-rio** [comment]
Bạn sửa lại issue đầy đủ thông tin theo format nhé

**Comment by nguyenthanhnam000** [comment]
Em sửa lại như kia đúng chưa thím?
