### ISSUE TITLE
Exist ads on website: [o-study.net]

### ISSUE THREAD

**Issue by nguyenthanhnam000** [abpvn/abpvn#431]
**Ads description**

**Step to reproduce**
1. Go to website
2. ...
3. ...

**Website url**
o-study.net

**Screenshot**

![ảnh](https://user-images.githubusercontent.com/108942634/178415856-3a651a80-b3fe-48df-80bb-fb494039a6b5.png)

<details>
<summary>With ABPVN Enabled</summary>

![Image name](imageUrl)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome |103|Adguard|4.0.181|Ex: EasyList + ABPVN List, EasyPrivacy|

**Comment by nguyenthanhnam000** [comment]
![ảnh](https://user-images.githubusercontent.com/108942634/178492609-1bcb5310-f08f-44a5-8774-874428404f6a.png)

**Comment by vhpcdpgl** [comment]
Mình cũng ko vô được trang này luôn. Chắc cũng dở như ai kia rồi ]]

**Comment by nguyenthanhnam000** [comment]
Mình tra google nó còn top một đây sao bảo không vào được. Có video quay lúc không vào được không (Thử Edge, Brave xem nào)

![ảnh](https://user-images.githubusercontent.com/108942634/178531618-57cf563c-edcd-43e7-a5b8-2fe0027309e3.png)

**Comment by hoang-rio** [comment]
> Bên này vẫn vào bình thường mà nhỉ? Thử đổi trình duyệt khác xem chứ quản lí bộ lọc mà lại bảo không truy cập được web thế là dở rồi
> ![ảnh](https://user-images.githubusercontent.com/108942634/178491241-15ce81cb-3895-4f9d-a6c1-915935dc04f5.png)
> 

Quản lý bộ lọc có liên quan đến việc không truy cập được web sao bạn? Nếu trang web bạn report bị nhà mạng mình đang sử dụng nó chặn thì mình không truy cập được là bình thường. Nhà mạng dạo này hay chặn những trang có nội dung không có bản quyền

**Comment by hoang-rio** [comment]
> Mình tra google nó còn top một đây sao bảo không vào được. Có video quay lúc không vào được không (Thử Edge, Brave xem nào)
> 
> Nếu không muốn đổi trình duyệt thì dùng google dịch cho lẹ nè https://translate.google.com/?hl=vi&sl=auto&tl=vi&op=websites
> 
> ![ảnh](https://user-images.githubusercontent.com/108942634/178531618-57cf563c-edcd-43e7-a5b8-2fe0027309e3.png)

Mình sẽ thử với VPN. Mà bạn tìm với từ khoá của nó thì nó top 1 là bình thường và không có gì chắc chắn cho việc xuất hiện trên google thì trang web sẽ vào được đâu

**Comment by nguyenthanhnam000** [comment]
Mình bảo là quản lí bộ lọc phải thử các cách khác nhau để xem truy cập được không, nếu đã thử hết các cách mà không truy cập được thì mới bảo là không truy cập được chứ chưa gì mới gõ tên web mà bảo không truy cập được vậy cho hỏi nếu vậy thì bạn từ chối không thèm chặn quảng cáo luôn ạ?

**Comment by hoang-rio** [comment]
Nếu vì không truy cập được mà mình không chặn thì mình đã close issue ngay từ thời điểm đó rồi. Mình comment như vậy cũng là 1 ghi chú để kiểm tra lại sau do thời điểm do mình chỉ dùng điện thoại và để bạn cùng kiếm tra lại thôi. Nhưng bạn phê bình mình ghê quá!

**Comment by nguyenthanhnam000** [comment]
Ghi chú à, vậy thì xin lỗi nha mình không biết đó là ghi chú. Mình cứ nghĩ đó là phản hồi. Nếu ghi chú thì thêm chữ Note chẳng hạn cho mình biết chứ mình tưởng đó là phản hồi lại nên thôi cho mình xin xin lỗi nha 
Ví dụ: "Note: Website is not accessible"
