### ISSUE TITLE
Exist ads on website: [teenvietnam.net]

### ISSUE THREAD

**Issue by nguyenthanhnam000** [abpvn/abpvn#433]
**Ads description**

**Step to reproduce**
1. Go to website
2. ...
3. ...

**Website url**
teenvietnam.net

**Screenshot**

![ảnh](https://user-images.githubusercontent.com/108942634/178960288-ee1ccd8d-21d9-4454-80c1-845181cd33c0.png)

<details>
<summary>With ABPVN Enabled</summary>

![Image name](imageUrl)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Ex: Chrome|Ex: 91|Adguard|Ex: 3.10|Ex: EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Cái issue form là tính năng mới của github hôm nay mình mới biết. Có thời gian mình sẽ cập nhật lên
