### ISSUE TITLE
Exist ads on website: [linkneverdie]

### ISSUE THREAD

**Issue by nguyenthanhnam000** [abpvn/abpvn#434]
**Ads description**

**Step to reproduce**
1. Go to website
2. ...
3. ...

**Website url**
linkneverdie.net

**Screenshot**

![ảnh](https://user-images.githubusercontent.com/108942634/179162022-89deca47-28fc-41c8-b1eb-0c4d7fe17376.png)

<details>
<summary>With ABPVN Enabled</summary>

![Image name](imageUrl)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Ex: Firefox, Chrome|Ex: 91|Ex: Adblock Plus|Ex: 3.10|Ex: EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Bạn report sai loại issue rồi. Bạn tạo lại cái khác nhé

**Comment by nguyenthanhnam000** [comment]
Bạn sửa đổi issue qua tiếng việt cho dễ nhận biết được không nhỉ? Mình không biết tiếng Anh nên mình chọn đại :v
