### ISSUE TITLE
Exist ads on website: [phimmoichills.net]

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#437]
**Ads description**

**Step to reproduce**
Banners quảng cáo cá độ
**Website url**

`https://phimmoichills.net/tag/jason+statham`
`https://phimmoichills.net/xem/wrath-of-man-tap-full-pm93910`
**Screenshot**
<details>
<summary>Trước khi chặn banners</summary>

![1_before](https://user-images.githubusercontent.com/59459998/181188044-c8751ec2-5ad1-4e22-9805-bbe13881c873.png)

</details>
<details>
<summary>Sau khi chặn banners</summary>

![2_after](https://user-images.githubusercontent.com/59459998/181188236-de8a92dd-130e-4176-8644-0f200a13c4a3.png)

</details>

**Rules đề xuất**
```
phimmoichills.net###chilladv
phimmoichills.net###catfishs_content
phimmoichills.net###pmadv
```

**Comment by hoang-rio** [comment]
Đây là trang redirect từ tên miền cũ phimmoichill.net
Mình đã xử lý ở https://github.com/abpvn/abpvn/commit/434fa4744ea474db715e8397685bfad432963418
