### ISSUE TITLE
Chặn quảng cáo từ host bit.ly trên các trang xem phim

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#44]
```
||bit.ly^$domain=biphim.tv|kingphim.net|vphim.net|phimmedia.tv|vkool.tv|
||bit.ly^$popup,domain=hatde.tv
```

**Comment by hoang-rio** [comment]
Bạn giải thích thêm về quy tắc chặn này nhé. Cụ thể là chặn cái gì và ở đâu

**Comment by vhpcdpgl** [comment]
> Bạn giải thích thêm về quy tắc chặn này nhé. Cụ thể là chặn cái gì và ở đâu

Dòng 1 là chặn banner trên các trang đó.
Dòng 2 là chặn cửa sổ popup.

**Comment by hoang-rio** [comment]
> Dòng 1 là chặn banner trên các trang đó.
> Dòng 2 là chặn cửa sổ popup.

Có hình ảnh hay url demo nào không bạn?

**Comment by vhpcdpgl** [comment]
> 
> 
> > Dòng 1 là chặn banner trên các trang đó.
> > Dòng 2 là chặn cửa sổ popup.
> 
> Có hình ảnh hay url demo nào không bạn?

https://i.postimg.cc/KYMvMpnt/phimmedia-tv-bit-ly.png
https://i.postimg.cc/sXPjnBHX/vphim-net-bit-ly.png

script trên hatde.tv:
```
<script>SmartPopunder.make('https://bit.ly/2TOGGsX', {cookieExpires: 60 * 2});</script>
<script>SmartPopunder.make('https://bit.ly/2vcZat6', {cookieExpires: 60 * 2});</script>
```

**Comment by hoang-rio** [comment]
Đã thêm ở commit 553e8ae93efef91f8562f47472f322a1f5fd541f

**Comment by vhpcdpgl** [comment]
Mình bổ sung thêm cái này nhé:

`||hatde.tv/assets/popup.js`

**Comment by hoang-rio** [comment]
> Mình bổ sung thêm cái này nhé:
> 
> `||hatde.tv/assets/popup.js`

Đã cập nhật rule chặn chung ở commit e88f5a31
