### ISSUE TITLE
Exist ads on website: [banhkhuc.net]

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#446]
**Proposed rules**

```
banhkhuc.net###m-bet
banhkhuc.net##.ibs-bet
banhkhuc.net##.mct_-bet
banhkhuc.net##[href^="mailto"]
banhkhuc.net##.btn-user.r-btn
```

**Comment by hoang-rio** [comment]
Mấy cái link mailto thì liên quan gì đến quảng cáo thím nhỉ? @vhpcdpgl

**Comment by vhpcdpgl** [comment]
> Mấy cái link mailto thì liên quan gì đến quảng cáo thím nhỉ? @vhpcdpgl 

Đại khái là nó bảo liên hệ QC thì mail vào đó. Mà trông vướng mắt quá nên mình thêm vào luôn 😀

**Comment by hoang-rio** [comment]
@vhpcdpgl Ngoài cái mailto mình bỏ qua thì còn lại đều đã thêm vào **ABPVN List** nhé
