### ISSUE TITLE
Exist ads on website: [tvhai.co]

### ISSUE THREAD

**Issue by khoald92vn** [abpvn/abpvn#447]
**Ads description**
Quảng cáo chạy 10 giây mới cho skip khi bấm load player xem phim.

**Website url**
https://tvhai.co/thuyet-minh/tham-tu-sherlock-phan-1-tap-1-server-1/

**Screenshot**
![image](https://user-images.githubusercontent.com/13995856/183587999-7e3467fb-ba8e-4718-a7d7-747d404e9a05.png)

Mong Ad sửa giùm ạ. Mình cảm ơn.

**Comment by hoang-rio** [comment]
Hiện tại mình kiểm tra với bộ lọc mới nhất thì mình không thấy có vấn đề như bạn mô tả bạn thử kiểm tra lại xem sao nhé!

**Comment by khoald92vn** [comment]
> Hiện tại mình kiểm tra với bộ lọc mới nhất thì mình không thấy có vấn đề như bạn mô tả bạn thử kiểm tra lại xem sao nhé!

Thank ad mình vừa mới update thì ok rồi ạ. Ngoài ra trên trang đấy còn 1 lỗi nữa là sau đấy phim bị lỗi không load được.
![image](https://user-images.githubusercontent.com/13995856/183611284-f6351e0b-220b-48e3-b336-e9117efa5538.png)

Hiện tại mình đã fix bằng cách thêm 

> ! 2022-08-08 https://player-cdn.com
> @@||apicdn30.xyz^$websocket,domain=player-cdn.com

vào my filter. Mong ad sửa lại ạ.

**Comment by hoang-rio** [comment]
Mình kiểm tra thì vẫn play bình thường dù websocket kia có bị chặn nên mình không có gì đề fix cả.
