### ISSUE TITLE
Chặn QC video trên các trang sử dụng JW Player

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#45]
Filter:
`||p.jwpcdn.com/player/plugins/vast/`
Ví dụ: Source script:
```
https://ssl.p.jwpcdn.com/player/plugins/vast/v/8.5.11/vast.js
https://ssl.p.jwpcdn.com/player/plugins/vast/v/8.7.13/vast.js
```

**Comment by hoang-rio** [comment]
Rule này đã chặn rồi bạn nhé https://github.com/abpvn/abpvn/blob/741184ac236812c4e9a37a739cb58937ed8c52db/filter/src/abpvn_general.txt#L31
