### ISSUE TITLE
Exist ads on website: [`phimmoi1.com` ; `mephimnhat1.com`]

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#450]
**Ads scripts**
```
https://mephimnhat1.com/mmo/pc.json
https://phimmoi1.com/mmo/pc.json
https://phimmoi1.com/mmo/shopee08.xml
https://sponsor.imacdn.com/vg/shopee08.mp4
```
**Proposed rules**
```
||sponsor.imacdn.com/*$media,domain=phimmoi1.com
||phimmoi1.com/mmo/*
||mephimnhat1.com/mmo/*
```

**Comment by hoang-rio** [comment]
Proposed rules may make video can not play. Did you check it?

**Comment by hoang-rio** [comment]
I just update these website use ublock/adguard rule in commit https://github.com/abpvn/abpvn/commit/68a5259fd9f938e5b6fc60004d9dc456436ac290 it require user click play icon

**Comment by vhpcdpgl** [comment]
> Proposed rules may make video can not play. Did you check it?

Yes, I did.

**Comment by hoang-rio** [comment]
> > Proposed rules may make video can not play. Did you check it?
> 
> Yes, I did. It load a "vast video" (sponsored video) before start the main movie.

I do a re check and your rule is accepted. Previous I check with error video (it's always can not play)
