### ISSUE TITLE
Exist ads on website: `lxhentai.com`

### ISSUE THREAD

**Issue by DiAnTTA** [abpvn/abpvn#453]
**Ads description**
Nhảy quảng cáo.

### Steps to reproduce:
1. Go to https://lxhentai.com/truyen/nu-sinh-se-jeong
2. Nhấn vào biểu tượng Trăng khuyết 🌜 để bật chế độ tối. 
3. Nhảy quảng cáo `https://tructiepbongda365.com/anh-hot/?utm_source=Lxhentai&utm_medium=Pop`

<details>
<summary>Screenshot with ABPVN enabled</summary>

![Android_KiwiBrowser](https://user-images.githubusercontent.com/74956696/185580800-105cc47b-a430-40a3-84c3-1a66e719cd91.jpg)
</details>

### Environment:
* **OS**: Android 11
* **Trình duyệt**: [Kiwi Browser](https://github.com/kiwibrowser/src.next/releases/tag/2886579806) 105.0.5195.24
* **Extentions**: uBlock Origin 1.43.0

<details>

```yaml
OS: Android 11
Kiwi Browser (Chromium) (arm64): 105.0.5195.24

uBlock Origin: 1.43.0
filterset (summary): 
  network: 83913
  cosmetic: 89704
  scriptlet: 19409
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 40177-100, now
  default: 
    user-filters: 0-0, never
    VIE-1: 1910-0, now
    adguard-mobile: 8154-11, now
    easylist: 69589-249, now
    easyprivacy: 27390-140, now
    plowe-0: 3635-865, now
    ublock-abuse: 76-0, now
    ublock-badware: 4242-92, now
    ublock-filters: 32632-157, now
    ublock-privacy: 231-3, now
    ublock-quick-fixes: 409-37, now
    ublock-unbreak: 1834-44, now
    urlhaus-1: 4611-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5195 ms
  maxAssetCacheWait: 680 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    lxhentai.com: 2
    adconnect.vn: 1
    googletagmanager.com: 1
```
</details>

**Comment by DiAnTTA** [comment]
*Rule tham khảo*:
```j
||ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js$script,domain=lxhentai.com
```

**Comment by hoang-rio** [comment]
ABPVN đã có rule `lxhentai.com##+js(abort-current-script, document.cookie)` để chặn popup trên trang này và mình kiểm tra cũng không phát sinh popup trên firefox. Có thể do trình duyệt của bạn không hỗ trợ thì mình không thể can thiệp được

**Comment by DiAnTTA** [comment]
> Có thể do trình duyệt của bạn không hỗ trợ 

→ Các trình duyệt Chromium chỉ không hỗ trợ rule `$popup` thôi.

Mình test trên **Firefox** thì cũng nhảy quảng cáo mà @hoang-rio 

https://user-images.githubusercontent.com/74956696/185733921-c84849cf-8189-4456-b9a9-69ffb13202f7.mp4

<details>

```yaml
Firefox Mobile: 103.2.0
uBlock Origin: 1.44.0
filterset (summary): 
  network: 83080
  cosmetic: 28215
  scriptlet: 17779
  html: 728
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33337-355, 2m
    ublock-badware: 4262-0, 2m
    ublock-privacy: 247-1, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1848-0, 2m
    ublock-quick-fixes: 417-0, 2m
    adguard-mobile: 8155-171, 2m
    easylist: 69600-25174, 2m
    easyprivacy: 27394-592, 2m
    urlhaus-1: 5419-0, 2m
    plowe-0: 3632-3, 2m
    VIE-1: 1912-32, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3474 ms
  maxAssetCacheWait: 405 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    lxhentai.com: 4
    adconnect.vn: 1
    googletagmanager.com: 1
```
</details>

**Comment by hoang-rio** [comment]
Chắc firefox của bạn khác firefox của mình rồi
https://user-images.githubusercontent.com/11514638/185742275-6c7b3edc-07d0-45ad-abcc-5b1fa0237df2.mp4

**Comment by DiAnTTA** [comment]
@hoang-rio Bạn phải truy cập vào URL `https://lxhentai.com/truyen/nu-sinh-se-jeong` này mới thấy vấn đề. Chứ test ở trang Home của `lxhentai.com` thì không thấy là phải 😂

https://user-images.githubusercontent.com/74956696/185742738-41fdd580-29c0-4361-95c2-b5d6746d964b.mp4

**Comment by hoang-rio** [comment]
Lỗi mình thật 😅 mình mở lại issue kiểm tra lại sau nhê
