### ISSUE TITLE
Exist ads on website: [motphimtv.info]

### ISSUE THREAD

**Issue by QuangNHe** [abpvn/abpvn#457]
**Ads description**
Video ads sometimes show

**Step to reproduce**
1. Go to website
2. Select any film
3. Play any film

**Website url**
https://motphimtv.info/xem-phim/phuc-luu-nien-tap-1-10578_125250.html

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

![Screenshot_2022-09-05-14-14-29-41_b01ec2a14c04824276048023717266ae](https://user-images.githubusercontent.com/16065318/188390554-d33fa556-2d4b-44fa-89ad-54e4ea3acaf5.jpg)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![Screenshot_2022-09-05-14-18-33-37_b01ec2a14c04824276048023717266ae](https://user-images.githubusercontent.com/16065318/188390952-f0733c5f-305f-43df-8989-f2e2efa3860d.jpg)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Cốc Cốc|103|Adblock Plus|3.14|EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Cái này do CocCoc mobile của bạn chứ ABPVN đã có rule `/v/*/vast.js$script` chặn được script `https://motphimtv.info/player/v/8.22.1/vast.js` load quảng cáo video trên website này rồi.
