### ISSUE TITLE
[Android] Can’t switch next episode on vuighe.net

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#459]
1.Steps

- Access [[Toradora Tập 1 - Rồng và hổ](https://vuighe.net/toradora/tap-1-rong-va-ho)](https://vuighe.net/toradora/tap-1-rong-va-ho)  and play video

- Click the button to switch next episode

2. Actual: Coc Coc can’t switch next episode (Video: https://drive.google.com/file/d/1hzEsqha3fAzcwLhuW_H2dTj2e3uwwK_4/view?usp=sharing)

3. Expected: Can switch next episode when playing video

---
**Environment**

Device: Samsung Galaxy J7 Prime, Android 8.1.0
Coc Coc version: 109.0.176
--
Our DEV checked and figured out that rule phimnhanh1.com,xemphim1080.com,phimmoi1.com,mephimnhat1.com,vuighe.net,mehoathinh.com#$#json-prune 'midroll midroll2 meta.ads'  in abp-filters-anti-cv make this issue.

Kindly help support.

**Comment by hoang-rio** [comment]
This issue has been release in to ABP Filters
