### ISSUE TITLE
Chặn QC trên PLO.VN

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#46]
Filter:
`/logcounter.`
Source script (ví dụ):
`https://plo.vn/utilities/logcounter.ashx?type=view&zoneId=58&contentId=571003&url=%2Fthe-thao%2Ftrong-nuoc%2Fafc-thang-tay-trung-tri-nan-dan-xep-ti-so-sau-dich-covid19-905399.html&rd=0.5332747301747993`

Filter:
`/ad-exchange.`
Source script (ví dụ):
`https://gamma.cachefly.net/js/ad-exchange.js`

Filter:
`/uploaded/ads/*`
Source script (ví dụ):
`https://static.plo.vn/Uploaded/Ads/LUONGTU/qed_PRDO.png`

**Comment by hoang-rio** [comment]
> Filter:
> /logcounter.

Đây không phải quảng cáo. Đây là logging mình từ chối thêm rule này

> Filter:
> /ad-exchange.

Filter này có ở **EasyList** rồi nên không thêm vào **ABPVN List** nữa
> /uploaded/ads/*

Filter này ok: Đã đưa vào **ABPVN List** ở commit abc4945186f1a0caac38182c8ae7b0694d089e3b
