### ISSUE TITLE
Exist ads on website: javhd.tech

### ISSUE THREAD

**Issue by QuangNHe** [abpvn/abpvn#463]
**Ads description**

**Step to reproduce**
1. Clean site setting
2. Go to website
3. Open any link
4. Play video
5. Open fullscreen and exit fullscreen

**Website url**
https://javhd.tech

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

![image](https://user-images.githubusercontent.com/16065318/192212512-6d4ad705-1eb7-48e7-981f-cdabe3522096.png)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Adblock Browser(Android)|101|Adblock Plus|3.2|EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Please add [NSFW] prefix for adult content. Incorrect issue format will be close without any fix
