### ISSUE TITLE
[NSFW] Exist popunder ads on website: [sex6688.link]

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#465]
**Ads description**
Have popunder ads on this site

**Step to reproduce**
1. Go to website sex6688.link
2. Click on any video item to play
3. Click on play button or other video item

**Environment**
|Chrome|105|Adblock Plus|3.14|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist, EasyList|

**Comment by hoang-rio** [comment]
Please add prefix [NSFW] with adult website. If not issue will be close without fix

**Comment by tonylinhtv** [comment]
@hoang-rio Why do you determine this is not an issue?

**Comment by hoang-rio** [comment]
Just close because of missing prefix NSFW

**Comment by tonylinhtv** [comment]
@hoang-rio I edited prefix already. Would you mind re-openning and helping us check this issue? Thanks!
