### ISSUE TITLE
[NSFW] Exist popunder  ads on website: [viet69.gg]

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#467]
**Ads description**
Have popunder ads on this site

**Step to reproduce**
1. Go to website viet69.gg
2. Click on any video item to play

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|105|Adblock Plus|3.14|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist, EasyList|

**Comment by hoang-rio** [comment]
Why you do not add NSFW prefix?
