### ISSUE TITLE
Exist ads on website: phimmoikf.com

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#468]
**Ads description**
Have video ads when playing video

**Step to reproduce**
1. Go to website phimmoikf.com
2. Click on any video item to play

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome | 105 | Adblock Plus | 3.14 | ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist, EasyList|

**Comment by tonylinhtv** [comment]
@hoang-rio THis issue still happens. Please help us check again. Thanks!
![Screenshot_9](https://user-images.githubusercontent.com/114989985/197156685-023478b6-7264-425e-a84d-850f4bae6172.png)

**Comment by hoang-rio** [comment]
> @hoang-rio THis issue still happens. Please help us check again. Thanks!
> ![Screenshot_9](https://user-images.githubusercontent.com/114989985/197156685-023478b6-7264-425e-a84d-850f4bae6172.png)
> 

Please give me full url. I can not reproduce this issue

**Comment by tonylinhtv** [comment]
@hoang-rio So, Can we remove video ads on this site?

**Comment by hoang-rio** [comment]
> @hoang-rio So, Can we remove video ads on this site?

Common jwplayer vast plugin already blocked by EL. Please check in you adblocker log

**Comment by tonylinhtv** [comment]
@hoang-rio  You can try this link https://phimmoikf.com/xem-phim/me-chong-kho-tinh-phan-1-tap-20-22673.html

**Comment by hoang-rio** [comment]
>  @hoang-rio  You can try this link https://phimmoikf.com/xem-phim/me-chong-kho-tinh-phan-1-tap-20-22673.html

I can reprodure with this url. I will check it. From next issue please note full url instead of any video item click. Not all video item can reproduce
