### ISSUE TITLE
Exist ads on website: vebotv.info

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#469]
**Ads description**
Have a black big popup ads in the center of screen

**Step to reproduce**
1. Go to website vebotv.info
2. Click on match item

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|105|Adblock Plus|3.14|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist, EasyList|

**Comment by hoang-rio** [comment]
Because of limitation of ABP so this issue only can be fixed in uBlock Origin or AdGuard
