### ISSUE TITLE
Chặn QC trên thesaigontimes.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#47]
Filter 1:
`/doitacqc/*`
Sources:
```
https://www.thesaigontimes.vn/doitacqc/adgoo300250.htm
https://www.thesaigontimes.vn/doitacqc/admicro300250_301.htm
https://www.thesaigontimes.vn/doitacqc/admicro300250_302.htm
https://www.thesaigontimes.vn/doitacqc/admicro300250_303.htm
```
Filter 2:
```
||cdn-ads.thesaigontimes.vn^
||ads.thesaigontimes.vn^
```
Ví dụ:
```
ads.thesaigontimes.vn/adsro250300.aspx
cdn-ads.thesaigontimes.vn/Uploads/AdsImage/qc_300250_2020.gif
```

**Comment by hoang-rio** [comment]
` ||ads.thesaigontimes.vn^`

Cái này bị chặn bởi rule đã có ở **EasyList** rồi nên mình không thêm

` /doitacqc/*`

Đã được chuyển thành `||thesaigontimes.vn/doitacqc/` vì đây không cần thiết phải dùng quy tắc chung có thể gây chậm

`||cdn-ads.thesaigontimes.vn^`

Cái này Ok dù mình không tìm thấy trên trang

Đã thêm ở commit cfbc0634

**Comment by vhpcdpgl** [comment]
```
https://www.upsieutoc.com/images/2020/04/22/Screenshot_20200422-114432_Chrome.jpg
https://www.upsieutoc.com/images/2020/04/22/Screenshot_20200422-114323_Chrome.jpg
```
View page source tại homepage hoặc tracking trên mobile thì thấy bạn ạ.
