### ISSUE TITLE
Exist ads on website: phimmoichills.net

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#471]
**Ads description**
Have video ads when playing video

**Step to reproduce**
1. Go to website phimmoichills.net
2. Click on any video item to play

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|105|Adblock Plus|3.14|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist, EasyList|

**Comment by hoang-rio** [comment]
This site has only ads on top of website and now it hidden. No video ads found

**Comment by tonylinhtv** [comment]
@hoang-rio Video ads still exists. Please help us check again. Thanks!
![Screenshot_10](https://user-images.githubusercontent.com/114989985/197157110-217a4a2e-be1e-4d46-a0c9-21113c2de181.png)

**Comment by hoang-rio** [comment]
> @hoang-rio Video ads still exists. Please help us check again. Thanks!
> ![Screenshot_10](https://user-images.githubusercontent.com/114989985/197157110-217a4a2e-be1e-4d46-a0c9-21113c2de181.png)
> 

I think you have issue with EasyList. Please check it up to date first. Thanks.

**Comment by hoang-rio** [comment]
May be you Coccoc standard whitelist currently whitelist jwplayer vast plugin. Please contact CocCoc filter list author to resolve this issue. I can help any more.

**Comment by tonylinhtv** [comment]
@hoang-rio I'm sorry. I've edit Subscription Filter. We don't use EasyList. Instead, we use ABPVN List+EasyList.
https://easylist-downloads.adblockplus.org/abpvn%2Beasylist.txt

**Comment by hoang-rio** [comment]
Give me full url which can reproduce this issue please. Please also give me coccoc standard whitelist url.

**Comment by tonylinhtv** [comment]
**issue url:** https://phimmoichills.net/xem/xac-song-phan-11-tap-1-pm90808
https://coccoc.com/adblock/coccoc_standard.txt

**Comment by hoang-rio** [comment]
vast video plugin in this site whitelisted in coccoc standard. Please contact coccoc for help
<img width="798" alt="Screen Shot 2022-10-22 at 15 53 39" src="https://user-images.githubusercontent.com/11514638/197330572-45db7175-c1f7-4d1c-940e-16c0c8d9e307.png">

**Comment by tonylinhtv** [comment]
@hoang-rio you mean I need to remove vast video plugin out of whitelist in coccoc standard. And then, you will add rule to fix on your side. Right?

**Comment by hoang-rio** [comment]
Video ads will be disappear when remove whitelist rule. You can try by disable coccoc standar filter list

**Comment by tonylinhtv** [comment]
@hoang-rio after removing this whitelist, it can not play video on this site https://phimchat1.com/xem-phim/khuynh-the-cam-lan-coc-vu-lai-8216. Please help us check. Thanks!

**Comment by hoang-rio** [comment]
> @hoang-rio after removing this whitelist, it can not play video on this site https://phimchat1.com/xem-phim/khuynh-the-cam-lan-coc-vu-lai-8216. Please help us check. Thanks!

I mean remove whitelist is remove domain from whitelist not remove rule. For another website please create new issue

**Comment by tonylinhtv** [comment]
@hoang-rio ok, thank you!
