### ISSUE TITLE
[NSFW] Pop-under ads on website: [sexvietnam.site]

### ISSUE THREAD

**Issue by dunglq1** [abpvn/abpvn#476]
**Incorrect block description**
Website has pop-under ads

**Step to reproduce**
1. Go to website
2. Click on any video thumbnails
3. It opens pop-under ads

**Website url**
https://sexvietnam.site/

<details>
<summary>With ABPVN Enabled</summary>
https://user-images.githubusercontent.com/117613505/200220609-66ee5230-62f3-431c-bf53-ad10e724da12.mp4
</details>

**Environment**
|Browser|Browser Version|Adblocker Version|
|---------|----------------|-----------------|
|Coc Coc (iOS)|112.0.476|0.11.1|

**Comment by hoang-rio** [comment]
Please add prefix NSFW. If not i will skip this issue

**Comment by hoang-rio** [comment]
Resolved in ABP Filters Anti CV
