### ISSUE TITLE
Chặn QC trên tinmoi.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#48]
`||tinmoi.vn/?mod=ajax&act=getAds`
`||tinmoi.vn/ga.js`

**Comment by hoang-rio** [comment]
2 quy tắc này chặn gì và nó sinh quảng cáo ở đâu bạn?

**Comment by vhpcdpgl** [comment]
Mấy cái này mình tracking trên mobile bạn ạ.
Cái đầu là hiển thị qc trên mobile, cái thứ hai là nạp qc từ doubleclick.net.
Source script của chúng:
1.
`https://www.tinmoi.vn/?mod=ajax&act=getAds2&device=1&module=news&category_id=2` trong đó cái id=n tùy theo trang.
2.
`https://www.tinmoi.vn/ga.js`

**Comment by hoang-rio** [comment]
Đã thêm ở commit: 22418c0347e76a5ac6dc14c12a04e69ed53907cb
