### ISSUE TITLE
[NSFW] Exist ads on website: vn.javbabe.net

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#480]
**Ads description**
Have banner ads in front of player

**Step to reproduce**
1. Go to website vn.javbabe.net
2. Open any video. Eg: https://vn.javbabe.net/ppsd-051-mosaic-removed/

**Website url**
https://vn.javbabe.net/ppsd-051-mosaic-removed/

**Screenshot**
<details>
<summary>Screenshot</summary>

![Screenshot_33](https://user-images.githubusercontent.com/114989985/200738685-732c670e-85df-43a5-8d3f-207a6661862c.png)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|105|Adblock Plus|3.14|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist|

**Comment by hoang-rio** [comment]
Please alway keep screenshot inside details tag. Thank.

**Comment by hoang-rio** [comment]
@tonylinhtv Did you check this website is Vietnamese or global website support Vietnamese language?

**Comment by tonylinhtv** [comment]
@hoang-rio this website maybe Vietnamese website but server located at USA
