### ISSUE TITLE
Exist ads on website: liquipedia.net

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#483]
**Ads description**
Have banner ads

**Step to reproduce**
1. Go to website liquipedia.net
2. Have 2 banner ads. one is at top center position, other is at left bottom corner

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

![Screenshot_36](https://user-images.githubusercontent.com/114989985/201605481-a505683b-4354-4b2f-90e2-db216ea170f4.png)

![Image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|105|Adblock Plus|3.14|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist|

**Comment by tonylinhtv** [comment]
Type of ads on this site may be the same as ads on site https://vietgiaitri.com. Please help me check!
![Screenshot_37](https://user-images.githubusercontent.com/114989985/201607670-3d915f5b-fc30-44fb-b5fd-9a53365f9aad.png)

**Comment by hoang-rio** [comment]
liquipedia.net is not Vietnamese website. https://vietgiaitri.com display ads because of exit in [AA List](https://easylist-downloads.adblockplus.org/exceptionrules.txt)
PS: Please remember create new issue for each website
