### ISSUE TITLE
[NSFW] Exist ads on website: xxxcouch.com

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#485]
**Ads description**
Have popunder ad on website xxxcouch.com

**Step to reproduce**
1. Go to website xxxcouch.com
2. Click on any video thumnail, there will appear popunder ad

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|105|Adblock Plus|3.14|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist|

**Comment by hoang-rio** [comment]
Please report Vietnamese website only.
