### ISSUE TITLE
[NSFW] Exist ads on website: javnong.cc

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#488]
**Ads description**
Have popunder ads on website javnong.cc

**Step to reproduce**
1. Go to website javnong.cc
2. Click on any video thumbnail. There will appear popunder ads

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|105|Adblock Plus|3.14|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist|

**Comment by hoang-rio** [comment]
Resolved in ABP Filters Anti CV

**Comment by hoangnm693** [comment]
hi @hoang-rio 
Banner display with ABPVN.

<details>

![image](https://github.com/abpvn/abpvn/assets/130738821/d180a5ea-810b-4741-ace3-c76d68aa4dfa)

</details>

Please check it.
Thank you.
