### ISSUE TITLE
Chặn QC trên vnexpress.net

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#49]
Filter: `||s1.vnecdn.net/*mads.js`
Script: `https://s1.vnecdn.net/vnexpress/restruct/j/v504/redesign/helper/mads.js`
Nó nạp qc từ `core.polyad.net`
P/s: Ngoài ra còn có script này: `https://s1.vnecdn.net/vnexpress/restruct/j/v504/v2/helper/mvod/ads.js` và `https://s1.vnecdn.net/vnexpress/restruct/j/v506/v2/helper/vod/ads.js`
, ko biết có thể gộp tất cả thành `||s1.vnecdn.net/*ads.js` được không?

**Comment by hoang-rio** [comment]
Bạn kiểm tra lại kết quả khi bật **EasyList** rồi cập nhật giúp mình nhé. Nếu **EasyList** chưa chặn mình sẽ thêm vào bộ lọc

**Comment by hoang-rio** [comment]
> Filter: `||s1.vnecdn.net/*mads.js`
> Script: `https://s1.vnecdn.net/vnexpress/restruct/j/v504/redesign/helper/mads.js`
> Nó nạp qc từ `core.polyad.net`
> P/s: Ngoài ra còn có script này: `https://s1.vnecdn.net/vnexpress/restruct/j/v504/v2/helper/mvod/ads.js` và `https://s1.vnecdn.net/vnexpress/restruct/j/v506/v2/helper/vod/ads.js`
> , ko biết có thể gộp tất cả thành `||s1.vnecdn.net/*ads.js` được không?

Quảng cáo từ `polyad.net` căn bản đã bị **ABPVN** chặn nên nếu script này không tạo ra quảng cáo hiển thị được trên màn hình thì mình sẽ không chặn nhé
