### ISSUE TITLE
[NSFW] Exist ads on website: [heovl.sex]

### ISSUE THREAD

**Issue by nguyenlve** [abpvn/abpvn#496]
**Ads description**
Need to wait 5s and click skip ads button to play video. 

**Step to reproduce**
1. go to website: heovl.sex
2. Open any video.

**Website url**
https://heovl.sex/videos/thu-dam-suong-qua-tinh-chay-khap-lon

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

https://user-images.githubusercontent.com/119655019/205818008-58225194-fa66-44d4-a7b2-c2d498353189.mp4

![heovl](https://user-images.githubusercontent.com/119655019/205814843-f75ec0b9-b060-429b-b71d-4c81ff16823d.jpg)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Adblock Browser |3.2.1|Adblock Plus|3.2.1|EasyList + ABPVN List, EasyPrivacy|

**Comment by nguyenlve** [comment]
[hangtt1@coccoc.com](mailto:hangtt1@coccoc.com)

**Comment by hoang-rio** [comment]
Please add prefix and keep all media inside details tag

**Comment by hoang-rio** [comment]
Ads video is blocked by EL and noway to skip this placholder by any Adblocker because of code of this site is not allow it. So this issue can not be fix
