### ISSUE TITLE
[NSFW] Exist ads on website: vlxxs.net

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#499]
**Ads description**
Have popunder ads

**Step to reproduce**
1. Go to website vlxxs.net
2. Click on menu item "KHÔNG CHE" on menu bar
3. Click on video item "Chào đón đêm noel đáng nhớ..."

**Website url**
https://vlxxs.net/

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>
![Screenshot_35](https://user-images.githubusercontent.com/114989985/209628478-f6f6d0de-99aa-4344-a918-e3ae9fb3cfbd.png)

![Image name](imageUrl)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|107|Adblock Plus|3.15|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist|

**Comment by tonylinhtv** [comment]
Popunder ads still happens.
Steps:
access vlxxs.net -> visit any video to watch -> click on play button. Popunder ads will appear.
Please help us check again. Thanks!

**Comment by hoang-rio** [comment]
Please confirm play button is in iframe? ABPVN can not process iframe of non Vietnamese website.

**Comment by tonylinhtv** [comment]
@hoang-rio  Yep. Play button is in iframe.

**Comment by hoang-rio** [comment]
ABPVN only can process it if iframe also Vietnamese website. If not ABPVN can not do anything
