### ISSUE TITLE
Chặn QC trên m.saostar.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#50]
Rules:
```
||ss-statics-m.catscdn.vn/*adsdefine/*
||ss-statics-m.catscdn.vn/*ads_cache/*
```
Cái này gần giống rule có sẵn của abpvn nhưng khác là nó _có thêm chữ "m" trước ".catscdn.vn"_.
Script:
```
https://ss-statics-m.catscdn.vn/data/themes/saostar_v5_mobile/assets/js/adsdefine/single.min.js?pversion=6.1.864
https://ss-statics-m.catscdn.vn/data/themes/saostar_v5_mobile/ads_cache/single/ad-single-mid-banner-2.js?pversion=1.36
```

**Comment by hoang-rio** [comment]
Cái  này bạn đã kiểm tra với **EasyList** chưa nhỉ

**Comment by hoang-rio** [comment]
Đã thêm ở 2e593b0

**Comment by vhpcdpgl** [comment]
Mình test rồi bạn. Nói chung các bộ lọc như vậy hình như người ta lập từ tracking trên PC nên nó ít chú ý tới các mã QC chỉ chạy trên mobile.
