### ISSUE TITLE
[NSFW] Exist pop-under ads on website: cliphotvn.com

### ISSUE THREAD

**Issue by nguyenminhkhmt** [abpvn/abpvn#500]
**Ads description**

**Step to reproduce**
1. Go to website
2. Random play a video on this site
3. ...

**Website url**
cliphotvn.com

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Ex: Firefox, Chrome|Ex: 91|Ex: Adblock Plus|Ex: 3.10|Ex: EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Please add NSFW for all adult issue report. If not it will be ignore
