### ISSUE TITLE
[NSFW] Exist ads on website: sexdiaryz.xyz

### ISSUE THREAD

**Issue by nguyenminhkhmt** [abpvn/abpvn#503]
**Ads description**

**Step to reproduce**
1. Go to the website
2. Play a random video
3. rewind forward/backward -> Show Pop-under ads

**Website url**
sexdiaryz.xyz

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

![Image name](imageUrl)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Coccoc iOS|114.0.134|Adblock Plus|Ex: 3.10|Ex: EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
This site use embed iframe from non Vietnamese website so ABPVN can not process
