### ISSUE TITLE
[NSFW] Pop-under ads on website: [cliphotvn.com]

### ISSUE THREAD

**Issue by nguyenminhkhmt** [abpvn/abpvn#505]
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'"><b>Ads description</b><br>
Website has pop-under ads when we play a video</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'"><b>Step to reproduce</b></p>
<ol style="list-style-type: decimal">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Go to website</li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Click on any video thumbnails</li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Play a video</li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">It opens pop-under ads</li>
</ol>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">(We can reproduce it by refreshing a tab without clearing the browsing history)</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; color: #dca10d"><span style="color: #000000"><b>Website url</b><br>
<a href="https://cliphotvn.com/">https://cliphotvn.com/</a></span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px"><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">With ABPVN Enabled</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px"><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 20.0px 'Helvetica Neue'"><b>Environment</b></p>

Browser | Browser Version | Adblocker Version
-- | -- | --
Coc Coc (iOS) | 112.0.504 (or latest appstore ver) | SDK version: 0.11.1; Blocklist version: 202301050517
  |   |  

<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px"><br></p>
<br class="Apple-interchange-newline">

**Comment by hoang-rio** [comment]
Duplicated with fixed issue #500

**Comment by nguyenminhkhmt** [comment]
Hi, this issue is not solved yet in the ios Cốc Cốc browser app. I checked this morning, and popup-ads still show.

**Comment by hoang-rio** [comment]
Issue #500 fixed use selector `cliphotvn.2tenz.top###video_player ~ div[id]` please check with your dev team about this css rule support
In the next time if problem happend again with same site same issue please comment in old issue don't create new please

**Comment by nguyenminhkhmt** [comment]
@hoang-rio the issue hasn't been solved yet.
Here is the list we use in our browser:

https://browser.coccoc.com/js/ios_abp_custom_rules.txt
https://easylist-downloads.adblockplus.org/abpvn-minified.txt
https://easylist-downloads.adblockplus.org/easylist-minified.txt

Please help. Thank

**Comment by nguyenminhkhmt** [comment]
Still not working. Please check with CocCoc iOS as described.

**Comment by hoang-rio** [comment]
I can not do anything because noway to debug Adblock in CocCoc iOS. Please only update comment to this issue when has debug method.

I remember I said about checking in where I can debug adblock.

**Comment by hoang-rio** [comment]
Tried with new element hiding rule
```adblock
cliphotvn.2tenz.top##div[style^="position:fixed;inset:0px;z-index:100000;"]
```
int commit 2d81f40
Hope it fixed your issue

**Comment by hoang-rio** [comment]
I close issue because you can not provide me how to debug it on CocCoc iOS. In other platform it working fine so nothing to continue.

Now i can confirm this issue resolved with video attached in https://github.com/abpvn/abpvn/issues/511#issuecomment-1427029810 please check it. It may be fixed by commit mention in https://github.com/abpvn/abpvn/issues/505#issuecomment-1386385513

To find old issue please check both open and closed issue.
Now and after until CocCoc provide method to debug ABP on Android, iOS platform we will close which issue only reproduce in CocCoc Android and CocCoc iOS because I don't know why and how to fix
