### ISSUE TITLE
[NSFW] Pop-under ads on website: [viet69.lol]

### ISSUE THREAD

**Issue by nguyenminhkhmt** [abpvn/abpvn#507]
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'"><b>Ads description</b><br>
Website has pop-under ads when we play a video</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'"><b>Step to reproduce</b></p>
<ol style="list-style-type: decimal">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Go to website</li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Click on any video thumbnails</li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Show pop-under ads in a new tab page.</li>
</ol>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">(We can reproduce it by refreshing a tab without clearing the browsing history)</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'"><b>Website url</b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; color: #dca10d"><a href="http://viet69.tv">viet69.tv</a></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px"><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">With ABPVN Enabled</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px"><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 20.0px 'Helvetica Neue'"><b>Environment</b></p>

Browser | Browser Version | Adblocker Version
-- | -- | --
Coc Coc (iOS) | 112.0.504 (or latest appstore ver) | SDK version: 0.11.1; Blocklist version: 202301050517
  |   |

**Comment by hoang-rio** [comment]
I checked with view-source and see it redirected to `viet69.lol`
Is this domain still work?

**Comment by nguyenminhkhmt** [comment]
the site viet69.tv redirects the user to viet69.lol. Same issue.
