### ISSUE TITLE
Exist ads on website: cafenau.com

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#508]
**Ads description**
Block Adblock

**Step to reproduce**
1. Go to website cafenau.com
2. It will show a banner to ask user to turn off Adblock

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

![Screenshot_38](https://user-images.githubusercontent.com/114989985/210748754-7d31644f-2c96-4f4b-b2ab-a65235b40c69.png)

![Image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Chrome|107|Adblock Plus|3.15|ABP filters, ABPVN List+EasyList, Adblock Warning Removal List, CocCoc standard whitelist|

**Comment by hoang-rio** [comment]
@tonylinhtv In next time please keep Image bellow summary tag with 1 empty line
