### ISSUE TITLE
[NSFW] Exist ads on website: [missav.com, sexdiaryz.xyz]

### ISSUE THREAD

**Issue by nguyenlve** [abpvn/abpvn#509]
**Ads description**
Automatically open 1 ads tab.

**Step to reproduce**
1. Go to website
2. Open any video

**Website url**
https://missav.com/
https://sexdiaryz.xyz/

**Screenshot**
<details>
<summary>With ABPVN Enabled</summary>

![Image name](imageUrl)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image name](imageUrl)
</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Adblock Browser|3.2.3|Adblock Plus|3.2.3|EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Don't forget prefix [NSFW] for adult site

**Comment by hoang-rio** [comment]
[sexdiaryz.xyz/](https://sexdiaryz.xyz/) duplicated in not plan to fix #503

**Comment by hoang-rio** [comment]
missav.com not is Vietnamese website
