### ISSUE TITLE
Chặn mã QC realclick.vn trên quantrimang.com

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#51]
**Rule:**
`||quantrimang.com/cache.aspx`
**Script:**
`https://quantrimang.com/cache.aspx?_path=https://realclick.vn/client/banner/&mod=lazy&data=zone|419|mrc419|zone|311|mrc311|zone|306|adrighttwo|zone|403|adsoutbounce`

**Comment by hoang-rio** [comment]
Rule này sẽ chặn mất cả tính năng khác load qua url:
`quantrimang.com/cache.aspx`

Mình đã chuyển thành
`/realclick.vn/` rồi thêm ở commit dd7c7394

**Comment by vhpcdpgl** [comment]
Ngoài cái realclick nó còn nạp qc của meta.vn nữa:
`https://quantrimang.com/cache.aspx?_path=http://meta.vn/ajx/Ajx_TopProducts2.aspx&top=2&min=-&max=-&kw=&ids=`

**Comment by hoang-rio** [comment]
Đã xử đẹp với commit ae1a8b37

**Comment by vhpcdpgl** [comment]
Bổ sung chặn mã quảng cáo trên quantrimang.com:
**Rule:**
`quantrimang.com###adsviewbottom`

**Element:**
`<div id="adsviewbottom" class="adbox">`
