### ISSUE TITLE
Block incorrect on website: medium.com

### ISSUE THREAD

**Issue by vinhphm** [abpvn/abpvn#510]
**Incorrect block description**
ABPVN blocks Medium's article titles as mentioned in https://github.com/AdguardTeam/AdguardFilters/issues/141284

**Step to reproduce**
1. Go to website
2. Sign in to Medium
3. Article titles on the left pane blocked by ABPVN filter.

**Website url**
[https://medium.com](https://medium.com)

<details>
<summary>With ABPVN Enabled</summary>

![image](https://user-images.githubusercontent.com/75784849/215822138-04997b5a-33b3-4548-9d49-f9de0d6bba21.png)
</details>
<details>
<summary>Without ABPVN Enabled</summary>

![image](https://user-images.githubusercontent.com/75784849/215822255-11530b11-b6d2-406d-9480-ca6967b0f9fd.png)

</details>

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|---------|----------------|--------------------------------|-----------------|-------------------|
|Safari|16.3|AdGuard for Safari|1.11.10|AdGuard filters + ABPVN List|
|Chrome|109.0.5414.119|uBlock Origin|1.46.0|EasyList + ABPVN List|

**Comment by hoang-rio** [comment]
Checked with ABPVN List + EasyList but no blocked in this site and this site view normaly

<details>
<summary>Normal site display</summary>

![ảnh](https://user-images.githubusercontent.com/11514638/215922039-e590dd9a-ea2c-40c7-87f8-b106999d6c9b.png)
</details>

Please provide blocked log if you make sure that issue come from ABPVN like this

<details>
<summary>Blocked log example</summary>

![ảnh](https://user-images.githubusercontent.com/11514638/215922325-783fb4cc-bd25-4a45-b251-5b78446ffbbb.png)

</details>

**Comment by BlazDT** [comment]
![image](https://user-images.githubusercontent.com/34266271/216013718-d73462d3-dce3-4569-aecc-35016da75ce5.png)

Fix is:

medium.com#@#.qc
