### ISSUE TITLE
[NSFW] Exist ads on website: http://cliphotvn.com/

### ISSUE THREAD

**Issue by nguyenminhkhmt** [abpvn/abpvn#511]
**Ads description**

**Step to reproduce**
1. Go to website
2. Click some videos
3. Site show pop-under ads

**Website url**

http://cliphotvn.com/

**Environment**
Browser: CocCoc iOS & Android
Browser Version: Lastest version from the Appstore
Extentions/Adblocker Programs: ABP
Adblocker Version: Latest version
Subscription Filter: EasyList (minified) + ABPVN List (minified) + CocCoc strict rule

**Comment by hoang-rio** [comment]
Dulicated with #500 and when check with CocCoc lastest on iOS no popup found.

<details>
<summary>[NSFW] Click to view screen capture video</summary>

https://user-images.githubusercontent.com/11514638/218313004-7693fa9e-3135-4a2c-956c-05f14deb61ef.MP4


</details>

In next issue please search and comment to exist issue intead of create new. This is not first time you create duplicate issue for same site
