### ISSUE TITLE
Can't load site after turn on ABP: toptruyen.me

### ISSUE THREAD

**Issue by nguyenminhkhmt** [abpvn/abpvn#513]
**Ads description**

**Step to reproduce**
1. Go to the website
2. Select any story to read
3. Observer.
4. Site can't load, only show a blank page.

**Website URL**
https://www.toptruyen.me

**Screenshot**
![Simulator Screen Shot - iPhone 12 Pro Max - 2023-02-16 at 09 03 47](https://user-images.githubusercontent.com/16470510/219292273-832f8562-2fb0-4796-bff7-46fbd3cb0a6e.png)

**Environment**
Browser: CocCoc iOS & Android
Browser Version: Lastest version from the Appstore
Extensions/Adblocker Programs: ABP
Adblocker Version: Latest version
Subscription Filter: EasyList (minified) + ABPVN List (minified) + CocCoc strict rule

**Comment by hoang-rio** [comment]
@nguyenminhkhmt Can you provide a screen capture video?

**Comment by nguyenminhkhmt** [comment]
https://drive.google.com/file/d/19HZVGF4zpbUy0Bfjtgg0mlwJ6QtY94Fk/view?usp=sharing
Pls check the video from here, the file size is too big to upload directly to GitHub. thank u

**Comment by hoang-rio** [comment]
I see you are using a debug version of CocCoc in a Simulator? Did you check Appstore version in a physical device to make sure issue is not come from debuging?

**Comment by nguyenminhkhmt** [comment]
Yes, the same issue happens with the main Product. I recorded the video from real device here:
https://drive.google.com/file/d/1AOKv3ozSFH7Ax_HiiZljlt5CeqclS6kj/view?usp=sharing

**Comment by hoang-rio** [comment]
I tried reproduce in Firefox Desktop, CocCoc Desktop, CocCoc Android but no way to reproduce this issue. It's mean this issue can't fix because only happend in CocCoc iOS

**Comment by hoang-rio** [comment]
@nguyenminhkhmt Because you have source code CocCoc iOS so I think you can debug and get log to know why it happed. If it come from filter rule that exist in ABPVN List please let me know

**Comment by monzta** [comment]
@nguyenminhkhmt I see in [CocCoc strict rules](https://browser.coccoc.com/js/ios_abp_custom_rules.txt) you seem to want to disable ad blocking on `toptruyen.me` with this exception rule: `@@||toptruyen.me` 

However, this rule will not disable it completely. Instead I would recommend using `@@||toptruyen.me^$document` 

Was this exception rule added to debug this particular issue or you simply want to disable ad blocking on `toptruyen.me` in general?

**Comment by nguyenminhkhmt** [comment]
Hi, actually, this is a temporary solution to allow users to read the manga site they want while we haven't solved the issue yet. I don't want it to affect our users' experiences because they can't access the site's content.

**Comment by nguyenminhkhmt** [comment]
As per the information provided by @hoang-rio, this issue is caused by the ABP engine and cannot be fixed by him. Therefore, we cannot wait and need to whitelist it first.

**Comment by monzta** [comment]
If you want to disable it for this domain, I would recommend using `@@||toptruyen.me^$document` instead of `@@||toptruyen.me`.

**Comment by nguyenminhkhmt** [comment]
Okay, got it. Thank u @monzta
