### ISSUE TITLE
Block incorrect on website: tuoitre.vn

### ISSUE THREAD

**Issue by megavietbm** [abpvn/abpvn#516]
### Check List

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%

### Incorrect block description

Still show blank space in tuoitre.vn

### Reproduce step

1. Go to website tuoitre.vn
2. Swipe down some topic in below and see the blank space of ads
3. please hide this blank space. Thank you

### Website url of issue

https://tuoitre.vn/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>With ABPVN Enabled</summary>

![image](https://user-images.githubusercontent.com/32122505/219565445-27228008-22be-4e35-9b4c-3fb2ef204644.png)
</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Without ABPVN Disabled</summary>

![image](https://user-images.githubusercontent.com/32122505/219565538-14173e7b-62d9-4a2a-87e9-2884025a2463.png)
</details>

### Environment

**Environment**
|Browser|Browser Version|Extentions/Adblocker Programs|Adblocker Version|Subscription Filter|
|-----------|-----------------------|-----------------|-----------------|-------------------|
|Adblock Browser 3.2.4|Ex: 91|Ex: Adblock Plus|Ex: 3.10|Ex: EasyList + ABPVN List, EasyPrivacy|

**Comment by hoang-rio** [comment]
Your are choose incorrect issue type. Please choose correct in next time
