### ISSUE TITLE
[NSFW] Exist ads on website: sexdiaryz.fun

### ISSUE THREAD

**Issue by megavietbm** [abpvn/abpvn#519]
### Check List

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

show popup ads on website: sexdiaryz.fun

### Reproduce step

1. Go to website
2. Click on any video or play video in detail
3. Popup ads will show

### Website url of issue

https://sexdiaryz.fun/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://user-images.githubusercontent.com/32122505/220046150-1d615987-f64c-4111-9398-32b295dc9fbd.png)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://user-images.githubusercontent.com/32122505/220045880-3cf394de-6f9f-4019-b8a7-03ca6453efe5.png)
</details>

### Browser

Adblock Browser 3.2.4

### Adblocker

Adblock Browser 3.2.4

### Active filter list

*Easy List+ FanBoy

**Comment by hoang-rio** [comment]
This type of ads can not be blocked with Adblock Plus normal syntax. It's only blockable with snippet. So your browser/your adblocker must be support snippet

**Comment by hoang-rio** [comment]
Fixed with ABP Filters
