### ISSUE TITLE
Exist ads on website: luotphimtv.cc

### ISSUE THREAD

**Issue by nonqxt86** [abpvn/abpvn#527]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Dọn giúp em mấy cái banner ads với bác

### Reproduce step

1. Go to website
2. ...
3. ...

### Website url of issue

https://luotphimtv.cc/phim/tan-tay-du-ky-2-t6/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Firefox 102

### Adblocker

Ublock Origin

### Active filter list

Bộ lọc Ublock + ABPVN

**Comment by hoang-rio** [comment]
Mình đã chặn mấy cái placeholder mình thấy do bạn k cung cấp ảnh chụp màn hình.
