### ISSUE TITLE
Exist ads on website: ophim.info

### ISSUE THREAD

**Issue by tonylinhtv** [abpvn/abpvn#528]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Center banner to ask user to turn off Adblock.
I tried to hide element "fc-ab-root". But after hiding, It's unable to scroll page anymore.

### Reproduce step

1. Go to website ophim.info
2. Center banner appears

### Website url of issue

https://ophim.info/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![Screenshot_5](https://user-images.githubusercontent.com/114989985/231113068-7abe32a4-8298-4517-aed2-f6e6dc773a39.png)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 110

### Adblocker

Adblock Plus 3.16

### Active filter list

* ABP filters
* ABPVN List+EasyList
* Adblock Warning Removal List
* CocCoc standard whitelist

**Comment by hoang-rio** [comment]
All banner now blocked but dismisable funding choice popup is out of scope so it still display. User can dismiss or allow ads with single click
