### ISSUE TITLE
[NSFW] Block incorrect on website: [viet69.love]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#529]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Incorrect block description

https://godpvqnszo.com/aas/r45d/vki/1955608/b6b2efb5.js
is blocked by ABPVN

### Reproduce step

1. Go to website: https://viet69.love/
2. Stuck at loading state

### Website url of issue

https://viet69.love/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

<img width="959" alt="image" src="https://user-images.githubusercontent.com/130738821/231972737-dc81fc93-3fb9-4a35-8c27-b0601cf82a24.png">
<img width="931" alt="image" src="https://user-images.githubusercontent.com/130738821/231972825-b4ceb970-f461-4813-b68b-bdb78e3ad1e7.png">
<img width="931" alt="image" src="https://user-images.githubusercontent.com/130738821/231972886-a8c33ea3-2dab-4f1e-b3a0-dc695e89d412.png">

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.16.2

### Active filter list

* ABP filters
* EasyList

**Comment by hoang-rio** [comment]
Fixed in abp filters anti cv
