### ISSUE TITLE
Chặn QC trên tapchitaichinh.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#53]
Rule1:
`||tapchitaichinh.vn/*adv.js`

URL:
`http://static.tapchitaichinh.vn/Tctc.Mobile/Jscripts/adv.js?v=1.0.1`

Rule2:
`||tapchitaichinh.vn/*adv.ashx`

URL:
`http://m.tapchitaichinh.vn/ajax/adv.ashx`

**Comment by bigdargon** [comment]
Qc ở vn gặp @vhpcdpgl chắc phải khóc thét 😄

**Comment by vhpcdpgl** [comment]
> Qc ở vn gặp @vhpcdpgl chắc phải khóc thét 😄 

Thực ra là vhpcdpgl đang khóc thét vì QC ở VN 😁
