### ISSUE TITLE
[NSFW] Block incorrect on website: [www4.bestjavporn.com]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#530]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

appear button close ads in this site if i blocked,site not load video.pls check thank you

### Reproduce step

1.Go to website: www4.bestjavporn.com
2.Stuck at  button "close"

### Website url of issue

www4.bestjavporn.com

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.16.2

### Active filter list

Active filter list
ABP filters
EasyList

**Comment by hoang-rio** [comment]
This issue is not follow the top check list (screenshot is not in details tag). It'll close without any check.
Addition this website is non Vietnamese
