### ISSUE TITLE
Block incorrect on website: [motphimtv.me]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#535]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Incorrect block description

can't load video 

### Reproduce step

Go to link "https://motphimtv.me/xem-phim/hen-uoc-ngot-ngao-dau-ha-tap-1-11180_132796.html"
i can't watch video

### Website url of issue

https://motphimtv.me/xem-phim/hen-uoc-ngot-ngao-dau-ha-tap-1-11180_132796.html

### Screenshot or screen capture when ABPVN enable

![image](https://github.com/abpvn/abpvn/assets/91521634/a69e3fe9-a45c-4c34-aa02-eb88dae54627)

### Screenshot or screen capture when ABPVN disabled

![image](https://github.com/abpvn/abpvn/assets/91521634/d839570d-baef-45bb-8b24-e0f89c3fadda)

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.17

### Active filter list

EasyList
ABPVN List

**Comment by hoang-rio** [comment]
I can play video normaly on this site. Please make sure that you are not active another filter
