### ISSUE TITLE
Block incorrect on website: [https://motphimtv.me,https://motchill.tv]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#538]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Incorrect block description

can't load video

### Reproduce step

1. Go to link "https://motphimtv.me/xem-phim/ban-trai-toi-la-ho-ly-phan-2-tap-1-11240_133429.html" and "https://motchill.tv/xem-phim/hoc-vien-dao-tao-ngoi-sao-tap-1-11216_133193.html"
2. Can't load  video 

### Website url of issue

https://motchill.tv/xem-phim/hoc-vien-dao-tao-ngoi-sao-tap-1-11216_133193.html

### Screenshot or screen capture when ABPVN enable

![image](https://github.com/abpvn/abpvn/assets/91521634/deceabac-2b79-4bcb-b691-5c07e242f2aa)
![image](https://github.com/abpvn/abpvn/assets/91521634/c35d6ae8-8504-446c-81b2-57ab9187474b)

### Screenshot or screen capture when ABPVN disabled

![image](https://github.com/abpvn/abpvn/assets/91521634/62c66a56-230d-4fbd-8981-8f46e18116ab)

![image](https://github.com/abpvn/abpvn/assets/91521634/a2030095-f246-4429-8e8f-528be5eabf5f)

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.17

### Active filter list

Easy list,APVN list

**Comment by hoang-rio** [comment]
@HoangHaiDang02 
Did you really check  **Reproduce rate is over 50%**
Please check it more careful in next issue
https://github.com/abpvn/abpvn/assets/11514638/376d003a-9ffe-40ca-a9d9-2a4350456aa5
