### ISSUE TITLE
Block incorrect on website: [animehay.io]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#541]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Incorrect block description

can't load video

### Reproduce step

1. Go to link https://animehay.io/xem-phim/highschool-of-the-dead-tap-11-5251.html
2. Can't watch video

### Website url of issue

https://animehay.io/xem-phim/highschool-of-the-dead-tap-11-5251.html

### Screenshot or screen capture when ABPVN enable

![image](https://github.com/abpvn/abpvn/assets/91521634/064d6291-03d1-44ad-a1d8-f70e9eb48907)

### Screenshot or screen capture when ABPVN disabled

![image](https://github.com/abpvn/abpvn/assets/91521634/26d58952-460c-4fcd-9041-2577916a1940)

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.17

### Active filter list

ABPVN List+EasyList

**Comment by hoang-rio** [comment]
I can watch video normaly with ABP enable. Please check again.

Addition this site use embed from non Vietnamese website so it may not be process by ABPVN

**Comment by hoang-rio** [comment]
Sorry about my mistake. I create PR to https://github.com/abp-filters/abp-filters-anti-cv/pull/1380 to fix this issue
