### ISSUE TITLE
Exist after ads space on website: [myeva.vn]

### ISSUE THREAD

**Issue by eporubin** [abpvn/abpvn#542]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Hi 👋  there are left blank spaces on this [website](https://myeva.vn/muon-con-hieu/ ) there there used to be ads, there is an empty bottom tab and also several spaces in the page such us:
**Bottom tab**
- `myeva.vn###adop_bfd`
- <img width="1421" alt="image" src="https://github.com/abpvn/abpvn/assets/33602691/89ac400d-04d5-4e6f-8239-8e6a11c137fe">
**Empty space after the picture**
-`myeva.vn##.adsbypubpower`
-<img width="854" alt="image" src="https://github.com/abpvn/abpvn/assets/33602691/13a6061d-b950-4a83-96ec-31cfa33a8e96">
**Empty space on page in the article x2** 
-`myeva.vn##ins[class*="adsby"]`
-<img width="854" alt="image" src="https://github.com/abpvn/abpvn/assets/33602691/a3230d12-6286-444f-a905-17575d25a25f">
Please review and add the necessary filter to the list

### Reproduce step

1. Go to [website ](https://myeva.vn/muon-con-hieu/ )

### Website url of issue

https://myeva.vn/muon-con-hieu/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Google Chrome (Version 114.0.5735.133) 

### Adblocker

Adblock Plus 3.17

### Active filter list

ABP Filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
@eporubin if you know how to create filter you should follow Contributing guild and create a PR
