### ISSUE TITLE
Block incorrect on website: www.clickadu.com

### ISSUE THREAD

**Issue by cl-bvl** [abpvn/abpvn#545]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [ ] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Incorrect block description

Hello.
The rule 
```
@@||www.clickadu.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js$script,domain=linkneverdie.net
```
in `filter/abpvn.txt` blocking cloudflare script that required to normal site working.

It's 100% legal script presented on all Cloudflare sites, like
https://cloudflare.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js
https://docker.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js
https://digitalocean.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js
and hundred of thousand other websites. 

Thank you.

### Reproduce step

1. Go to website
2. ...
3. ...

### Website url of issue

https://www.clickadu.com

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>
</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 114

### Adblocker

All

### Active filter list

`abpvn.txt`

**Comment by hoang-rio** [comment]
This is white list rule and it only run in specific site in $domain. This domain is blocked by another rule in ABPVN because it serving ads

**Comment by cl-bvl** [comment]
Hmmm, really.
Thanks.
