### ISSUE TITLE
Block not ads content: [https://video.kenh14.vn/]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#547]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

can't load the site

### Reproduce step

1. Go to website link https://video.kenh14.vn/
2. can't watch site

### Website url of issue

https://video.kenh14.vn/

### Screenshot or screen capture when ABPVN enable

![image](https://github.com/abpvn/abpvn/assets/91521634/486d2922-c9ff-4ae3-8cac-30f389f9efd0)

### Screenshot or screen capture when ABPVN disabled

![image](https://github.com/abpvn/abpvn/assets/91521634/cf88b60f-3b3b-4698-a039-8d030fe65f6a)

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.18

### Active filter list

abpvn+easylist

**Comment by hoang-rio** [comment]
Please choose correct template. Thanks

**Comment by HoangHaiDang02** [comment]
sorry, i changed
