### ISSUE TITLE
Block incorrect on website: [audiotruyenfull.com]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#549]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Incorrect block description

can't load site when enable abp in device iPhone12

### Reproduce step

1. Go to website audiotruyenfull.com
2. can't watch content site

### Website url of issue

audiotruyenfull.com

### Screenshot or screen capture when ABPVN enable

![image](https://github.com/abpvn/abpvn/assets/91521634/35d4dc3f-b698-40ee-bf06-e23be3f69190)

### Screenshot or screen capture when ABPVN disabled

![image](https://github.com/abpvn/abpvn/assets/91521634/0e9e31d5-1662-44b2-a272-4698b8c3305a)

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.17

### Active filter list

EasyList + ABPVN List

**Comment by hoang-rio** [comment]
ABPVN has no false positive rule in this site. Please make sure that you are not using in any other filter list
![ảnh](https://github.com/abpvn/abpvn/assets/11514638/8ff508a3-6b9e-4ccd-8953-834f6e29cf71)

**Comment by HoangHaiDang02** [comment]
yes, the issue just appear in device iPhone12 (not devtool in bowsers). i think it is problem from abp(not rules).

**Comment by hoang-rio** [comment]
> yes, the issue just appear in device iPhone12 (not devtool in bowsers). i think it is problem from abp(not rules).pls help me check in device iPhone or macOS(with abp on safari) with useragent (iPhone or iPad)

You should check it by your self because I have no device at this moment
