### ISSUE TITLE
Block incorrect on website: [https://vndoc.com]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#550]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Incorrect block description

can't download document learning in site. pls help me check

### Reproduce step

1. Go to link "https://vndoc.com/download/tuyen-tap-37-de-thi-hoc-ki-1-mon-toan-lop-2-103293"
2. click button download
3. can't download and site white

### Website url of issue

https://vndoc.com/download/tuyen-tap-37-de-thi-hoc-ki-1-mon-toan-lop-2-103293

### Screenshot or screen capture when ABPVN enable

![image](https://github.com/abpvn/abpvn/assets/91521634/0318924e-75ed-44b3-beb7-b524d50c5685)

### Screenshot or screen capture when ABPVN disabled

![image](https://github.com/abpvn/abpvn/assets/91521634/5be5e830-2619-4043-8bb3-094f8d993aa8)

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.18

### Active filter list

ABPVN List+EasyList

**Comment by hoang-rio** [comment]
Checked with ABPVN List + EasyList in Chrome with ABP but no issue found. Please let me know if you are using at least another filter list

![Screenshot 2023-08-14 at 14 48 30](https://github.com/abpvn/abpvn/assets/11514638/4feb3ffb-f7e1-4902-bc11-b10e03ce3f5b)

**Comment by hoang-rio** [comment]
In issue report check list has "Reproduce rate is over 50%" but i don't know why you make incorrect report many time

**Comment by HoangHaiDang02** [comment]
when click button "Tải về" t can't download with some site after check appear issue with abpvnlist.pls help me review it

**Comment by hoang-rio** [comment]
> when click button "Tải về" t can't download with some site after check appear issue with abpvnlist.pls help me review it

It's may not issue from ABPVN List. It may come from EL. I'll take a check

**Comment by HoangHaiDang02** [comment]
thank you so much @hoang-rio
