### ISSUE TITLE
Exist ads on website: [animesub.me]

### ISSUE THREAD

**Issue by ghajini** [abpvn/abpvn#551]
### Checklists

- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

banner & video preroll ads

### Reproduce step

1. Go to website 
2. play the video
3. ads

### Website url of issue

`https://animesub.me/xem-phim-dua-con-cua-than-tuong/1-sv1.html`

### Screenshot or screen capture when ABPVN enable

`https://github.com/abpvn/abpvn/assets/20338483/e3cb79fc-93e9-4bbb-a461-adafca1a2879`
`https://github.com/abpvn/abpvn/assets/20338483/1564e084-1ded-4926-a721-94bcd47176b9`

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

opera stable

### Adblocker

ublock origin 1.52

### Active filter list

all default ublock filter lists + ABPVN List

**Comment by hoang-rio** [comment]
@ghajini Please make sure that all check list passed in the future issue before submit.
In this issue check list item "Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab" was not pass
