### ISSUE TITLE
Exist ads on website: ["www.molympiad.net"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#552]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

appear detect adblock the site

### Reproduce step

1. Go to website "https://www.molympiad.net/2022/05/de-thi-olympic-10-3-tinh-dak-lak-2020-2021-khoi-10.html"
2. appear detect adblock

### Website url of issue

https://www.molympiad.net/2022/05/de-thi-olympic-10-3-tinh-dak-lak-2020-2021-khoi-10.html

### Screenshot or screen capture when ABPVN enable

![image](https://github.com/abpvn/abpvn/assets/91521634/d9df2bbf-da29-4411-ab57-f114c5dd3bc7)

### Screenshot or screen capture when ABPVN disabled

![image](https://github.com/abpvn/abpvn/assets/91521634/e18a6407-33fa-4e21-a8d4-35e39aa9d91a)

### Browser

Cốc Cốc Browser 116.0.198

### Adblocker

Adblock Plus 3.17

### Active filter list

ABPVN List
Easy List

**Comment by hoang-rio** [comment]
Please create issue again with correct issue template. Thanks
