### ISSUE TITLE
Exist ads on website: ["vn.phimxxx.us"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#556]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

appear banner

### Reproduce step

1. Go to website "https://vn.phimxxx.us/"
2. Choose video
3. Banner appear

### Website url of issue

"https://vn.phimxxx.us/"

### Screenshot or screen capture when ABPVN enable

![image](https://github.com/abpvn/abpvn/assets/91521634/83685b0b-229b-47d5-a53f-8834845ffc3c)

### Screenshot or screen capture when ABPVN disabled

![image](https://github.com/abpvn/abpvn/assets/91521634/7964c88e-aeaf-4690-a875-ccba3e555dfe)

### Browser

Cốc Cốc Browser 120

### Adblocker

Adblock Plus 3.19

### Active filter list

Easy List
ABPVN List

**Comment by hoang-rio** [comment]
Any issue does not pass the check list will be close without any process. @HoangHaiDang02 please check checklist and do it carefully

**Comment by hoang-rio** [comment]
@HoangHaiDang02 If you create any issue does not pass the checklist one more time I will block you from ABPVN List repo because this is not the first time you create issue about adult website without NFSW prefix and uploaded image outside details tag (it will show image when open issue not like standard must be click to see the image)

**Comment by HoangHaiDang02** [comment]
I'm very sorry for the above incident. I will not repeat the same mistake in the next reports @hoang-rio

**Comment by hoang-rio** [comment]
> I'm very sorry for the above incident. I will not repeat the same mistake in the next reports @hoang-rio

You must create another issue with correct information and required format
