### ISSUE TITLE
Chặn script chạy QC trên tinmoi24.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#56]
Rule :
`||tinmoi24.vn/js/ajax-detail.js`
URL:
`https://tinmoi24.vn/js/ajax-detail.js?v=1.4`

**Comment by hoang-rio** [comment]
Cái này load quảng cáo ở đâu vậy bạn?

**Comment by vhpcdpgl** [comment]
> Cái này load quảng cáo ở đâu vậy bạn?

Nó nạp qc từ Google. Có thể xem trong code của file .js ở trên.

**Comment by hoang-rio** [comment]
Ý mình là nó hiển thị quảng cáo ra chỗ nào trên trang. Còn nạp quảng cáo từ google mà quảng cáo đó không hiển thị được thì kệ nó.

**Comment by vhpcdpgl** [comment]
Ừ thì kệ nó đi 😋
