### ISSUE TITLE
Exist ads on website: [nettruyenai.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#561]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://nettruyenai.com/
2. Click anywhere on website

### Website url of issue

https://nettruyenai.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/ffb56469-2bc3-4624-a489-130a25199e7d)
![image](https://github.com/abpvn/abpvn/assets/130738821/c25801a1-e174-4ca9-9d01-983b571d31ff)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/0118a786-efd4-4362-8904-23edf1c9e1e9)
![image](https://github.com/abpvn/abpvn/assets/130738821/6bdbbe50-16a1-4221-86f8-a00cc5a67bde)

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoangnm693** [comment]
hi @hoang-rio 
Popunder ads appears again.
Pls help to check it.
Thank you.

**Comment by hoang-rio** [comment]
Popup block with ABP Filter via MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/18
