### ISSUE TITLE
Exist ads on website: [gavang.link]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#562]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website gavang.link

### Website url of issue

https://gavang.link/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/993bfab6-21b2-428a-be7e-91a7b90554da)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/9ad18682-16c5-4d98-abca-8902ddba97cb)

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoangnm693** [comment]
Seem ads appears again on https://gavang.link/
Pls help to check it.
Thank you.

**Comment by hoang-rio** [comment]
> Seem ads appears again on https://gavang.link/
> Pls help to check it.
> Thank you.

Checked but no ads banner found

**Comment by hoang-rio** [comment]
Added rule to block some missing ads but it's not banner ads
