### ISSUE TITLE
[NSFW] Exist ads on website: [vailonxx.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#563]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Banner ads and popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://vailonxx.com/

### Website url of issue

https://vailonxx.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/bc02b92a-79cd-4886-af2f-dc64e349b4fa)
![image](https://github.com/abpvn/abpvn/assets/130738821/4d939836-10f8-4308-ae90-e0d2b278834e)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/10576b19-0599-46bf-b026-9a131ad1ce0d)

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by HoangHaiDang02** [comment]
appear banner ads and pop-under ads on the site
### Step check 
go to site "vailonxx.com"
and choose frist video, site will redirect to other site (make same on video you can see it)
### video 
<details>
<summary>Click to open</summary>


[Screencast from 09-11-2023 18:22:48.webm](https://github.com/abpvn/abpvn/assets/91521634/edf6d56e-9b49-4c34-96cc-44293d5bd1b3)



</details>

**Comment by hoang-rio** [comment]
> a @hoang-rio, appear banner ads and pop-under ads on the site, help me check it
> ### Step check 
> go to site "vailonxx.com"
> and choose frist video, site will redirect to other site (make same on video you can see it)
> ### video 
> <details>
> <summary>Click to open</summary>
> 
> 
> [Screencast from 09-11-2023 18:22:48.webm](https://github.com/abpvn/abpvn/assets/91521634/edf6d56e-9b49-4c34-96cc-44293d5bd1b3)
> 
> 
> 
> </details>

Updated. Please check

**Comment by hoangnm693** [comment]
Banner ads and popup under ads appears again.
Pls help to check.
<details>

![image](https://github.com/abpvn/abpvn/assets/130738821/9684fc5f-87b6-4185-af4f-3b5bccab296d)

</details>
