### ISSUE TITLE
Exist ads on website: [animevietsub.boctem.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#570]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website https://animevietsub.boctem.com/

### Website url of issue

https://animevietsub.boctem.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/006b8741-4762-4d45-9a3e-ac98bc5781c4)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoangnm693** [comment]
i re-check today.
Banner ads still display with ABPVN
![image](https://github.com/abpvn/abpvn/assets/130738821/5a7501d0-ce9e-4f9e-814b-e1c4fd578283)

**Comment by hoang-rio** [comment]
It's a ABP bug when has multiple domain in same element hiding rule. I changed domain order in element hide rule
