### ISSUE TITLE
Exist ads on website: [hhhkungfu.tv]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#578]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://hhhkungfu.tv/cuu-thien-huyen-de-quyet
2. Click Xem phim

### Website url of issue

https://hhhkungfu.tv

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/d64250f9-347d-4a3d-bd1c-e6c385380456)
![image](https://github.com/abpvn/abpvn/assets/130738821/caeec2c1-2711-4924-b187-4ae1039f0e2e)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoangnm693** [comment]
This sites now has popunder ads.
URL: https://hhhkungfu.tv/tien-nghich
<details>
![image](https://github.com/abpvn/abpvn/assets/130738821/aa1e0030-8bbe-46b7-ad77-65de2347a426)

</details>

**Comment by HoangHaiDang02** [comment]
appear pop-under on the site, help me check it
step:
1.go to site "hhhkungfu.tv"
2.change to mobile mode
3.choose video and click "xem phim" .site will redirect to orther site
<details>
<summary>Click to open</summary>


[Screencast from 30-10-2023 17:26:11.webm](https://github.com/abpvn/abpvn/assets/91521634/aff6c772-a90c-4d89-b394-1a42b258821e)



</details>

**Comment by hoang-rio** [comment]
> appear pop-under on the site, help me check it
> step:
> 1.go to site "hhhkungfu.tv"
> 2.change to mobile mode
> 3.choose video and click "xem phim" .site will redirect to orther site
> <details>
> <summary>Click to open</summary>
> 
> 
> [Screencast from 30-10-2023 17:26:11.webm](https://github.com/abpvn/abpvn/assets/91521634/aff6c772-a90c-4d89-b394-1a42b258821e)
> 
> 
> 
> </details>

Updated. Please check
