### ISSUE TITLE
Exist ads on website: [biphim.in]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#579]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website https://biphim.in/

### Website url of issue

https://biphim.in/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/b1608385-030b-434e-b735-8a57f5610518)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoangnm693** [comment]
This sites now has popunder ads.
https://biphim.in/
Pls help to check it.
Thank you.

**Comment by hoang-rio** [comment]
> This sites now has popunder ads. https://biphim.in/ Pls help to check it. Thank you.

Checked but no popupder ads found. Please provide reproduce step or video

**Comment by hoangnm693** [comment]
Pls check this video.
https://coccocvn-my.sharepoint.com/:v:/g/personal/hoangnm2_coccoc_com/EaA_UrZVL2JKrq1osImeotABYnLtAZQn679YQL8Gdx81yQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=xVl8Zp
