### ISSUE TITLE
Exist ads on website: [animevietsub.fan]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#580]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://animevietsub.fan/phim/ao-no-orchestra-a4920/
2. click anywhere on website

### Website url of issue

https://animevietsub.fan

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

<img width="951" alt="image" src="https://github.com/abpvn/abpvn/assets/130738821/cd36ccbd-4b85-4165-b0b3-e9b29e12ae17">
<img width="958" alt="image" src="https://github.com/abpvn/abpvn/assets/130738821/98a6d9f8-7f13-4e3e-8ee1-c0a7b692bda6">

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
It must be fix via ABP Filters. Here is created merge request: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/11 Please follow this MR
