### ISSUE TITLE
Exist ads on website: [subnhanh.im]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#581]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website https://subnhanh.im/xem-phim/co-nang-gang-nam-soon-manh-me-strong-girl-nam-soon-2023-vietsub-tap-1.html

### Website url of issue

https://subnhanh.im

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/bb3f64af-3bf3-4f60-b957-b2a98a7b9579)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoangnm693** [comment]
i got same issue on https://subnhanhvl.cc/
Pls help to fix it.
Thank you.

**Comment by hoang-rio** [comment]
> hi @hoang-rio I got same issue on https://subnhanhvl.cc/ Pls help to fix it. Thank you.

It just is a replica domain. I will add this to ABPVN
