### ISSUE TITLE
Exist ads on website: [phimmoi.im]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#584]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Popunder ads and banner ads still display with ABPVN

### Reproduce step

1. Go to website https://phimmoi.im/

### Website url of issue

https://phimmoi.im/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/f7f61c73-7937-42fc-931a-d93f7515494d)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Popup must be block via ABP Filters. See MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/13

**Comment by hoangnm693** [comment]
hi @hoang-rio 
At the bottom of page, banner ads still display with ABPVN.
<details>

![image](https://github.com/abpvn/abpvn/assets/130738821/b7fecb70-1875-4e30-b745-010262a98f46)

</details>

**Comment by hoang-rio** [comment]
> hi @hoang-rio At the bottom of page, banner ads still display with ABPVN.

Updated. Please check
