### ISSUE TITLE
Exist ads on website: [animet.net]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#585]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Popunder ads and banner ads still display with ABPVN

### Reproduce step

1. Go to website https://animet.net/

### Website url of issue

https://animet.net/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/1c5e160b-246f-4374-b25a-868f0bbd2d66)
![image](https://github.com/abpvn/abpvn/assets/130738821/883a6b70-9c45-4573-9b59-80bda9f07934)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Popup must be block via ABP Filters. Check this MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/13
