### ISSUE TITLE
Exist ads on website: [tctruyen.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#586]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://tctruyen.com/truyen-tranh/tokyo-manji-revengers-11932
2. Click on the white space on the left then popunder ads appears.

### Website url of issue

https://tctruyen.com

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/2a6b90ae-22c1-44a9-8a1d-dc29e2a34cf9)
![image](https://github.com/abpvn/abpvn/assets/130738821/09613d87-39f2-418f-b40c-47d5251d10a7)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Popup must be block via ABP Filters. Check this PR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/13

**Comment by HoangHaiDang02** [comment]
hi a @hoang-rio, site appear pop-under pls help me recheck site
### Step check
Go to website "tctruyen.com"
Choose comic and choose chap comic
Site will redirect to other site
### Video screen
<details>
<summary>Click to open</summary>


[Screencast from 09-11-2023 17:39:57.webm](https://github.com/abpvn/abpvn/assets/91521634/93fdf68e-4ef4-490e-bc9b-3d9e3d58447c)



</details>

**Comment by hoang-rio** [comment]
Please make sure that your ABP Filters updated and work correctly. Popup on this site opened by inline script only blocked with scriptlet. I've just checked and no popup found

**Comment by HoangHaiDang02** [comment]
this is rules i used
<details>
<summary>Click to open</summary>


![image](https://github.com/abpvn/abpvn/assets/91521634/7f1f067d-ea2b-49c0-9635-a88311ddac66)



</details>

**Comment by hoang-rio** [comment]
Fixed. Please update
