### ISSUE TITLE
Exist ads on website: [tctruyen.net]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#595]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://tctruyen.net/truyen-tranh/toi-thang-cap-mot-minh/chapter-197/578809.html
2. click on page

### Website url of issue

https://tctruyen.net

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

<img width="953" alt="image" src="https://github.com/abpvn/abpvn/assets/130738821/cfacb47e-701d-453a-9d2f-0965f01bd5c0">

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Popup block with ABP FIlters via MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/15
