### ISSUE TITLE
[NSFW] Exist ads on website: [hentaizz.vip]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#596]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://hentaizz.vip/
2. click on page

### Website url of issue

https://hentaizz.vip/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

<img width="957" alt="image" src="https://github.com/abpvn/abpvn/assets/130738821/f9b67bb4-1c4f-4a00-b6d5-cd72e9813ec7">

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Popup block with ABP Filters via MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/16

**Comment by hoangnm693** [comment]
Now, this domain has banner ads.
![image](https://github.com/abpvn/abpvn/assets/130738821/922de2a1-78d8-41c0-97a0-630338e27fcf)

**Comment by hoang-rio** [comment]
> Now, this domain has banner ads.
> ![image](https://github.com/abpvn/abpvn/assets/130738821/922de2a1-78d8-41c0-97a0-630338e27fcf)
> 

Updated. Please check
