### ISSUE TITLE
[NSFW] Exist ads on website: [truyensextv.org]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#598]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website https://truyensextv.org/

### Website url of issue

https://truyensextv.org/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

<img width="958" alt="image" src="https://github.com/abpvn/abpvn/assets/130738821/f2a5838b-1dd9-41eb-8225-cc69db13fc9a">

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 117

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoangnm693** [comment]
hi @hoang-rio 
popunder ads display with ABPVN.
URL: https://truyensextv.org/hiep-dam-chi-dau-full/

<details>


https://github.com/abpvn/abpvn/assets/130738821/3fb14b35-3145-42a3-a3b9-00d5edc62e7a


</details>

Thank you.

**Comment by hoang-rio** [comment]
See ABP Filters MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/98
