### ISSUE TITLE
Exist ads on website: ["phimtuoitho.tv"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#599]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Ads description

appear some banner ads when go to site "phimtuoitho.tv"

### Reproduce step

1. Go to website "phimtuoitho.tv"
2. Can see some ads at between screen(when scroll down you can see it) and below screen

### Website url of issue

phimtuoitho.tv

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![phimtuoitho_Ad1](https://github.com/abpvn/abpvn/assets/91521634/11d62ae2-146f-4775-bd5c-d0831e196d6c)
![phimtuoitho_Ad2](https://github.com/abpvn/abpvn/assets/91521634/a7cbf5ea-5086-4258-947f-22b5316802f6)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/889246d5-5b63-4f3b-b3e2-d6ab2c1d827b)

</details>

### Browser

Cốc Cốc Browser 121.0.188

### Adblocker

Adblock Plus 3.19

### Active filter list

ABPVN List + EasyList

**Comment by HoangHaiDang02** [comment]
<details><summary>click</summary>
![image](https://github.com/abpvn/abpvn/assets/91521634/ace7b6c2-73f0-4a59-9ea7-aabece4d903b)
<details>
maybe issue comeback pls help me check it. thank you so much

**Comment by hoang-rio** [comment]
> click
> 
> maybe issue comeback pls help me check it. thank you so much

Something when wrong with commit tree. I'm checking and will getting back to you soon

**Comment by hoang-rio** [comment]
@HoangHaiDang02 Git commit tree issue now resolved. Everything now ok

**Comment by HoangHaiDang02** [comment]
@hoang-rio  i have rechecked. Fine with me thank you so much

**Comment by HoangHaiDang02** [comment]
issue still appearr banner on desktop

**Comment by hoang-rio** [comment]
> issue still appear bottom banner and appear banner on iOS device pls help me check it
> Click to open
> Click to open

It's only appear in iOS device so it mean it not filter list problem. Please don't report in the environment where I can not debug. I only can support for debugable brower/device like windows, macos and android. I have no way to debug in iOS because it's does not support debug method and it usually got filter rule compatible issue

**Comment by HoangHaiDang02** [comment]
sorry, it also appear in android divice with Cốc Cốc browser. Can you help me check it?

**Comment by hoang-rio** [comment]
> appear banner ads on the site help me check. thank you so much anh @hoang-rio
> click

This is self promotion banner with shorten link to internal content. ABPVN will not block this type of banner
