### ISSUE TITLE
ad có thể thêm cái k cần bấm captcha đc k

### ISSUE THREAD

**Issue by Moon229** [abpvn/abpvn#6]
mình xài cái raiblock nó bắt bấm captcha nhiều quá

**Comment by abpvn** [comment]
Bạn có thể tìm hiểu về captcha trên google nhé! Nếu mình có khả năng qua mặt được captcha thì mình giàu lâu rồi. Trả lời thế cho vui thông và không có cách nào đâu bạn. Close giúp mình luôn nhé :)
