### ISSUE TITLE
Block incorrect on website: [bestcrazygames.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#601]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab

### Incorrect block description

website show anti adblock popup

### Reproduce step

1. Go to website https://www.bestcrazygames.com/game/blocky-gun-paintball

### Website url of issue

https://www.bestcrazygames.com

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/64488f0b-3040-4bc7-bcfd-1eb97a3be7ea)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Cốc Cốc Browser 121.0.188

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List

**Comment by hoang-rio** [comment]
This website is not belong to Vietnamese so please report to EasyList
