### ISSUE TITLE
[NSFW] Exist ads on website: [dualeotruyenpk.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#602]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://dualeotruyenpk.com/

### Website url of issue

https://dualeotruyenpk.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
It's just domain redirection
Report domain redirection at https://abpvn.com/report/ with commit https://github.com/abpvn/abpvn/commit/f7f2b6c8afb0dc6adc5ddbbbb1d9f50d59e17da6

Popup blocker via ABP Filters processed manualy via MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/17
