### ISSUE TITLE
Exist ads on website: [phimbom.net]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#603]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

Banner ads & popup under ads still display with ABPVN

### Reproduce step

1. Go to website https://phimbom.net/

### Website url of issue

https://phimbom.net/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/7c5204e1-e169-4f06-b8b1-3b9494516519)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Popunder blocker with ABP Filters with MR https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/19
