### ISSUE TITLE
[NSFW] Exist ads on website: [vlxx.moe]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#606]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website https://vlxx.moe/

### Website url of issue

https://vlxx.moe/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/ae2dba12-05ff-42af-b806-7eb864901469)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by HoangHaiDang02** [comment]
### Ads description
ads still display with ABPVN

### Reproduce step
1. Go to website "vlxx.moe"
2. Turn on devtool and move mobile state
3. choose video site will redirect

### Video
<details>
<summary>Click to open</summary>


[Screencast from 30-10-2023 15:08:48.webm](https://github.com/abpvn/abpvn/assets/91521634/9935866b-bc69-403c-a18f-4a8d64551f17)



</details>

**Comment by hoang-rio** [comment]
Popunder block via ABP Filters with MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/28 please wait until it merged and confirm

**Comment by HoangHaiDang02** [comment]
hi a @hoang-rio, during the reporting process, I saw that the domain "pashiwjudffa.com" appeared on the network. Can we block this domain for many sites and is it effective? help me confirm thankyou so much

**Comment by hoang-rio** [comment]
> hi a @hoang-rio, during the reporting process, I saw that the domain "pashiwjudffa.com" appeared on the network. Can we block this domain for many sites and is it effective? help me confirm thankyou so much

This domain loaded via inline script will be blocked by snippet rule above.

**Comment by HoangHaiDang02** [comment]
Currently, I have some similar problems loading the same domain. Can I report here? Or create new problems?

**Comment by hoang-rio** [comment]
> Currently, I have some similar problems loading the same domain. Can I report here? Or create new problems?

Key of issue is domain. All issue about same domain must be report in same issue

**Comment by HoangHaiDang02** [comment]
thank you so much for information

**Comment by hoang-rio** [comment]
MR was merged. Please wait until it update to ABP Filters URL https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt
