### ISSUE TITLE
Exist ads on website: [nhattruyenmin.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#609]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website https://nhattruyenmin.com/truyen-tranh/blue-box/chap-96/983544

### Website url of issue

https://nhattruyenmin.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/e39353fb-7245-4f39-8ebb-3bf7a098d1cd)
![image](https://github.com/abpvn/abpvn/assets/130738821/f7e51c99-fc7a-479b-9670-6878a71086b0)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoangnm693** [comment]
Seem like domain has been changed to nhattruyenplus.com
But when i report domain change in https://abpvn.com/report/?submit then got this message
<details>
![image](https://github.com/abpvn/abpvn/assets/130738821/bf93539b-0748-4105-b845-ac82ea1654fa)
</details>

**Comment by hoang-rio** [comment]
> Seem like domain has been changed to nhattruyenplus.com But when i report domain change in https://abpvn.com/report/?submit then got this message

Image inside detail tag must have one blank line to displayable. I've just checked nhattruyenmin.com it not redirectiont nhattruyenplus.com so report tools work correctly. It may be only redirect when match some condition

**Comment by hoang-rio** [comment]
<details>

![ảnh](https://github.com/abpvn/abpvn/assets/11514638/6856b767-ed6a-40d7-ba37-f9f8e019a210)
</details>
I see it's change url directly. Not make a redirection so report tool will not work.
I will add nhattruyenplus.com as a replica domain

**Comment by hoangnm693** [comment]
Popunder ads still display with ABPVN.
Domain: nhattruyenplus.com
Thank you.

**Comment by hoang-rio** [comment]
> Popunder ads still display with ABPVN. Domain: nhattruyenplus.com Thank you.

Same as #622 please update ABPVN List to lastest version
