### ISSUE TITLE
Exist ads on website: [holyphim.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#613]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://holyphim.com/phim-hd-online/titanic-1997f

### Website url of issue

https://holyphim.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/5646bcf3-2384-40c7-a519-c2600dc606af)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Popup block with ABP Filters via MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/22
