### ISSUE TITLE
Block incorrect on website: [phimchillc.net]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#620]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Incorrect block description

website show anti adblock popup

### Reproduce step

1. Go to website https://phimchillc.net/

### Website url of issue

https://phimchillc.net/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/5728263d-22eb-4bf5-bbb3-7be5c7c8904d)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.19

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
It's a domain change from `phimchill1.co`
Updated via report tools for domain change: https://abpvn.com/report/ with commit https://github.com/abpvn/abpvn/commit/4918784a8f11070208577ccf6b559926f91cfe11

**Comment by hoangnm693** [comment]
Just feel confused a bit when using report tool for domain change.
For example in this case, i know `phimchillc.net` is new domain then how can I find the old ones (this case is `phimchill1.co`) to fill out in report tool?

**Comment by hoang-rio** [comment]
Most of case new domain will be similiar with old. In this case you can type phimchill in to old domain and this tool will auto suggest phimchill1.co
Then you can copy phimchill1.co to browser address bar. If it redirect to phimchillc.net you can return to report tool enter new domain and submit. If can not find old domain from suggest back to github and create new issue

**Comment by hoangnm693** [comment]
I typed phimchill into old domain in report tools (https://abpvn.com/report/) but no auto suggest appears.
Do i miss any steps?
<details>

![image](https://github.com/abpvn/abpvn/assets/130738821/1b8fef21-3f10-4b88-bc08-c87c2887fc02)

</details>

**Comment by hoang-rio** [comment]
I will check the reason why but if tool find match domain in ABPVN will show suggest like this ![Screenshot_20231018_183833_Firefox Beta.jpg](https://github.com/abpvn/abpvn/assets/11514638/a815b9f2-d1d9-4214-b641-92ef27cf00a5)
