### ISSUE TITLE
[NSFW] Exist ads on website: ["phevkl.biz"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#626]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

appear some ads when connect to site 

### Reproduce step

1. Go to website "phevkl.biz"
2. You can see it

### Website url of issue

phevkl.biz

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/b2acf2cd-6097-4eb3-86ac-232206123ebc)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/8b4104a5-c379-4274-9931-b1514910f5a1)

</details>

### Browser

Cốc Cốc Browser 121.0.188

### Adblocker

Adblock Plus 3.19

### Active filter list

EasyList + ABPVN List

**Comment by hoangnm693** [comment]
Banner ads still display with ABPVN
<details>

![image](https://github.com/abpvn/abpvn/assets/130738821/8334e811-3043-4f5c-bedd-a8631d01ee2d)


</details>

**Comment by hoang-rio** [comment]
> Banner ads still display with ABPVN
> <details>
> 
> ![image](https://github.com/abpvn/abpvn/assets/130738821/8334e811-3043-4f5c-bedd-a8631d01ee2d)
> 
> 
> </details>

Updated

**Comment by hoang-rio** [comment]
Updated. Please check
