### ISSUE TITLE
[NSFW] Exist ads on website: ["vlxx.studio"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#627]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

appear banner ads on the site 

### Reproduce step

1. Go to website "vlxx.studio"
2. you can see it

### Website url of issue

vlxx.studio

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/9143ef3b-a5f1-4e23-b0e3-db1159d74bd1)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/45cdb5ce-cd0f-4fe6-bedb-d6bc2c3a395b)

</details>

### Browser

Cốc Cốc Browser 121.0.188

### Adblocker

Adblock Plus 3.19

### Active filter list

EasyList + ABPVN List

**Comment by HoangHaiDang02** [comment]
hi @hoang-rio after recheck i found new banner on desktop mode with Chrome 118.help me recheck it thank you 
<details>
<summary>Click to open</summary>


![image](https://github.com/abpvn/abpvn/assets/91521634/55a66a7e-83d8-49ef-9ce1-d84039d42455)


</details>

**Comment by hoang-rio** [comment]
> hi @hoang-rio after recheck i found new banner on desktop mode with Chrome 118.help me recheck it thank you 
> <details>
> <summary>Click to open</summary>
> 
> 
> ![image](https://github.com/abpvn/abpvn/assets/91521634/55a66a7e-83d8-49ef-9ce1-d84039d42455)
> 
> 
> </details>

Updated. Please check
