### ISSUE TITLE
Exist ads on website: [animehay.city]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#628]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://animehay.city/thong-tin-phim/sousou-no-frieren-3888.html

### Website url of issue

https://animehay.city/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.20

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Popup block with ABP Filters via MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/27
