### ISSUE TITLE
Chặn QC trên thethao247.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#63]
Rule:
`thethao247.vn###lc-girl-block-en_2`
Element:
`<div class="livechat-girl js-livechat-girl animated" id="lc-girl-block-en_2" style="left:10px;bottom: 100px; top: auto;width: 155px;">`

**Comment by stephenhawk8054** [comment]
@hoang-rio Looks like there are new ads now.

URL: 
[https://thethao247.vn/aff-cup/365-truoc-them-gap-dtvn-dt-indonesia-quyet-lam-toi-cung-voi-btc-aff-cup-de-doi-lai-cong-bang-d246288.html](https://thethao247.vn/aff-cup/365-truoc-them-gap-dtvn-dt-indonesia-quyet-lam-toi-cung-voi-btc-aff-cup-de-doi-lai-cong-bang-d246288.html)

![image](https://user-images.githubusercontent.com/66517106/146110790-d9af3bdb-9ffc-425f-8b12-500bc08fc474.png)

Firefox 95.0, ublock 1.39.2 EasyList + ABPVN

Proposed filters:

```
||aj1047.online^
||serving.ad.org.vn^
||thethao247.vn/neo/*$subdocument
/quang-cao*.jpg$domain=thethao247.vn
##[href*="serving.ad.org.vn"]
```
