### ISSUE TITLE
[NSFW] Exist ads on website: ["sex.lenlut.net"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#634]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

appear pop-under same issue #606

### Reproduce step

1. Go to website "sex.lenlut.net"
2. turn on devtool and start mobile mode
3. choose video and site will redirect to the other site

### Website url of issue

sex.lenlut.net

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 01-11-2023 11:49:30.webm](https://github.com/abpvn/abpvn/assets/91521634/2aed8f67-d0d7-4dae-a649-bb11fb3e384d)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/07d578da-4092-4554-b23c-f235c442418c)

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.20

### Active filter list

ABP filters
ABPVN List+Easy List
EasyList

**Comment by hoang-rio** [comment]
See https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/30 for ABP Filters fix

**Comment by hoang-rio** [comment]
> i have detect when connect the site popup will appear help me recheck a @hoang-rio thank you link: https://sex.lenlut.net/
> Click to open

Fixed with source code view only. Please confirm
