### ISSUE TITLE
[NSFW] Exist ads on website: ["vn.xemsex.asia"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#635]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

appear pop-under on the site

### Reproduce step

1. Go to website "vn.xemsex.asia"
2. choose video and site wil redirect to the other site

### Website url of issue

vn.xemsex.asia

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 01-11-2023 12:05:43.webm](https://github.com/abpvn/abpvn/assets/91521634/58098dbc-a9ce-40ab-8dc2-15f78002c5be)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/304891dc-d548-4f53-81d4-17d437615a5c)

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.20

### Active filter list

ABP filters
ABPVN List+Easy List
EasyList

**Comment by hoang-rio** [comment]
See https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/30 for ABP Filters fix
