### ISSUE TITLE
[NSFW] Exist ads on website: [hentai-vn.com]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#637]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

pop-under appear on the site

### Reproduce step

1. Go to website "hentai-vn.com"
2. Choose video and site will redirect to the other site same #606 

### Website url of issue

hentai-vn.com

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 02-11-2023 16:11:29.webm](https://github.com/abpvn/abpvn/assets/91521634/8d9a7eeb-3ad0-420f-88b9-05f7f856f3c0)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/5609f872-7607-440b-9f14-14f32cd35dee)

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.20

### Active filter list

ABP filters
ABPVN List+Easy List
EasyList

**Comment by hoang-rio** [comment]
See https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/31 for ABP Filters popup block
