### ISSUE TITLE
[NSFW] Exist ads on website: [sieudamtv.com ]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#638]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

go to site "sieudamtv.com" appear pop-up(button close)

### Reproduce step

1. Go to website "sieudamtv.com"
2. You can see it

### Website url of issue

https://sieudamtv.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

<img width="1662" alt="image" src="https://github.com/abpvn/abpvn/assets/91521634/48211fa3-fa4c-40a9-9cae-fab44138e307">

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

<img width="1664" alt="image" src="https://github.com/abpvn/abpvn/assets/91521634/c8abaaaf-ea46-494a-96de-6e8e484fb735">

</details>

### Browser

Cốc Cốc 122.0.190

### Adblocker

Adblock Plus 3.20

### Active filter list

ABP filters
ABPVN List+Easy List
EasyList

**Comment by hoang-rio** [comment]
See https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/33 for ABP Filter

**Comment by hoang-rio** [comment]
sieudamtv.biz currently exists in ABPVN List with domain sex.sieudamtv.biz
