### ISSUE TITLE
Block incorrect on website: [linkneverdie.net]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#639]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Incorrect block description

Website is blank when ABP is turned on.

### Reproduce step

1. Go to website https://linkneverdie.net/

### Website url of issue

https://linkneverdie.net/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/4d9d2c65-4d60-49ef-99f7-d4d700c25170)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/79a4a840-b111-4c94-a94a-e7cfb990e139)

</details>

### Browser

Chrome 119

### Adblocker

Adblock Plus 3.20

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
See https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/32 for ABP Filters fix
