### ISSUE TITLE
Block incorrect on website: [zaloweb.vn]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#642]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Incorrect block description

Website show anti adblock popup

### Reproduce step

1. Go to website https://zaloweb.vn/

### Website url of issue

https://zaloweb.vn/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/2ef6e85d-b527-49c2-b14d-dbb2b04e8b3d)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 119

### Adblocker

Adblock Plus 3.20

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
This website may be scam/phishing. You should warn your user about it. Official website is https://zalo.me
For security reason i will block this website permanently in ABPVN List

**Comment by hoang-rio** [comment]
Another thing, if antiadblock popup is dismissable ABPVN will just skip it. Because it does block user to it's content. It just a warn/notice
