### ISSUE TITLE
Exist ads on website: [truyensieuhay.com]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#652]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)

### Ads description

appear banner ads

### Reproduce step

1. Go to website "truyensieuhay.com"
2. Banner show on the screen

### Website url of issue

truyensieuhay.com

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/4b360dbc-dba7-41a7-8c8c-d07940cd2977)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/9bf47eea-9e74-456c-9cf3-62840615c7ae)

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.20

### Active filter list

Easy List
ABP Filter
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
Popup can't show because the script show popup is blocked by ABP Filter with the rule bellow

```
truyensieuhay.com,quangcaoyenbai.com,khoaiphim.com,phimmoi.im,phimbom.net,sieudamtv.com#$#abort-on-property-read document.cookie
```

Here is blocked script

```javascript
function showPopUpBanner() {
        $('.popUpBannerBox').fadeIn("2000");
    }
    

    $('.popUpBannerBox').click(function (e) {
        if (!$(e.target).is('.popUpBannerContent, .popUpBannerContent *')) {
            $('.popUpBannerBox').fadeOut("2000");
            return false;
        }
    });
    $('.closeButton').click(function () {
        $('.popUpBannerBox').fadeOut("2000");
        return false;
    });
    console.log(getCookie("ads_bet10"));
    if (getCookie("ads_bet10") == "") {
        setTimeout(showPopUpBanner, 1000); //thời gian popup bắt đầu hiển thị
       // setCookie("ads_bet10", "dapopup", 0.02);
    }
```

<details>
<summary>Image when visit website im chrome</summary>

![ảnh](https://github.com/abpvn/abpvn/assets/11514638/9751902e-0858-416f-9db3-2caa139ccf60)

</details>

**Comment by HoangHaiDang02** [comment]
that is things i have seen. i will check on other device.Thank you for confirm
<details>
<summary>Click to open</summary>


![image](https://github.com/abpvn/abpvn/assets/91521634/d8f4ca57-704c-45d2-b881-fe04f8ef3e8d)


</details>

**Comment by hoang-rio** [comment]
There is some issue in your ABP Filters.
