### ISSUE TITLE
[NSFW] Exist ads on website: [quatvn.vip]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#653]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [x] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear pop-under on the site

### Reproduce step

1. Go to website "quatvn.vip"
2. click random posion on site screen site will redirect to other site

### Website url of issue

quatvn.vip

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 07-11-2023 15:20:06.webm](https://github.com/abpvn/abpvn/assets/91521634/ab2009d6-d10c-4b25-bef0-ccfbc5bb0849)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/7ba9bc08-b34b-4b10-8d42-84708b5313d9)

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.20

### Active filter list

EasyList
ABPVN List+EasyList
ABP Filters

**Comment by hoang-rio** [comment]
Hm. New checkpoint recently added "I did not answer truthfully to ALL the above checkpoints." so your did not answer truthfully?

**Comment by HoangHaiDang02** [comment]
no, i have create new user and implement rule above.And check with other device before create issue.help me check it.

<details>
<summary>Click to open</summary>


![image](https://github.com/abpvn/abpvn/assets/91521634/e6c0ab12-798e-431b-b1e3-773e770d8576)



</details>
