### ISSUE TITLE
 [NSFW] Block incorrect on website: [cliphotvn.pro]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#656]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Incorrect block description

Can't rewind video on site. Besides, the site is also unstable when watching videos, pls help me check

### Reproduce step

1. Go to link "https://cliphotvn.pro/hai-chi-em-dang-loan-luan-thi-phat-hien-bo-me-dat-camera/"
2. After watch video you can't rewind video

### Website url of issue

cliphotvn.pro

### Screenshot or screen capture when ABPVN enable

Can't rewind
<details>
<summary>Click to open</summary>

[Screencast from 09-11-2023 14:30:07.webm](https://github.com/abpvn/abpvn/assets/91521634/b3e9a1f7-e53c-472d-8087-99f821f91004)

</details>

Unstable
<details>
<summary>Click to open</summary>

[Screencast from 09-11-2023 14:33:13.webm](https://github.com/abpvn/abpvn/assets/91521634/eb65f193-b8d8-4a19-b6d1-454bbdfdbbad)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/d607c9b0-517b-4cd2-91f4-d10291e5a2a3)

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.20

### Active filter list

ABP filters
ABPVN List+EasyList
EasyList

**Comment by hoang-rio** [comment]
Did you check these issue when ABP disabled? I don't see normal function when disable ABP

**Comment by HoangHaiDang02** [comment]
I tried when adblock was off and it seemed to be blocked by rules:"**/v/*/vast.js$script,domain=~cdn2.kenhvn2.com**"

**Comment by hoang-rio** [comment]
Could you provide video when you feel it's normal and isn't normal?. I visited this website but I don't feel anything is not normal

**Comment by HoangHaiDang02** [comment]
this is video about problem
<details>
<summary>Click to open</summary>


[Screencast from 10-11-2023 13:35:39.webm](https://github.com/abpvn/abpvn/assets/91521634/49d0b291-35fb-462a-8156-b558cdd88ba2)


</details>

**Comment by hoang-rio** [comment]
This is not a issue. This site use two layer of player. First layer only for load video ads. when it blocked i will hide automatic shortly then show second layer that is real embed video player. If ads not blocked user must click skip ads to continue to real embed player

Rewind in both case enable or disable ABP is nothing different.

**Comment by HoangHaiDang02** [comment]
Thank you for information❤️
