### ISSUE TITLE
Block incorrect on website: [designervn.net]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#660]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Incorrect block description

website show anti adblock popup

### Reproduce step

1. Go to website https://designervn.net/

### Website url of issue

https://designervn.net/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/3760775e-54d5-432f-bd3a-a987600b3233)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 119

### Adblocker

Adblock Plus 3.21

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
This popup is closeable so user can close it by them self. With this type of anti adblock popup ABPVN will not process because it's does not block website feature.
