### ISSUE TITLE
[NSFW] Exist ads on website: [phim.sexabc.pro]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#661]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear pop-under on the site and banner ads

### Reproduce step

1. Go to website "phim.sexabc.pro"
2. you can see banner ads
3. after choose video 
4. click watch video site will redirect to other site

### Website url of issue

phim.sexabc.pro

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 14-11-2023 14:39:24.webm](https://github.com/abpvn/abpvn/assets/91521634/531b3cdf-1632-450e-9610-2589cde90778)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/f09f0b68-6318-4e12-8eac-b9806d34742f)

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.21

### Active filter list

ABP filters
ABPVN List+EasyList
EasyList

**Comment by hoang-rio** [comment]
ABP Filters fix MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/39

**Comment by hoang-rio** [comment]
See ABP Filters MR here: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/72
