### ISSUE TITLE
[NSFW] Exist ads on website: ["sex.ngonvcl.pro"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#663]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear banner ads and pop-under ads on the site "ngonvcl.pro" same issue #661
 

### Reproduce step

1. Go to website "sex.ngonvcl.pro"
2. you can see banner ads
3. after choose video
4. click watch video site will redirect to other site

### Website url of issue

sex.ngonvcl.pro

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 14-11-2023 15:00:05.webm](https://github.com/abpvn/abpvn/assets/91521634/64f8abc0-9533-47d7-826c-d004a0f3d7d6)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/b271b0d4-cdfa-497a-9cb1-9971eb5cced4)

</details>

### Browser

Chrome 118

### Adblocker

Adblock Plus 3.21

### Active filter list

ABP filters
ABPVN List+EasyList
EasyList

**Comment by hoang-rio** [comment]
> appear pop under ads same issue https://github.com/abpvn/abpvn/issues/661 anh @hoang-rio help me recheck the issue. thank you so much

Blocked with #661 because both of them use same domain for video frame
