### ISSUE TITLE
Exist ads on website: ["phimlongtieng.com"]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#668]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear some banner ads and pop-under ads on the site 

### Reproduce step

1. Go to website "phimlongtieng.com" and banner ads will appear
2. After chose film site will redirect to the other site 

### Website url of issue

phimlongtieng.com

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 27-11-2023 14:55:55.webm](https://github.com/abpvn/abpvn/assets/91521634/42e23f5e-9dc6-4a99-b446-8e8201059e74)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/00a1dd5f-3a35-45da-af12-114bdffd5598)

</details>

### Browser

Chrome 119

### Adblocker

Adblock Plus 3.21

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
See MR https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/41 for ABP Filters contribute
