### ISSUE TITLE
Chặn banner QC trên baodautu.vn [hiển thị trên mobile]

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#67]
### Rule:
`baodautu.vn###bottom-banner-mobile`
_Banner treo, che khuất một phần nội dung khi xem báo trên mobile._

### Before:

![Baodautu vn_Banner](https://user-images.githubusercontent.com/59459998/81361343-53357680-9108-11ea-9e88-ced49a395499.jpg)

### After:

![Baodautu vn_LostBanner](https://user-images.githubusercontent.com/59459998/81361802-8debde80-9109-11ea-8acc-3bd2272fee97.jpg)

**Comment by hoang-rio** [comment]
Nội dung này không phải quảng cáo mà chỉ là lời mới cái ứng dụng nên mình không chặn nhé
