### ISSUE TITLE
Exist ads on website: [protruyen.xyz]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#671]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website https://protruyen.xyz/doc-nguyen-ton-chuong-0.721.html

### Website url of issue

https://protruyen.xyz/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/0d365a8e-871e-43d0-8ea6-f823c88ce4f8)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 119

### Adblocker

Adblock Plus 3.21.1

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
ABPVN will not process if website still allow user use it. To block this type please find or report to a Annoyances filter list
