### ISSUE TITLE
[NSFW] Block incorrect on website: [sex.heovl.io]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#673]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Incorrect block description

appear banner ads on the site

### Reproduce step

1. Go to site "https://sex.heovl.io/"
2. You can see banner ads

### Website url of issue

https://sex.heovl.io/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/996ec016-b08e-44df-acfe-75533149a800)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/082f4982-c654-4fc5-b237-b713ec658534)

</details>

### Browser

Chrome 119

### Adblocker

Adblock Plus 3.21.1

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
Please choose correct template
