### ISSUE TITLE
[NSFW] Exist ads on website: [dualeotruyenww.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#675]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://dualeotruyenww.com/

### Website url of issue

https://dualeotruyenww.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 119

### Adblocker

Adblock Plus 3.21.1

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
This site redirect from dualeotruyenpk.com
Check MR https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/43 for update
