### ISSUE TITLE
Exist ads on website: [chillphimmoi.org]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#676]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear banner ads and pop-under ads on the site "chillphimmoi.org"

### Reproduce step

1. Go to website "chillphimmoi.org"
2. You can see banner ads
3. after chose film when click watch film site will redirect to other site

### Website url of issue

chillphimmoi.org

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 06-12-2023 15:02:15.webm](https://github.com/abpvn/abpvn/assets/91521634/57de0906-1bf1-4653-b334-1826711fb21a)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/a3222b95-7b0e-4f02-94b0-d85cd3c09eb9)

</details>

### Browser

Chrome 119

### Adblocker

Adblock Plus 3.21.1

### Active filter list

ABP filters
ABPVN List+EasyList
EasyList

**Comment by hoangnm693** [comment]
hi @hoang-rio 
pop under ads display when clicking play video button
URL: https://chillphimmoiz.org/xem-phim/nhu-hoa-tren-cat-d07da0-tap-1
<details>

![image](https://github.com/abpvn/abpvn/assets/130738821/70a794c0-75fd-4010-8090-1f624ce4ec37)

</details>
Pls check it.
Thanks.
