### ISSUE TITLE
Exist ads on website: [truyenvnhay.tv]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#680]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear pop-under on the site. anh @hoang-rio help me check issue

### Reproduce step

1. Go to website "truyenvnhay.tv"
2. click random position on the site.
3. site will redirect to other site

### Website url of issue

truyenvnhay.tv

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 28-12-2023 16:14:07.webm](https://github.com/abpvn/abpvn/assets/91521634/1a1d251d-de13-4a71-95e3-c6a582e17caa)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 120

### Adblocker

3.21.1

### Active filter list

ABPVN List+EasyList
ABP filters

**Comment by hoang-rio** [comment]
Checkout Popup block with ABP Filters at [eyeo/anti-cv/abp-filters-anti-cv#58](https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/58)
