### ISSUE TITLE
Exist ads on website: [abtruyen.com]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#684]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Banner ads & popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://abtruyen.com/truyen-tranh/toi-thang-cap-mot-minh-7131

### Website url of issue

https://abtruyen.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/fc2acbc8-035c-4188-bc10-566b94059354)
![image](https://github.com/abpvn/abpvn/assets/130738821/f73a845d-571a-49a5-87c3-35ed887be874)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 120

### Adblocker

Adblock Plus 3.21

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
See merge request https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/71 to follow fix in ABP Filters
