### ISSUE TITLE
Chặn mã QC trên download.com.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#69]
Đề nghị cập nhật rule:
```
/meta.vn/ajx/Ajx_TopProducts2.aspx$domain=quantrimang.com
```
Thành rule:
```
/meta.vn/ajx/Ajx_TopProducts2.aspx$domain=quantrimang.com|download.com.vn
```
Script QC nằm trong:
```
https://download.com.vn/scripts/main.mobile.bundle.min.js?v=0805
```
_(Công ty META là chủ quản của cả quantrimang và download, script QC cũng giống như nhau)_

**Comment by vhpcdpgl** [comment]
**Rule đề nghị chung cho các script quảng cáo trên quantrimang.com và |download.com.vn:**
`/cache.aspx$domain=quantrimang.com|download.com.vn`

**Rule hiện có trên abpvn:**
```
||static.download.com.vn/cache.aspx?_path=*ad$script
/meta.vn/ajx/Ajx_TopProducts2.aspx$domain=quantrimang.com|download.com.vn
```

_Các script quảng cáo (meta.vn và realclick.vn) của quantrimang.com và download.com.vn đều load từ file cache.aspx, mình đã test nhiều lần trên PC và mobile, fiví dụ:_

```
https://quantrimang.com/cache.aspx?_path=http://meta.vn/ajx/Ajx_TopProducts2.aspx&top=2&min=-&max=-&kw=&ids=
https://quantrimang.com/cache.aspx?_path=https://realclick.vn/client/banner/&mod=lazy&data=zone|419|mrc419|zone|311|mrc
http://static.download.com.vn/cache.aspx?_path=http://realclick.vn/client/banner/&amp;mod=lazy&amp;data=zone|190|underfeaturedbox|pos|941|ad_right2|zone|134|adrighttop
```

**Comment by hoang-rio** [comment]
Nếu dùng rule như thế khả năng sẽ chặn hết cả các tài nguyên khác được load qua file cache.aspx bạn ạ. Vậy không ổn lắm
