### ISSUE TITLE
Exist ads on website: [phimgichill.net]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#690]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://phimgichill.net
2. wait about 15 seconds
3. click on page then popunder ads appear

### Website url of issue

https://phimgichill.net/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 120

### Adblocker

Adblock Plus 3.21

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
Please make sure that ABP Filters is enabled.
If you still can reproduce please profile screen capture video because I can not reproduce. Next time don't forget provide screen shot/screen capture since create issue

**Comment by hoangnm693** [comment]
@hoang-rio pop-under ads only appears after around 10~15 seconds.
<details>

https://github.com/abpvn/abpvn/assets/130738821/767215f2-5837-449a-9119-c890f2757655

</details>
Can you check it again?

**Comment by hoang-rio** [comment]
> @hoang-rio pop-under ads only appears after around 10~15 seconds.
> Can you check it again?

It's done via https://github.com/abpvn/abpvn/commit/ff6f217fb66976dba625bf3dcc0972ccdb1e6c69 please update ABPVN to lastest version

**Comment by hoang-rio** [comment]
Something are incorrect so I reopen this issue

**Comment by hoang-rio** [comment]
This pop under need fix via ABP Filters. Here is merge request: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/76
