### ISSUE TITLE
Exist ads on website: [gocphimvn.vip]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#691]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Banner ads still display with ABPVN

### Reproduce step

1. Go to website https://gocphimvn.vip/phim/nu-phap-y-jd/cXyanZZs.html

### Website url of issue

https://gocphimvn.vip/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/ad0ef740-6d0e-4753-beb2-e185c0162348)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 120

### Adblocker

Adblock Plus 3.21

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
I saw you are turn off ABP when you make screen shot for "When ABP Enabled". What is going on? I've just checked and banner did not appear

**Comment by hoangnm693** [comment]
@hoang-rio sorry about that.
I turned on ABP then banner ads disappear but still get pop under ads.
<details>

https://github.com/abpvn/abpvn/assets/130738821/2d485194-7657-49b7-8160-0698207b742c

</details>
Can you check it again?

**Comment by hoang-rio** [comment]
> @hoang-rio sorry about that. I turned on ABP then banner ads disappear but still get pop under ads.
> Can you check it again?

Popunder ads blocked in ABP Filters with merge request https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/74
