### ISSUE TITLE
Exist ads on website: [truyengihotvay.net]

### ISSUE THREAD

**Issue by hoangnm693** [abpvn/abpvn#692]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Banner ads & popunder ads still display with ABPVN

### Reproduce step

1. Go to website https://truyengihotvay.net/doc-nang-phu-thuy-cua-toi-chuong-61.2.html

### Website url of issue

https://truyengihotvay.net/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/130738821/6961fa17-59bb-4a77-8d68-f406ccc97c5f)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 120

### Adblocker

Adblock Plus 3.21

### Active filter list

* ABP filters
* ABPVN List+Easy List
* EasyList

**Comment by hoang-rio** [comment]
See ABP Filter merge request here https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/74
