### ISSUE TITLE
site ko block  dc 

### ISSUE THREAD

**Issue by yagano1** [abpvn/abpvn#7]
truyenyy.com

**Comment by abpvn** [comment]
Không block được chỗ nào vậy bạn?

**Comment by yagano1** [comment]
có 1 cái ads chạy dọc bên  trái khi đọc  chương truyện.
http://prntscr.com/fe5zsf

**Comment by abpvn** [comment]
Bạn đang sử dụng những bộ lọc nào vậy?

**Comment by yagano1** [comment]
chỉ mình abpvn thôi. cái ko làm easylist.

**Comment by abpvn** [comment]
List thường thì bạn cần kết hợp thêm EasyList vì cái này có trong EasyList rồi nên mình không thể đưa vào bộ lọc được. @yagano1 bạn dùng thêm EasyList nhé!

**Comment by yagano1** [comment]
oh tks nhé .

**Comment by abpvn** [comment]
Nếu bạn muốn sử dụng bộ lọc ABPVN riêng biệt  thì bạn sử dụng list vip nhé! List này có thể dùng độc lập mà không cần EasyList.

**Comment by yagano1** [comment]
oh trước mình có ủng hộ  nhưng bữa đó hình như bị lỗi gì đó ko thây link. để tối mình donate lại.
cái  trang kia mình thấy nó block dc ads nhưng hình như ko dc  triệt để như các trang khác mà vẫn đẻ lại 2 dấu x nhỏ ko đáng kể .

**Comment by abpvn** [comment]
Dấu x nhỏ thì bạn update bộ lọc là hết nhé. Mình đã update bộ lọc rồi
