### ISSUE TITLE
 [NSFW] Exist ads on website: [javhd.tech]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#701]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear some banner ads on the site 

### Reproduce step

1. Go to link https://javhd.tech/play-video/1009/dqe8-em-hang-xom-dam-dang-cua-toi
2. You can see it 

### Website url of issue

https://javhd.tech/play-video/1009/dqe8-em-hang-xom-dam-dang-cua-toi

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/a470da8e-68b4-4cb3-89d1-26eaddd3d28b)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/02d41871-b939-47af-97f5-3191d5b5d50b)

</details>

### Browser

Chrome 120

### Adblocker

Adblock Plus 3.22

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
> hi anh @hoang-rio 
> currently site appear popunder when click watch film
> help me check and fix problem at https://javhd.tech/play-video/9518/gt7s-mot-bo-phim-sex-khong-che-cua-co-nang-hikari-aozora

Checked but popup was blocked by EasyList
