### ISSUE TITLE
[NSFW] Exist ads on website: [truyengihotqua.com]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#703]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear pop-under on the site truyengihotqua.com

### Reproduce step

1. Go to website truyengihotqua.com
2. Click choose option site will redirect to other site help me check

### Website url of issue

truyengihotqua.com

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 15-01-2024 09:25:09.webm](https://github.com/abpvn/abpvn/assets/91521634/ffedab06-4ce7-4732-83fe-11f8868ba022)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/9fb95203-0747-4ae8-80a8-b176555b7d1e)

</details>

### Browser

Chrome 120

### Adblocker

Adblock Plus 3.22

### Active filter list

ABPVN List+EasyList
ABP filters

**Comment by hoang-rio** [comment]
See ABP Filters MR here: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/89
