### ISSUE TITLE
Chặn banner QC trên phimgi.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#72]
**Rules:**
```
phimgi.tv###ric_pc_floatleft1
phimgi.tv###yo88_pc_bottomplayer
phimgi.tv###vic_pc_topplayer
phimgi.tv###may_pc_top
```
**Ví dụ:** mở một trang xem phim, các banner xuất hiện :

`https://phimgi.tv/xem-phim/ke-dam-len-knives-out-tap-1-server-1/`

**Hình:**

![phimgi tv](https://user-images.githubusercontent.com/59459998/82773870-5e5d0600-9e6d-11ea-881b-e9d9b6c1a1fb.png)

**Comment by hoang-rio** [comment]
Mình vào link trên nhưng không thấy banner nào cả. Nên mình close issue này nhé
![phimgi tv](https://user-images.githubusercontent.com/11514638/82778754-78eaab80-9e7c-11ea-835c-2e3b737f05a2.PNG)

**Comment by vhpcdpgl** [comment]
> Mình vào link trên nhưng không thấy banner nào cả. Nên mình close issue này nhé
> ![phimgi tv](https://user-images.githubusercontent.com/11514638/82778754-78eaab80-9e7c-11ea-835c-2e3b737f05a2.PNG)
> 

Lạ nhỉ. Như bạn thấy mình bật ublock origin mà vẫn dính qc. Hay là máy bạn có chặn bằng domain nữa nên nó ko hiển thị banner?

**Comment by hoang-rio** [comment]
Bạn đang bật những bộ lọc nào ở ublock origin vậy?

**Comment by stephenhawk8054** [comment]
@hoang-rio There are ads in new domain `phimgii.tv`

URL:
`https://phimgii.tv/xem-phim/thi-tran-riverdale-phan-2-riverdale-season-2-tap-8-server-1/`

Screenshot:

![image](https://user-images.githubusercontent.com/66517106/146350881-7d3482ab-a33c-4a13-821f-8ceb5fa97f2f.png)

Firefox 95.0, ublock 1.39.2 EasyList + ABPVN

Proposed filters: replace `phimgii.net` by `phimgii.tv`

Also there are some typos (lack 1 `#`) with these filters:

```
fimnhez.net,vaophim.org,phimgii.net,phimhdvns.net#.mobile-catfix
phimgii.net,phimhdvns.net#.lightbox-player-pc
phimgii.net,phimhdvns.net#div[id^="preload-"]
! For ublock
phimgii.net,phimhdvns.net#+js(acis, jQuery, popurl)
```
