### ISSUE TITLE
Block incorrect on website: [fonts.googleapis.com]

### ISSUE THREAD

**Issue by IbraheemEhab** [abpvn/abpvn#727]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Incorrect block description

This website is used to show fonts of google in websites

### Reproduce step

1. Go to website

### Website url of issue

http://fonts.googleapis.com/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/56744552/533d8920-7cb3-46d8-9bb4-ce571974430d)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/56744552/590a4cc0-17d1-4060-b822-9f968bf6a8d7)

</details>

### Browser

Firefox 122

### Adblocker

NextDNS

### Active filter list

A lot of Lists inside the dns

**Comment by phuonganh2601** [comment]
> NextDNS does not support Adblock Plus syntax that is syntax made ABPVN List. Please don't try to add block list if you don't know about compability

Mình sử dụng AdguardHome và cũng đang bị tình trạng block nhầm fonts.googleapis.com
![image](https://github.com/abpvn/abpvn/assets/61279348/e7548c89-4525-4dfc-b6ec-100033c144b7)

**Comment by hoang-rio** [comment]
> > NextDNS does not support Adblock Plus syntax that is syntax made ABPVN List. Please don't try to add block list if you don't know about compability
> 
> Mình sử dụng AdguardHome và cũng đang bị tình trạng block nhầm fonts.googleapis.com
> ![image](https://github.com/abpvn/abpvn/assets/61279348/e7548c89-4525-4dfc-b6ec-100033c144b7)
> 

Bạn bấm vào xem chi tiết xem quy tắc nào chặn. Mình có kiểm tra ABPVN List rồi và không có quy tắc nào chặn tên miền này hết

**Comment by hoang-rio** [comment]
Sau khi kiểm tra đi kiểm tra lại thì chỉ có file host ABPVN là chứa quy tắc chặn tên miền fonts.googleapis.com nếu các bạn đúng là đang dùng host ABPVN thì update nhé. Mình cũng đã đổi tên để tránh nhầm lần

**Comment by phuonganh2601** [comment]
Chi tiết quy tắc chặn như sau:
![image](https://github.com/abpvn/abpvn/assets/61279348/a93a9630-8d42-4171-a1c9-28db46cfb64d)

Mình đang sử dụng ABPVN List chọn sẵn trong danh sách của Adguard có đường link như sau:
https://adguardteam.github.io/HostlistsRegistry/assets/filter_16.txt

Sau khi cập nhật bộ lọc thì mọi thứ đã hoạt động bình thường.
Cảm ơn bạn nhiều.
