### ISSUE TITLE
Exist ads on website: [truyengihotnha.com]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#737]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear banner ads and popunder ads

### Reproduce step

1. Go to link https://truyengihotnha.com/doc-15-ly-do-ket-hon-chuong-4.2.html
2. After click random position in screen site will redirect to other site
3. And banner ads appear as video

### Website url of issue

https://truyengihotnha.com/doc-15-ly-do-ket-hon-chuong-4.2.html

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 01-03-2024 11:20:21.webm](https://github.com/abpvn/abpvn/assets/91521634/d8a1bf30-66f5-456e-9dc5-2d4b57c557a9)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/28b6abe5-ac4a-4ce8-8310-50eb5463ad94)

</details>

### Browser

Chrome 121

### Adblocker

Adblock Plus 3.24.1

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
> hi anh @hoang-rio domain truyengihotnha.net same. Should I create new issue ??

New issue for replica domain is accepted but just a comment will be better

**Comment by hoang-rio** [comment]
Please follow this MR: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/merge_requests/143

**Comment by hoang-rio** [comment]
Checked but no problem found
