### ISSUE TITLE
[NSFW] Exist ads on website: [phimsexviet.io]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#741]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear pop up in the site

### Reproduce step

1. Go to website phimsexviet.io
2. You can see it

### Website url of issue

phimsexviet.io

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/3769bf48-7fe7-40ca-a365-34a8dc9c6424)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/86a14f80-b4e6-48ed-a8a4-aff890e60a63)

</details>

### Browser

Chrome 122

### Adblocker

Adblock Plus 3.24.1

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
> xx.phimsexnhathay.com still appear help me check

Because of you said it's same as phimsexviet.io so I create same filter for all. But xx.phimsexnhathay.com is difference because it does not using js file `/theme/custom.int.js` so please create new issue for it
