### ISSUE TITLE
[NSFW] Exist ads on website: [sex.damxx.vip]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#742]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear pop under and banner ads in the site

### Reproduce step

1. Go to website sex.damxx.vip
2. After chose film site will redirect to other site
3. You can see banner ads same video 

### Website url of issue

sex.damxx.vip

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

[Screencast from 05-03-2024 14:27:59.webm](https://github.com/abpvn/abpvn/assets/91521634/76b44d1a-83c7-4886-86ad-09b362c341ef)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/376dfbaf-ae70-4e3d-bb19-e14a77412630)

</details>

### Browser

Chrome 122

### Adblocker

Adblock Plus 3.24.1

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
Redirected to sexphetv.pro
