### ISSUE TITLE
Block incorrect on website: [coldflownews.com]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#756]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Incorrect block description

appear custom rule wrong.
site can't load 

### Reproduce step

1. Go to website coldflownews.com
2. Site can't load css
3. You can see it

### Website url of issue

coldflownews.com

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/c1398874-ef5a-4b56-b053-a98a5d90c27d)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

</details>

### Browser

Chrome 123

### Adblocker

Adblock Plus 3.25.1

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
@HoangHaiDang02 Why you never read and check all required checklist above? I told you onetime in #746.

**PLEASE DON'T CREATE ISSUE LIKE THIS ONE MORE TIME. THANKS**

**Comment by hoang-rio** [comment]
For debug please use separate version EasyList and ABPVN List instead of combined version to find which is cause of problem.

![ảnh](https://github.com/abpvn/abpvn/assets/11514638/46bdf056-72cc-487b-acdc-79466ecb728a)
