### ISSUE TITLE
Chặn QC trên tinhte.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#76]
Rule đề xuất:
`||tinhte.vn/js/bdAd/*`

Script:
`https://tinhte.vn/js/bdAd/loader.min.js?_v=dd54c956`

Đoạn mã trên load QC từ Google:
```
pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
www.googletagservices.com/tag/js/gpt.js
```

**Comment by hoang-rio** [comment]
Quảng cáo của google căn bản đã bị EasyList chặn hết. Nếu không chặn script trên thì có quảng cáo hiển thị không bạn?

**Comment by vhpcdpgl** [comment]
Nếu bật cả easylist thì đúng là nó ko bật được.

**Comment by hoang-rio** [comment]
Ne

> Nếu bật cả easylist thì đúng là nó ko bật được.

Nếu vậy mình reject và close nhé
