### ISSUE TITLE
Chặn banner QC trên hosocongty.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#77]
**Rule đề xuất 1:**
`||blogfonts.com^$domain=hosocongty.vn,image`
**URL:**
`https://blogfonts.com/fonts/fontblogs-banner.png`

**Rule đề xuất 2:**
`||hosocongty.vn/uploads/products/*$domain=hosocongty.vn,image`
**URL:**
```
https://hosocongty.vn/uploads/products/quang-cao-do-gen.jpg
https://hosocongty.vn/uploads/products/quang-cao-do-genvn.jpg
```

**Comment by hoang-rio** [comment]
Rule 1 hình như chặn hơi nhiều và thừa
Rule 2 có thể gây chặn nhầm ảnh khác trên trang web nhé

**Comment by vhpcdpgl** [comment]
> Rule 1 hình như chặn hơi nhiều và thừa
> Rule 2 có thể gây chặn nhầm ảnh khác trên trang web nhé

Rule 1 chỉ có 1 cái ảnh chính là banner đó thôi.
Rule 2 cũng chỉ có 2 ảnh là 2 banner thôi. Các ảnh thông thường khác không trùng với 2 rule trên đâu bạn. Mình đã test nhiều tin khác nhau và xem log bằng cả adguard và nano adblocker.

**Comment by stephenhawk8054** [comment]
There are ads placeholders in the site now.

URL: `https://hosocongty.vn/`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/142965019-c63a24d9-993b-43bc-8cae-97f6b2904820.png)

</details>

Proposed filters:

```
hosocongty.vn##.advertTop
hosocongty.vn##.hsdn > li:not(> h3)
```
