### ISSUE TITLE
Exist ads on website: [phimmoi.vc]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#771]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

appear popup and some banner ads on the site

### Reproduce step

1. Go to website https://phimmoi.vc/
2. You can see ads in the site

### Website url of issue

https://phimmoi.vc/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/16c52e8e-9f39-41d4-b699-f22fa0aa4928)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/b4dbb155-5b26-48b4-8076-e93d7bdac6d4)

</details>

### Browser

Chrome 121

### Adblocker

Adblock Plus 3.25.1

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by playonevideo** [comment]
Ads on `https://phimmoi21.net/xem-phim/tyler-rake-nhiem-vu-giai-cuu-2-tap-1-server-1/`:

<img width="1757" height="289" alt="Image" src="https://github.com/user-attachments/assets/7b27c9c4-1c0d-4a24-b0db-e332e7c08d49" />

**Comment by hoang-rio** [comment]
> Ads on `https://phimmoi21.net/xem-phim/tyler-rake-nhiem-vu-giai-cuu-2-tap-1-server-1/`:
> 
> <img width="1757" height="289" alt="Image" src="https://github.com/user-attachments/assets/7b27c9c4-1c0d-4a24-b0db-e332e7c08d49" />

Please create new issue instead of comment

**Comment by playonevideo** [comment]
Alright, I noticed the site was the same as here, but with a different domain, and I didn't want to open a duplicate.
