### ISSUE TITLE
Anti adblock on website: [thientue.vn]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#781]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Incorrect block description

popup anti adblock appear when open the site

### Reproduce step

1. Go to website thientue.vn
2. You can see it

### Website url of issue

https://thientue.vn/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/02e88ab7-5129-4316-bb65-bcc5d59199a5)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/abpvn/abpvn/assets/91521634/e634c536-634d-4bb6-807d-dd8cccc6e91c)

</details>

### Browser

Chrome 121

### Adblocker

Adblock Plus 3.25.1

### Active filter list

ABPVN List+EasyList
ABP filters

**Comment by hoang-rio** [comment]
This dialog can be close so ABPVN will not process it because user can close dialog then continue use website
