### ISSUE TITLE
[NSFW] Exist ads on website: [mobiblog.club]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#787]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Appear banner ads and popunder ads on the site. Help me check it

### Reproduce step

1. Go to website https://mobiblog.club/
2. You can see it

### Website url of issue

https://mobiblog.club/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/user-attachments/assets/17716527-d0f4-4e3b-8756-8cf98d606788)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/user-attachments/assets/57ddf7bb-4a5e-4c60-b210-5ca22f3b293a)

</details>

### Browser

Chrome 125

### Adblocker

Adblock Plus 3.25.1

### Active filter list

ABPVN List+EasyList
ABP filters

**Comment by hoang-rio** [comment]
@HoangHaiDang02 ABP 4.4 with MV3 on Chrome stopped working on snippet rule on most of case. Please contact ABP Team (at eyeo). I can't support anymore if snippet rule do not work
