### ISSUE TITLE
Chặn QC trên bongdaso.com

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#79]
Rule đề xuất:
`bongdaso.com##blink`

Hình:

![Untitled](https://user-images.githubusercontent.com/59459998/83621210-91fc0680-a5b8-11ea-8b12-0bade88bc1be.png)

**Comment by stephenhawk8054** [comment]
There are ads and placeholders in the site now.

URL: `http://bongdaso.com/news.aspx`
<details><summary>Screenshot 1</summary>

![3](https://user-images.githubusercontent.com/66517106/142797320-16927791-6f07-4d8b-a066-134d3ee7a44c.png)

</details>
<details><summary>Screenshot 2</summary>

![2](https://user-images.githubusercontent.com/66517106/142797428-4cb45f78-d9a5-4c08-828a-66f708d6055c.png)

</details>

URL: `http://bongdaso.com/Solskjaer-r%e1%bb%9bm-n%c6%b0%e1%bb%9bc-m%e1%ba%aft-n%c3%b3i-l%e1%bb%9di-chia-tay-MU-_Art_235337.aspx`
<details><summary>Screenshot 3</summary>

![1](https://user-images.githubusercontent.com/66517106/142797404-5f6d80dc-46b8-487b-ad74-8b9370709684.png)

</details>

Firefox 94.0.1, ublock 1.38.6 default + ABPVN

Proposed filters:

```
||bongdaso.com/_BannerSlot.aspx$subdocument
bongdaso.com##.art_header_text
bongdaso.com##[class*="_banner"]
bongdaso.com##[id$="float_banner"]
```
