### ISSUE TITLE
Error on website: voz.vn

### ISSUE THREAD

**Issue by blactin** [abpvn/abpvn#790]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Filter block content on web

### Reproduce step

1. Go to website

### Website url of issue

voz.vn

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![firefox_VlzMKu5vDt](https://github.com/user-attachments/assets/c926f1ca-d728-46df-a4de-41ca5a20e824)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![firefox_4xsFvBaa7q](https://github.com/user-attachments/assets/878f54f7-7d09-4c41-a4ae-111e7dc6bd44)

</details>

### Browser

Firefox 128.0.3

### Adblocker

Adguard

### Active filter list

AdGuard Base Filter + AdGuard Mobile Filter + AdGuard Tracking Protection Filter + AdGuard Annoyances Filter + Online Malicious URL Blocklist + ABPVN List

**Comment by hoang-rio** [comment]
Your ABPVN List is outdated. Please update to lastest version please

**Comment by blactin** [comment]
> Your ABPVN List is outdated. Please update to latest version please

Just updated, problem still there.
Only on Firefox (Chromium like Edge, Arc,... still good).

**Comment by hoang-rio** [comment]
Checked but no problem found.
![Screenshot_20240803_215120_Firefox Beta.jpg](https://github.com/user-attachments/assets/eef1602f-cb19-46c7-922b-d6adc0a29a4a)
