### ISSUE TITLE
Block incorrect on website: [voz.vn]

### ISSUE THREAD

**Issue by blactin** [abpvn/abpvn#791]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### Incorrect block description

[class="block-body''] blocked by ABPVN List

### Reproduce step

1. Go to website

### Website url of issue

https://voz.vn/t/microsoft-w-nd0m-x-tut-tun-tut-vo-day-het.3937/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![firefox_SkjaBoVDPK](https://github.com/user-attachments/assets/a2bc6f8b-3796-49d1-9035-efd24c5cd6a5)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![firefox_Buf0ojh00g](https://github.com/user-attachments/assets/52081e94-711f-49c9-a14a-6e66c7a585b2)

</details>

### Browser

Firefox 128.0.3

### Adblocker

Adguard; uBlock Origin

### Active filter list

ABPVN List

**Comment by hoang-rio** [comment]
Checked but no problem found. I see the website design is not like original please disable another method to change website layout. It may be the problem

**Comment by blactin** [comment]
> Checked but no problem found. I see the website design is not like original please disable another method to change website layout. It may be the problem ![Screenshot_20240803_215120_Firefox Beta.jpg](https://private-user-images.githubusercontent.com/11514638/354824139-44bd2314-cedd-4b9c-a4f4-29271dc191b7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTc2MTUsIm5iZiI6MTcyMjY5NzMxNSwicGF0aCI6Ii8xMTUxNDYzOC8zNTQ4MjQxMzktNDRiZDIzMTQtY2VkZC00YjljLWE0ZjQtMjkyNzFkYzE5MWI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE1MDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NTViOTg5ZjY0MTdlZDE1MWY1NWFmMjllZGE0YTg2YjMzNDczMWNhNDM1YWVkYTVlZGUyMGU5MGRjMmU1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lMhlKKhf1-FcIvY2FvG3HoRwKoCYFpriYbUkD6-y8CA)

I have figured out the problem. I am using an add-on called Sauron instead of Dark Reader. I turned it off, and now the problem is resolved. Thank you for your help.
