### ISSUE TITLE
[NSFW] Exist ads on website: [phevkl.uk]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#795]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Appear banner, popup and popunder ads on the site. Help me check

### Reproduce step

1. Go to website https://phevkl.uk/
You can see it

### Website url of issue

https://phevkl.uk/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/user-attachments/assets/ac82b23d-c243-4205-8379-2248e35f7b08)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![Uploading image.png…]()

</details>

### Browser

Chrome 126

### Adblocker

Adblock Plus 4.5.1

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
> Hi a @hoang-rio . I checked the see the site redirect to **phevkl.blo**g and have popunder (phevkl.blo existing on ABPVN List). That mean is the other problem appear Help me fix it, pls

Which domain do you want to report ads? phevkl.blog  is existing on ABPVN List at this moment
