### ISSUE TITLE
[NSFW] Exist ads on website: [pheclip.one]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#803]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Ads description

Appear popunder and banner ads on the site

### Reproduce step

1. Go to website https://pheclip.one/
2.You can see popunder and popup ads after choose the movie

### Website url of issue

https://pheclip.one/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/user-attachments/assets/9c9adef8-210f-4764-b86a-c95c77ca95a5)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![Screenshot 2024-11-01 at 15 35 56](https://github.com/user-attachments/assets/f8d028e1-ce27-4ae2-8ca6-e16c561e3c95)

</details>

### Browser

Chrome 129

### Adblocker

Adblock Plus 4.8

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
> site redirected to pheclipsex.com I've report at [here](https://abpvn.com/report/) but It isn't impact help check it a @hoang-rio

Checked with current version of ABPVN List and no ads found. Site redirection being process in 3e3d37936ded7057543fcc50b3cc8905c31f0f2b
