### ISSUE TITLE
[NSFW] Appear anti adblock on website: [sexdiary.club]

### ISSUE THREAD

**Issue by HoangHaiDang02** [abpvn/abpvn#804]
### Checklists

- [X] Updated ABPVN List to latest version
- [X] Added prefix [NSFW] in issue title with site contain adult content
- [X] Searched domain in both open and close issue with same issue type
- [X] Reproduce rate is over 50%
- [X] Replace [domain] in issue title with issue domain
- [X] Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
- [X] Reported website must be belong to Vietnamese (also not is global website support Vietnamese)
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### Incorrect block description

Appear anti block after click watch the movie some second

### Reproduce step

1. Go to website https://sexdiary.club/chi-may-bay-ngoai-tinh-cung-dong-nghiep/
2. Choose watch the movie, the wall will appear after some second(10s)

### Website url of issue

https://sexdiary.club/chi-may-bay-ngoai-tinh-cung-dong-nghiep/

### Screenshot or screen capture when ABPVN enable

<details>
<summary>Click to open</summary>

![image](https://github.com/user-attachments/assets/185ac258-b975-4e7a-8936-34eeb807baec)

</details>

### Screenshot or screen capture when ABPVN disabled

<details>
<summary>Click to open</summary>

![image](https://github.com/user-attachments/assets/38104534-016d-4f26-a9b2-37ed45843285)

</details>

### Browser

chrome 129

### Adblocker

adblock plus 4.9

### Active filter list

ABP filters
ABPVN List+EasyList

**Comment by hoang-rio** [comment]
This site use video frame from dood.ws. It's non Vietnamese website so ABPVN can't process it. Please report to EL instead
