### ISSUE TITLE
Chặn banner QC trên xemphimso.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [abpvn/abpvn#82]
Rule đề xuất:
`xemphimso.tv/ads/*$image`
hoặc rule chung:
`/ads/*$image`
 Ex:
```
https://xemphimso.tv/ads/ballonpc.gif?v=6
https://xemphimso.tv/ads/top1mb.gif?v=5
https://xemphimso.tv/ads/sunwin2.gif?v=6
```

**Comment by hoang-rio** [comment]
Cái này có rule này chặn rồi mà bạn https://github.com/abpvn/abpvn/blob/65fdc2949c472f80b398972e88c26272cf2553e3/filter/src/abpvn_general.txt#L13
