### ISSUE TITLE
Lỗi linkneverdie.com

### ISSUE THREAD

**Issue by LaxusiC** [abpvn/abpvn#9]
Khi click nút Download trên trang web linkneverdie.com nó sẽ chuyển sang 1 trang khác yêu cầu nhập capcha để download, vấn đề là phiên bản cũ của abpvn sau khi xác nhận capcha xong click nút download sẽ down được

Không hiểu sao hôm nay thì lỗi, không tài nào click được nút Download trên linkneverdie nữa, mình phải untick bộ lock ABPVN thì ok

Mình dùng Chrome (Win 10) - uBlock

**Comment by abpvn** [comment]
Đã fix ở commit https://github.com/abpvn/abpvn/commit/b08b87c8bdcc5345260ab5d23b5be358d3f9a383 bạn nhé. Bạn update bộ lọc và check lại giúp mình nhé

**Comment by abpvn** [comment]
Nếu còn bị thị bạn update lần nữa là hết nhé
